## 연속형 자료

In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt

In [2]:
import pandas as pd

jido=pd.read_csv(r'C:\Users\stat_17\Desktop\지역좌표.csv', encoding='CP949')

In [3]:
x=jido.iloc[:, 3:4]
y=jido.iloc[:, 4:4+1]

import numpy as np
x=x.values.tolist()
y=y.values.tolist()

x=np.reshape(x, (637))
y=np.reshape(y, (637))

In [4]:
yb1_1=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20110708.csv')
yb1_1.rename(columns = {'2011070805' : 'variable'}, inplace = True)
#좌표 변환 함수#
def abc(a, b, c):
    k= (int(a) +149*(int(b)-1)-1 ) + (37697*c)
    return k

#변환한 행,리스트들 수집#
z = [0, 1, 4, 5, 9 , 14] # 8:강수량 # 6,7 -> PTY, SKY # 10: 최고기온 11: 최저기온 12:SKY2  13:적설량
t =[]
for n in z:
    for i, j in zip(x, y):
        t.append(abc(i, j, n))
        
#수집한 행의 리스트 행 추출#
def ac1_1(a):
    k = yb1_1.iloc[a:a+1,:]
    return k

##
u = []
for i in t:
    u.append(ac1_1(i))
    
    
##
u=np.reshape(u, (3822,19))

##
col1_name1 = yb1_1.columns

##
yb1__1 = pd.DataFrame(u, columns=col1_name1)

##
p=[]
for i in range(6):
        a = yb1__1.iloc[0+637*i:637+637*i,:]
        p.append(a)
    

    
##
pp=[]
for i in range(6):
    a=p[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp.append(df)
    

##
pp[5]=pp[5].loc[pp[5].variable == 'WAV'].replace(-1.0, 0)


ppp=pd.concat(pp[0:5])
YB1_1=pd.concat([ppp, pp[5]])

In [5]:
yb1_2=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20110807.csv')
yb1_2.rename(columns = {'2011080705' : 'variable'}, inplace = True)
t2 =[]
for n in z:
    for i, j in zip(x, y):
        t2.append(abc(i, j, n))
        
def ac1_2(a):
    k = yb1_2.iloc[a:a+1,:]
    return k

u2 = []
for i in t2:
    u2.append(ac1_2(i))
    
u2=np.reshape(u2, (3822,19))

col1_name2 = yb1_2.columns

yb1__2 = pd.DataFrame(u2, columns=col1_name2)

p2=[]
for i in range(6):
    a2 = yb1__2.iloc[0+637*i:637+637*i,:]
    p2.append(a2)
    
pp2=[]
for i in range(6):
    a2=p2[i].reset_index(drop=True)
    df2= jido.join(a2, how='left')
    pp2.append(df2)
    

##    
pp2[5]=pp2[5].loc[pp2[5].variable == 'WAV'].replace(-1.0, 0)


ppp2=pd.concat(pp2[0:5])
YB1_2=pd.concat([ppp2, pp2[5]])

In [6]:
yb1_3=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20120916.csv')
yb1_3.rename(columns = {'2012091605' : 'variable'}, inplace = True)
t3 =[]
for n in z:
    for i, j in zip(x, y):
        t3.append(abc(i, j, n))
        
def ac1_3(a):
    k = yb1_3.iloc[a:a+1,:]
    return k

u3 = []
for i in t3:
    u3.append(ac1_3(i))
    
u3=np.reshape(u3, (3822,19))

col1_name3 = yb1_3.columns

yb1__3 = pd.DataFrame(u3, columns=col1_name3)

p3=[]
for i in range(6):
    a3 = yb1__3.iloc[0+637*i:637+637*i,:]
    p3.append(a3)
    
pp3=[]
for i in range(6):
    a3=p3[i].reset_index(drop=True)
    df3= jido.join(a3, how='left')
    pp3.append(df3)
    
##    
pp3[5]=pp3[5].loc[pp3[5].variable == 'WAV'].replace(-1.0, 0)


ppp3=pd.concat(pp3[0:5])
YB1_3=pd.concat([ppp3, pp3[5]])

In [7]:
yb1_4=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20140824.csv')
yb1_4.rename(columns = {'2014082405' : 'variable'}, inplace = True)
t4 =[]
for n in z:
    for i, j in zip(x, y):
        t4.append(abc(i, j, n))
        
def ac1_4(a):
    k = yb1_4.iloc[a:a+1,:]
    return k

u4 = []
for i in t4:
    u4.append(ac1_4(i))
    
u4=np.reshape(u4, (3822,23))

col1_name4 = yb1_4.columns

yb1__4 = pd.DataFrame(u4, columns=col1_name4)

p4=[]
for i in range(6):
    a4 = yb1__4.iloc[0+637*i:637+637*i,:]
    p4.append(a4)
    
pp4=[]
for i in range(6):
    a4=p4[i].reset_index(drop=True)
    df4= jido.join(a4, how='left')
    pp4.append(df4)
    
##    
pp4[5]=pp4[5].loc[pp4[5].variable == 'WAV'].replace(-1.0, 0)


ppp4=pd.concat(pp4[0:5])
YB1_4=pd.concat([ppp4, pp4[5]])

In [8]:
yb1_5=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20161004.csv')
yb1_5.rename(columns = {'2016100405' : 'variable'}, inplace = True)
t5 =[]
for n in z:
    for i, j in zip(x, y):
        t5.append(abc(i, j, n))
        
def ac1_5(a):
    k = yb1_5.iloc[a:a+1,:]
    return k

u5 = []
for i in t5:
    u5.append(ac1_5(i))
    
u5=np.reshape(u5, (3822,23))

col1_name5 = yb1_5.columns

yb1__5 = pd.DataFrame(u5, columns=col1_name5)

p5=[]
for i in range(6):
    a5 = yb1__5.iloc[0+637*i:637+637*i,:]
    p5.append(a5)
    
pp5=[]
for i in range(6):
    a5=p5[i].reset_index(drop=True)
    df5= jido.join(a5, how='left')
    pp5.append(df5)
        
##    
pp5[5]=pp5[5].loc[pp5[5].variable == 'WAV'].replace(-1.0, 0)


ppp5=pd.concat(pp5[0:5])
YB1_5=pd.concat([ppp5, pp5[5]])

In [9]:
yb1_6=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20180702.csv')
yb1_6.rename(columns = {'2018070205' : 'variable'}, inplace = True)
t6 =[]
for n in z:
    for i, j in zip(x, y):
        t6.append(abc(i, j, n))
        
def ac1_6(a):
    k = yb1_6.iloc[a:a+1,:]
    return k

u6 = []
for i in t6:
    u6.append(ac1_6(i))
    
u6=np.reshape(u6, (3822,23))

col1_name6 = yb1_6.columns

yb1__6 = pd.DataFrame(u6, columns=col1_name6)

p6=[]
for i in range(6):
    a6 = yb1__6.iloc[0+637*i:637+637*i,:]
    p6.append(a6)
    
pp6=[]
for i in range(6):
    a6=p6[i].reset_index(drop=True)
    df6= jido.join(a6, how='left')
    pp6.append(df6)
    
    
##    
pp6[5]=pp6[5].loc[pp6[5].variable == 'WAV'].replace(-1.0, 0)


ppp6=pd.concat(pp6[0:5])
YB1_6=pd.concat([ppp6, pp6[5]])

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [10]:
yb1_7=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20180825.csv')
yb1_7.rename(columns = {'2018082505' : 'variable'}, inplace = True)
t7 =[]
for n in z:
    for i, j in zip(x, y):
        t7.append(abc(i, j, n))
        
def ac1_7(a):
    k = yb1_7.iloc[a:a+1,:]
    return k

u7 = []
for i in t7:
    u7.append(ac1_7(i))
    
u7=np.reshape(u7, (3822,23))

col1_name7 = yb1_7.columns

yb1__7 = pd.DataFrame(u7, columns=col1_name7)

p7=[]
for i in range(6):
    a7 = yb1__7.iloc[0+637*i:637+637*i,:]
    p7.append(a7)
    
pp7=[]
for i in range(6):
    a7=p7[i].reset_index(drop=True)
    df7= jido.join(a7, how='left')
    pp7.append(df7)

##    
pp7[5]=pp7[5].loc[pp7[5].variable == 'WAV'].replace(-1.0, 0)


ppp7=pd.concat(pp7[0:5])
YB1_7=pd.concat([ppp7, pp7[5]])

In [11]:
yb1_8=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20181005.csv')
yb1_8.rename(columns = {'2018100505' : 'variable'}, inplace = True)
t8 =[]
for n in z:
    for i, j in zip(x, y):
        t8.append(abc(i, j, n))
        
def ac1_8(a):
    k = yb1_8.iloc[a:a+1,:]
    return k

u8 = []
for i in t8:
    u8.append(ac1_8(i))
    
u8=np.reshape(u8, (3822,23))

col1_name8 = yb1_8.columns

yb1__8 = pd.DataFrame(u8, columns=col1_name8)

p8=[]
for i in range(6):
    a8 = yb1__8.iloc[0+637*i:637+637*i,:]
    p8.append(a8)
    
pp8=[]
for i in range(6):
    a8=p8[i].reset_index(drop=True)
    df8= jido.join(a8, how='left')
    pp8.append(df8)
    
##    
pp8[5]=pp8[5].loc[pp8[5].variable == 'WAV'].replace(-1.0, 0)


ppp8=pd.concat(pp8[0:5])
YB1_8=pd.concat([ppp8, pp8[5]])

In [12]:
yb1_9=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20190719.csv')
yb1_9.rename(columns = {'2019071905' : 'variable'}, inplace = True)
t9 =[]
for n in z:
    for i, j in zip(x, y):
        t9.append(abc(i, j, n))
        
def ac1_9(a):
    k = yb1_9.iloc[a:a+1,:]
    return k

u9 = []
for i in t9:
    u9.append(ac1_9(i))
    
u9=np.reshape(u9, (3822,23))

col1_name9 = yb1_9.columns

yb1__9 = pd.DataFrame(u9, columns=col1_name9)

p9=[]
for i in range(6):
    a9 = yb1__9.iloc[0+637*i:637+637*i,:]
    p9.append(a9)
    
pp9=[]
for i in range(6):
    a9=p9[i].reset_index(drop=True)
    df9= jido.join(a9, how='left')
    pp9.append(df9)
    
##    
pp9[5]=pp9[5].loc[pp9[5].variable == 'WAV'].replace(-1.0, 0)


ppp9=pd.concat(pp9[0:5])
YB1_9=pd.concat([ppp9, pp9[5]])

In [13]:
yb1_10=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20191001.csv')
yb1_10.rename(columns = {'2019100105' : 'variable'}, inplace = True)
t10 =[]
for n in z:
    for i, j in zip(x, y):
        t10.append(abc(i, j, n))
        
def ac1_10(a):
    k = yb1_10.iloc[a:a+1,:]
    return k

u10 = []
for i in t10:
    u10.append(ac1_10(i))
    
u10=np.reshape(u10, (3822,23))

col1_name10 = yb1_10.columns

yb1__10 = pd.DataFrame(u10, columns=col1_name10)

p10=[]
for i in range(6):
    a10 = yb1__10.iloc[0+637*i:637+637*i,:]
    p10.append(a10)
    
pp10=[]
for i in range(6):
    a10=p10[i].reset_index(drop=True)
    df10= jido.join(a10, how='left')
    pp10.append(df10)
    

##    
pp10[5]=pp10[5].loc[pp10[5].variable == 'WAV'].replace(-1.0, 0)


ppp10=pd.concat(pp10[0:5])
YB1_10=pd.concat([ppp10, pp10[5]])

In [14]:
yb1_11=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20191002.csv')
yb1_11.rename(columns = {'2019100205' : 'variable'}, inplace = True)
t11 =[]
for n in z:
    for i, j in zip(x, y):
        t11.append(abc(i, j, n))
        
def ac1_11(a):
    k = yb1_11.iloc[a:a+1,:]
    return k

u11 = []
for i in t11:
    u11.append(ac1_11(i))
    
u11=np.reshape(u11, (3822,23))

col1_name11 = yb1_11.columns

yb1__11 = pd.DataFrame(u11, columns=col1_name11)

p11=[]
for i in range(6):
    a11 = yb1__11.iloc[0+637*i:637+637*i,:]
    p11.append(a11)
    
pp11=[]
for i in range(6):
    a11=p11[i].reset_index(drop=True)
    df11= jido.join(a11, how='left')
    pp11.append(df11)
    
##    
pp11[5]=pp11[5].loc[pp11[5].variable == 'WAV'].replace(-1.0, 0)


ppp11=pd.concat(pp11[0:5])
YB1_11=pd.concat([ppp11, pp11[5]])

In [15]:
#YB1_1['date'] = 20110709
YB1_1['1day_mean'] = (YB1_1['4hr']  + YB1_1['7hr']  + YB1_1['10hr']+YB1_1['13hr']  + YB1_1['16hr'] + YB1_1['19hr']  ) / 6
YB1_1['1day_min'] = YB1_1.iloc[:, 6:12].min(axis=1)
YB1_1['1day_max'] = YB1_1.iloc[:, 6:12].max(axis=1)
YB1_1['day_mean'] = (YB1_1['22hr']  + YB1_1['25hr']  + YB1_1['28hr']  + YB1_1['31hr']  + YB1_1['34hr']+ YB1_1['37hr']  + YB1_1['40hr']  + YB1_1['43hr']) /8
YB1_1['day_min'] = YB1_1.iloc[:, 12:20].min(axis=1)
YB1_1['day_max'] = YB1_1.iloc[:, 12:20].max(axis=1)

In [16]:
#YB1_2['date'] = 20110808
YB1_2['1day_mean'] = (YB1_2['4hr']  + YB1_2['7hr']  + YB1_2['10hr']+YB1_2['13hr']  + YB1_2['16hr'] + YB1_2['19hr']  ) / 6
YB1_2['1day_min'] = YB1_2.iloc[:, 6:12].min(axis=1)
YB1_2['1day_max'] = YB1_2.iloc[:, 6:12].max(axis=1)
YB1_2['day_mean'] = (YB1_2['22hr']  + YB1_2['25hr']  + YB1_2['28hr']  + YB1_2['31hr']  + YB1_2['34hr']+ YB1_2['37hr']  + YB1_2['40hr']  + YB1_2['43hr']) /8
YB1_2['day_min'] = YB1_2.iloc[:, 12:20].min(axis=1)
YB1_2['day_max'] = YB1_2.iloc[:, 12:20].max(axis=1)

In [17]:
#YB1_3['date'] = 20120917

YB1_3['1day_mean'] = (YB1_3['4hr']  + YB1_3['7hr']  + YB1_3['10hr']+YB1_3['13hr']  + YB1_3['16hr'] + YB1_3['19hr']  ) / 6
YB1_3['1day_min'] = YB1_3.iloc[:, 6:12].min(axis=1)
YB1_3['1day_max'] = YB1_3.iloc[:, 6:12].max(axis=1)
YB1_3['day_mean'] = (YB1_3['22hr']  + YB1_3['25hr']  + YB1_3['28hr']  + YB1_3['31hr']  + YB1_3['34hr']+ YB1_3['37hr']  + YB1_3['40hr']  + YB1_3['43hr']) /8
YB1_3['day_min'] = YB1_3.iloc[:, 12:20].min(axis=1)
YB1_3['day_max'] = YB1_3.iloc[:, 12:20].max(axis=1)

In [18]:
#YB1_4['date'] = 20140825
YB1_4['1day_mean'] = (YB1_4['4hr']  + YB1_4['7hr']  + YB1_4['10hr']+YB1_4['13hr']  + YB1_4['16hr'] + YB1_4['19hr']  ) / 6
YB1_4['1day_min'] = YB1_4.iloc[:, 6:12].min(axis=1)
YB1_4['1day_max'] = YB1_4.iloc[:, 6:12].max(axis=1)
YB1_4['day_mean'] = (YB1_4['22hr']  + YB1_4['25hr']  + YB1_4['28hr']  + YB1_4['31hr']  + YB1_4['34hr']+ YB1_4['37hr']  + YB1_4['40hr']  + YB1_4['43hr']) /8
YB1_4['day_min'] = YB1_4.iloc[:, 12:20].min(axis=1)
YB1_4['day_max'] = YB1_4.iloc[:, 12:20].max(axis=1)

In [19]:
#YB1_5['date'] = 20161005
YB1_5['1day_mean'] = (YB1_5['4hr']  + YB1_5['7hr']  + YB1_5['10hr']+YB1_5['13hr']  + YB1_5['16hr'] + YB1_5['19hr']  ) / 6
YB1_5['1day_min'] = YB1_5.iloc[:, 6:12].min(axis=1)
YB1_5['1day_max'] = YB1_5.iloc[:, 6:12].max(axis=1)
YB1_5['day_mean'] = (YB1_5['22hr']  + YB1_5['25hr']  + YB1_5['28hr']  + YB1_5['31hr']  + YB1_5['34hr']+ YB1_5['37hr']  + YB1_5['40hr']  + YB1_5['43hr']) /8
YB1_5['day_min'] = YB1_5.iloc[:, 12:20].min(axis=1)
YB1_5['day_max'] = YB1_5.iloc[:, 12:20].max(axis=1)

In [20]:
#YB1_6['date'] = 20180706
YB1_6['1day_mean'] = (YB1_6['4hr']  + YB1_6['7hr']  + YB1_6['10hr']+YB1_6['13hr']  + YB1_6['16hr'] + YB1_6['19hr']  ) / 6
YB1_6['1day_min'] = YB1_6.iloc[:, 6:12].min(axis=1)
YB1_6['1day_max'] = YB1_6.iloc[:, 6:12].max(axis=1)
YB1_6['day_mean'] = (YB1_6['22hr']  + YB1_6['25hr']  + YB1_6['28hr']  + YB1_6['31hr']  + YB1_6['34hr']+ YB1_6['37hr']  + YB1_6['40hr']  + YB1_6['43hr']) /8
YB1_6['day_min'] = YB1_6.iloc[:, 12:20].min(axis=1)
YB1_6['day_max'] = YB1_6.iloc[:, 12:20].max(axis=1)

In [21]:
#YB1_7['date'] = 20180828
YB1_7['1day_mean'] = (YB1_7['4hr']  + YB1_7['7hr']  + YB1_7['10hr']+YB1_7['13hr']  + YB1_7['16hr'] + YB1_7['19hr']  ) / 6
YB1_7['1day_min'] = YB1_7.iloc[:, 6:12].min(axis=1)
YB1_7['1day_max'] = YB1_7.iloc[:, 6:12].max(axis=1)
YB1_7['day_mean'] = (YB1_7['22hr']  + YB1_7['25hr']  + YB1_7['28hr']  + YB1_7['31hr']  + YB1_7['34hr']+ YB1_7['37hr']  + YB1_7['40hr']  + YB1_7['43hr']) /8
YB1_7['day_min'] = YB1_7.iloc[:, 12:20].min(axis=1)
YB1_7['day_max'] = YB1_7.iloc[:, 12:20].max(axis=1)

In [22]:
#YB1_8['date'] = 20181006
YB1_8['1day_mean'] = (YB1_8['4hr']  + YB1_8['7hr']  + YB1_8['10hr']+YB1_8['13hr']  + YB1_8['16hr'] + YB1_8['19hr']  ) / 6
YB1_8['1day_min'] = YB1_8.iloc[:, 6:12].min(axis=1)
YB1_8['1day_max'] = YB1_8.iloc[:, 6:12].max(axis=1)
YB1_8['day_mean'] = (YB1_8['22hr']  + YB1_8['25hr']  + YB1_8['28hr']  + YB1_8['31hr']  + YB1_8['34hr']+ YB1_8['37hr']  + YB1_8['40hr']  + YB1_8['43hr']) /8
YB1_8['day_min'] = YB1_8.iloc[:, 12:20].min(axis=1)
YB1_8['day_max'] = YB1_8.iloc[:, 12:20].max(axis=1)

In [23]:
#YB1_9['date'] = 20190702
YB1_9['1day_mean'] = (YB1_9['4hr']  + YB1_9['7hr']  + YB1_9['10hr']+YB1_9['13hr']  + YB1_9['16hr'] + YB1_9['19hr']  ) / 6
YB1_9['1day_min'] = YB1_9.iloc[:, 6:12].min(axis=1)
YB1_9['1day_max'] = YB1_9.iloc[:, 6:12].max(axis=1)
YB1_9['day_mean'] = (YB1_9['22hr']  + YB1_9['25hr']  + YB1_9['28hr']  + YB1_9['31hr']  + YB1_9['34hr']+ YB1_9['37hr']  + YB1_9['40hr']  + YB1_9['43hr']) /8
YB1_9['day_min'] = YB1_9.iloc[:, 12:20].min(axis=1)
YB1_9['day_max'] = YB1_9.iloc[:, 12:20].max(axis=1)

In [24]:
#YB1_10['date'] = 20191002
YB1_10['1day_mean'] = (YB1_10['4hr']  + YB1_10['7hr']  + YB1_10['10hr']+YB1_10['13hr']  + YB1_10['16hr'] + YB1_10['19hr']  ) / 6
YB1_10['1day_min'] = YB1_10.iloc[:, 6:12].min(axis=1)
YB1_10['1day_max'] = YB1_10.iloc[:, 6:12].max(axis=1)
YB1_10['day_mean'] = (YB1_10['22hr']  + YB1_10['25hr']  + YB1_10['28hr']  + YB1_10['31hr']  + YB1_10['34hr']+ YB1_10['37hr']  + YB1_10['40hr']  + YB1_10['43hr']) /8
YB1_10['day_min'] = YB1_10.iloc[:, 12:20].min(axis=1)
YB1_10['day_max'] = YB1_10.iloc[:, 12:20].max(axis=1)

In [25]:
#YB1_11['date'] = 20191001
YB1_11['1day_mean'] = (YB1_11['4hr']  + YB1_11['7hr']  + YB1_11['10hr']+YB1_11['13hr']  + YB1_11['16hr'] + YB1_11['19hr']  ) / 6
YB1_11['1day_min'] = YB1_11.iloc[:, 6:12].min(axis=1)
YB1_11['1day_max'] = YB1_11.iloc[:, 6:12].max(axis=1)
YB1_11['day_mean'] = (YB1_11['22hr']  + YB1_11['25hr']  + YB1_11['28hr']  + YB1_11['31hr']  + YB1_11['34hr']+ YB1_11['37hr']  + YB1_11['40hr']  + YB1_11['43hr']) /8
YB1_11['day_min'] = YB1_11.iloc[:, 12:20].min(axis=1)
YB1_11['day_max'] = YB1_11.iloc[:, 12:20].max(axis=1)

In [26]:
SYB1_11=YB1_11.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1_10=YB1_10.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1_9=YB1_9.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1_8=YB1_8.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1_7=YB1_7.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1_6=YB1_6.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1_5=YB1_5.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1_4=YB1_4.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1_3=YB1_3.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr'],axis=1)
SYB1_2=YB1_2.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr'],axis=1)
SYB1_1=YB1_1.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr'],axis=1)

In [27]:
def cba1(a):
    k = SYB1_1.iloc[0+637*a:637+637*a,:]
    return k

uu = []
for i in range(6):
    uu.append(cba1(i))

In [28]:
RD1_1=pd.merge(uu[0], uu[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_1.rename(columns = {'1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD1_1.rename(columns = {'1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD1_1=pd.merge(RD1_1, uu[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_1=pd.merge(RD1_1, uu[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_1.rename(columns = {'1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD1_1.rename(columns = {'1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD1_1=pd.merge(RD1_1, uu[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_1=pd.merge(RD1_1, uu[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_1.rename(columns = {'1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD1_1.rename(columns = {'1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA1_1= RD1_1.drop(['variable_x','variable_y'] , axis=1)
RDA1_1['date']=20110709

<ipython-input-28-4b5e85c83344>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA1_1['date']=20110709

In [29]:
def cba2(a):
    k = SYB1_2.iloc[0+637*a:637+637*a,:]
    return k

uu2 = []
for i in range(6):
    uu2.append(cba2(i))



RD1_2=pd.merge(uu2[0], uu2[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_2.rename(columns = {'1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD1_2.rename(columns = {'1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD1_2=pd.merge(RD1_2, uu2[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_2=pd.merge(RD1_2, uu2[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_2.rename(columns = {'1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD1_2.rename(columns = {'1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD1_2=pd.merge(RD1_2, uu2[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_2=pd.merge(RD1_2, uu2[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_2.rename(columns = {'1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD1_2.rename(columns = {'1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA1_2= RD1_2.drop(['variable_x','variable_y'] , axis=1)
RDA1_2['date']=20110808

<ipython-input-29-0c06afa2480f>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA1_2['date']=20110808

In [30]:
def cba3(a):
    k = SYB1_3.iloc[0+637*a:637+637*a,:]
    return k

uu3 = []
for i in range(6):
    uu3.append(cba3(i))



RD1_3=pd.merge(uu3[0], uu3[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_3.rename(columns = {'1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD1_3.rename(columns = {'1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD1_3=pd.merge(RD1_3, uu3[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_3=pd.merge(RD1_3, uu3[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_3.rename(columns = {'1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD1_3.rename(columns = {'1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD1_3=pd.merge(RD1_3, uu3[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_3=pd.merge(RD1_3, uu3[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_3.rename(columns = {'1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD1_3.rename(columns = {'1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA1_3= RD1_3.drop(['variable_x','variable_y'] , axis=1)
RDA1_3['date']=20120917

<ipython-input-30-e74841e68931>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA1_3['date']=20120917

In [31]:
def cba4(a):
    k = SYB1_4.iloc[0+637*a:637+637*a,:]
    return k

uu4 = []
for i in range(6):
    uu4.append(cba4(i))



RD1_4=pd.merge(uu4[0], uu4[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_4.rename(columns = {'1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD1_4.rename(columns = {'1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD1_4=pd.merge(RD1_4, uu4[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_4=pd.merge(RD1_4, uu4[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_4.rename(columns = {'1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD1_4.rename(columns = {'1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD1_4=pd.merge(RD1_4, uu4[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_4=pd.merge(RD1_4, uu4[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_4.rename(columns = {'1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD1_4.rename(columns = {'1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA1_4= RD1_4.drop(['variable_x','variable_y'] , axis=1)
RDA1_4['date']=20140825

<ipython-input-31-f9d47266534d>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA1_4['date']=20140825

In [32]:
def cba5(a):
    k = SYB1_5.iloc[0+637*a:637+637*a,:]
    return k

uu5 = []
for i in range(6):
    uu5.append(cba5(i))



RD1_5=pd.merge(uu5[0], uu5[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_5.rename(columns = {'1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD1_5.rename(columns = {'1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD1_5=pd.merge(RD1_5, uu5[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_5=pd.merge(RD1_5, uu5[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_5.rename(columns = {'1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD1_5.rename(columns = {'1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD1_5=pd.merge(RD1_5, uu5[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_5=pd.merge(RD1_5, uu5[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_5.rename(columns = {'1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD1_5.rename(columns = {'1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA1_5= RD1_5.drop(['variable_x','variable_y'] , axis=1)
RDA1_5['date']=20161005

<ipython-input-32-b334cd46a457>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA1_5['date']=20161005

In [33]:
def cba6(a):
    k = SYB1_6.iloc[0+637*a:637+637*a,:]
    return k

uu6 = []
for i in range(6):
    uu6.append(cba6(i))



RD1_6=pd.merge(uu6[0], uu6[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_6.rename(columns = {'1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD1_6.rename(columns = {'1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD1_6=pd.merge(RD1_6, uu6[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_6=pd.merge(RD1_6, uu6[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_6.rename(columns = {'1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD1_6.rename(columns = {'1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD1_6=pd.merge(RD1_6, uu6[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_6=pd.merge(RD1_6, uu6[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_6.rename(columns = {'1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD1_6.rename(columns = {'1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA1_6= RD1_6.drop(['variable_x','variable_y'] , axis=1)
RDA1_6['date']=20180703

<ipython-input-33-10a5d8129e15>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA1_6['date']=20180703

In [34]:
def cba7(a):
    k = SYB1_7.iloc[0+637*a:637+637*a,:]
    return k

uu7 = []
for i in range(6):
    uu7.append(cba7(i))



RD1_7=pd.merge(uu7[0], uu7[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_7.rename(columns = {'1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD1_7.rename(columns = {'1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD1_7=pd.merge(RD1_7, uu7[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_7=pd.merge(RD1_7, uu7[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_7.rename(columns = {'1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD1_7.rename(columns = {'1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD1_7=pd.merge(RD1_7, uu7[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_7=pd.merge(RD1_7, uu7[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_7.rename(columns = {'1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD1_7.rename(columns = {'1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA1_7= RD1_7.drop(['variable_x','variable_y'] , axis=1)
RDA1_7['date']=20180826

<ipython-input-34-165481e3d2ba>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA1_7['date']=20180826

In [35]:
def cba8(a):
    k = SYB1_8.iloc[0+637*a:637+637*a,:]
    return k

uu8 = []
for i in range(6):
    uu8.append(cba8(i))



RD1_8=pd.merge(uu8[0], uu8[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_8.rename(columns = {'1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD1_8.rename(columns = {'1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD1_8=pd.merge(RD1_8, uu8[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_8=pd.merge(RD1_8, uu8[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_8.rename(columns = {'1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD1_8.rename(columns = {'1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD1_8=pd.merge(RD1_8, uu8[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_8=pd.merge(RD1_8, uu8[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_8.rename(columns = {'1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD1_8.rename(columns = {'1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA1_8= RD1_8.drop(['variable_x','variable_y'] , axis=1)
RDA1_8['date']=20181006

<ipython-input-35-509079bc7c5d>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA1_8['date']=20181006

In [36]:
def cba9(a):
    k = SYB1_9.iloc[0+637*a:637+637*a,:]
    return k

uu9 = []
for i in range(6):
    uu9.append(cba9(i))



RD1_9=pd.merge(uu9[0], uu9[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_9.rename(columns = {'1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD1_9.rename(columns = {'1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD1_9=pd.merge(RD1_9, uu9[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_9=pd.merge(RD1_9, uu9[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_9.rename(columns = {'1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD1_9.rename(columns = {'1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD1_9=pd.merge(RD1_9, uu9[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_9=pd.merge(RD1_9, uu9[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_9.rename(columns = {'1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD1_9.rename(columns = {'1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA1_9= RD1_9.drop(['variable_x','variable_y'] , axis=1)
RDA1_9['date']=20190720

<ipython-input-36-92f71942ae1a>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA1_9['date']=20190720

In [37]:
def cba10(a):
    k = SYB1_10.iloc[0+637*a:637+637*a,:]
    return k

uu10 = []
for i in range(6):
    uu10.append(cba10(i))



RD1_10=pd.merge(uu10[0], uu10[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_10.rename(columns = {'1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD1_10.rename(columns = {'1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD1_10=pd.merge(RD1_10, uu10[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_10=pd.merge(RD1_10, uu10[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_10.rename(columns = {'1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD1_10.rename(columns = {'1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD1_10=pd.merge(RD1_10, uu10[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_10=pd.merge(RD1_10, uu10[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_10.rename(columns = {'1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD1_10.rename(columns = {'1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA1_10= RD1_10.drop(['variable_x','variable_y'] , axis=1)
RDA1_10['date']=20191002

<ipython-input-37-0777f8bafae5>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA1_10['date']=20191002

In [38]:
def cba11(a):
    k = SYB1_11.iloc[0+637*a:637+637*a,:]
    return k

uu11 = []
for i in range(6):
    uu11.append(cba11(i))



RD1_11=pd.merge(uu11[0], uu11[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_11.rename(columns = {'1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD1_11.rename(columns = {'1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD1_11=pd.merge(RD1_11, uu11[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_11=pd.merge(RD1_11, uu11[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_11.rename(columns = {'1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD1_11.rename(columns = {'1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD1_11=pd.merge(RD1_11, uu11[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_11=pd.merge(RD1_11, uu11[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1_11.rename(columns = {'1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD1_11.rename(columns = {'1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA1_11= RD1_11.drop(['variable_x','variable_y'] , axis=1)
RDA1_11['date']=20191003

<ipython-input-38-85ffb5b7985c>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA1_11['date']=20191003

In [39]:
RRDDAA=pd.concat([RDA1_11,RDA1_10,RDA1_9,RDA1_8,RDA1_7,RDA1_6,RDA1_5,RDA1_4,RDA1_3,RDA1_2,RDA1_1])

In [40]:
RRDDAA

,sd,sgg,umd,x,y,1day_mean_T3H,1day_min_T3H,1day_max_T3H,day_mean_T3H,day_min_T3H,...,day_mean_POP,day_min_POP,day_max_POP,1day_mean_WAV,1day_min_WAV,1day_max_WAV,day_mean_WAV,day_min_WAV,day_max_WAV,date
0,경상북도,포항시남구,구룡포읍,105,94,22.833333,22.0,25.0,23.875,19.0,...,80.0,30.0,90.0,0.833333,0.5,1.5,1.75,1.0,2.5,20191003
1,경상북도,포항시남구,연일읍,102,94,23.166667,22.0,25.0,24.375,20.0,...,78.75,30.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0,20191003
2,경상북도,포항시남구,오천읍,103,93,23.0,22.0,25.0,25.0,22.0,...,78.75,30.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0,20191003
3,경상북도,포항시남구,대송면,102,93,23.0,22.0,25.0,24.375,20.0,...,78.75,30.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0,20191003
4,경상북도,포항시남구,동해면2,104,94,23.333333,22.0,25.0,24.875,21.0,...,80.0,30.0,90.0,0.583333,0.5,1.0,0.875,0.5,1.5,20191003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,경상남도,합천군,쌍백면,81,81,26.6,24.9,28.0,25.15,23.8,...,60.375,30.0,71.0,0.0,0.0,0.0,0.0,0.0,0.0,20110709
633,경상남도,합천군,삼가면,81,80,26.666667,25.0,28.0,25.25,24.0,...,60.0,30.0,70.0,0.0,0.0,0.0,0.0,0.0,0.0,20110709
634,경상남도,합천군,가회면,79,81,26.216667,24.8,27.5,24.8,23.5,...,60.75,25.0,74.0,0.0,0.0,0.0,0.0,0.0,0.0,20110709
635,경상남도,합천군,대병면,79,83,25.55,24.1,27.0,24.05,22.8,...,60.0,23.0,72.0,0.0,0.0,0.0,0.0,0.0,0.0,20110709
636,경상남도,합천군,용주면,81,83,26.9,25.2,28.3,25.425,24.1,...,60.0,28.0,71.0,0.0,0.0,0.0,0.0,0.0,0.0,20110709

## 범주형자료

In [41]:
z_1 = [6,7] # 8:강수량 # 6,7 -> PTY, SKY # 10: 최고기온 11: 최저기온 12:SKY2  13:적설량
t_1 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_1.append(abc(i, j, n))

u_1 = []
for i in t_1:
    u_1.append(ac1_1(i))
    
u_1=np.reshape(u_1, (1274,19))

col1_name1 = yb1_1.columns

ybs1_1 = pd.DataFrame(u_1, columns=col1_name1)

p_1=[]
for i in range(2):
    a = ybs1_1.iloc[0+637*i:637+637*i,:]
    p_1.append(a)
    
pp_1=[]
for i in range(2):
    a=p_1[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_1.append(df)

YB1__1=pd.concat(pp_1)
YB1__1.rename(columns = {'2011070805' : 'variable'}, inplace = True)

In [42]:
t_2 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_2.append(abc(i, j, n))

u_2 = []
for i in t_2:
    u_2.append(ac1_2(i))

u_2=np.reshape(u_2, (1274,19))

col1_name2 = yb1_2.columns

ybs1_2 = pd.DataFrame(u_2, columns=col1_name2)

p_2=[]
for i in range(2):
    a = ybs1_2.iloc[0+637*i:637+637*i,:]
    p_2.append(a)
    
pp_2=[]
for i in range(2):
    a=p_2[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_2.append(df)

YB1__2=pd.concat(pp_2)
YB1__2.rename(columns = {'2011080705' : 'variable'}, inplace = True)

In [43]:
t_3 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_3.append(abc(i, j, n))

u_3 = []
for i in t_3:
    u_3.append(ac1_3(i))

u_3=np.reshape(u_3, (1274,19))

col1_name3 = yb1_3.columns

ybs1_3 = pd.DataFrame(u_3, columns=col1_name3)

p_3=[]
for i in range(2):
    a = ybs1_3.iloc[0+637*i:637+637*i,:]
    p_3.append(a)
    
pp_3=[]
for i in range(2):
    a=p_3[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_3.append(df)

YB1__3=pd.concat(pp_3)
YB1__3.rename(columns = {'2012091605' : 'variable'}, inplace = True)

In [44]:
t_4 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_4.append(abc(i, j, n))

u_4 = []
for i in t_4:
    u_4.append(ac1_4(i))

u_4=np.reshape(u_4, (1274,23))

col1_name4 = yb1_4.columns

ybs1_4 = pd.DataFrame(u_4, columns=col1_name4)

p_4=[]
for i in range(2):
    a = ybs1_4.iloc[0+637*i:637+637*i,:]
    p_4.append(a)
    
pp_4=[]
for i in range(2):
    a=p_4[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_4.append(df)

YB1__4=pd.concat(pp_4)
YB1__4.rename(columns = {'2014082405' : 'variable'}, inplace = True)

In [45]:
t_5 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_5.append(abc(i, j, n))

u_5 = []
for i in t_5:
    u_5.append(ac1_5(i))

u_5=np.reshape(u_5, (1274,23))

col1_name5 = yb1_5.columns

ybs1_5 = pd.DataFrame(u_5, columns=col1_name5)

p_5=[]
for i in range(2):
    a = ybs1_5.iloc[0+637*i:637+637*i,:]
    p_5.append(a)
    
pp_5=[]
for i in range(2):
    a=p_5[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_5.append(df)

YB1__5=pd.concat(pp_5)
YB1__5.rename(columns = {'2016100405' : 'variable'}, inplace = True)

In [46]:
t_6 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_6.append(abc(i, j, n))

u_6 = []
for i in t_6:
    u_6.append(ac1_6(i))

u_6=np.reshape(u_6, (1274,23))

col1_name6 = yb1_6.columns

ybs1_6 = pd.DataFrame(u_6, columns=col1_name6)

p_6=[]
for i in range(2):
    a = ybs1_6.iloc[0+637*i:637+637*i,:]
    p_6.append(a)
    
pp_6=[]
for i in range(2):
    a=p_6[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_6.append(df)

YB1__6=pd.concat(pp_6)
YB1__6.rename(columns = {'2018070205' : 'variable'}, inplace = True)

In [47]:
t_7 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_7.append(abc(i, j, n))

u_7 = []
for i in t_7:
    u_7.append(ac1_7(i))

u_7=np.reshape(u_7, (1274,23))

col1_name7 = yb1_7.columns

ybs1_7 = pd.DataFrame(u_7, columns=col1_name7)

p_7=[]
for i in range(2):
    a = ybs1_7.iloc[0+637*i:637+637*i,:]
    p_7.append(a)
    
pp_7=[]
for i in range(2):
    a=p_7[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_7.append(df)

YB1__7=pd.concat(pp_7)
YB1__7.rename(columns = {'2018082505' : 'variable'}, inplace = True)

In [48]:
t_8 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_8.append(abc(i, j, n))

u_8 = []
for i in t_8:
    u_8.append(ac1_8(i))

u_8=np.reshape(u_8, (1274,23))

col1_name8 = yb1_8.columns

ybs1_8 = pd.DataFrame(u_8, columns=col1_name8)

p_8=[]
for i in range(2):
    a = ybs1_8.iloc[0+637*i:637+637*i,:]
    p_8.append(a)
    
pp_8=[]
for i in range(2):
    a=p_8[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_8.append(df)

YB1__8=pd.concat(pp_8)
YB1__8.rename(columns = {'2018100505' : 'variable'}, inplace = True)

In [49]:
t_9 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_9.append(abc(i, j, n))

u_9 = []
for i in t_9:
    u_9.append(ac1_9(i))

u_9=np.reshape(u_9, (1274,23))

col1_name9 = yb1_9.columns

ybs1_9 = pd.DataFrame(u_9, columns=col1_name9)

p_9=[]
for i in range(2):
    a = ybs1_9.iloc[0+637*i:637+637*i,:]
    p_9.append(a)
    
pp_9=[]
for i in range(2):
    a=p_9[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_9.append(df)

YB1__9=pd.concat(pp_9)
YB1__9.rename(columns = {'2019071905' : 'variable'}, inplace = True)

In [50]:
t_10 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_10.append(abc(i, j, n))

u_10 = []
for i in t_10:
    u_10.append(ac1_10(i))

u_10=np.reshape(u_10, (1274,23))

col1_name10 = yb1_10.columns

ybs1_10 = pd.DataFrame(u_10, columns=col1_name10)

p_10=[]
for i in range(2):
    a = ybs1_10.iloc[0+637*i:637+637*i,:]
    p_10.append(a)
    
pp_10=[]
for i in range(2):
    a=p_10[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_10.append(df)

YB1__10=pd.concat(pp_10)
YB1__10.rename(columns = {'2019100105' : 'variable'}, inplace = True)

In [51]:
t_11 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_11.append(abc(i, j, n))

u_11 = []
for i in t_11:
    u_11.append(ac1_11(i))

u_11=np.reshape(u_11, (1274,23))

col1_name11 = yb1_11.columns

ybs1_11 = pd.DataFrame(u_11, columns=col1_name11)

p_11=[]
for i in range(2):
    a = ybs1_11.iloc[0+637*i:637+637*i,:]
    p_11.append(a)
    
pp_11=[]
for i in range(2):
    a=p_11[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_11.append(df)

YB1__11=pd.concat(pp_11)
YB1__11.rename(columns = {'2019100205' : 'variable'}, inplace = True)

In [52]:
from scipy.stats import mode

YB1__1['1day_mode'] = YB1__1.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB1__1['day_mode'] = YB1__1.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

In [53]:
YB1__2['1day_mode'] = YB1__2.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB1__2['day_mode'] = YB1__2.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

In [54]:
YB1__3['1day_mode'] = YB1__3.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB1__3['day_mode'] = YB1__3.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

In [55]:
YB1__4['1day_mode'] = YB1__4.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB1__4['day_mode'] = YB1__4.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

In [56]:
YB1__5['1day_mode'] = YB1__5.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB1__5['day_mode'] = YB1__5.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

In [57]:
YB1__6['1day_mode'] = YB1__6.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB1__6['day_mode'] = YB1__6.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

In [58]:
YB1__7['1day_mode'] = YB1__7.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB1__7['day_mode'] = YB1__7.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

In [59]:
YB1__8['1day_mode'] = YB1__8.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB1__8['day_mode'] = YB1__8.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

In [60]:
YB1__9['1day_mode'] = YB1__9.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB1__9['day_mode'] = YB1__9.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

In [61]:
YB1__10['1day_mode'] = YB1__10.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB1__10['day_mode'] = YB1__10.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

In [62]:
YB1__11['1day_mode'] = YB1__11.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB1__11['day_mode'] = YB1__11.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

In [63]:
SYB1__11=YB1__11.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1__10=YB1__10.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1__9=YB1__9.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1__8=YB1__8.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1__7=YB1__7.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1__6=YB1__6.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1__5=YB1__5.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1__4=YB1__4.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1__3=YB1__3.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr'],axis=1)
SYB1__2=YB1__2.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr'],axis=1)
SYB1__1=YB1__1.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr'],axis=1)

In [64]:
def cba_1(a):
    k = SYB1__1.iloc[0+637*a:637+637*a,:]
    return k

u_u = []
for i in range(2):
    u_u.append(cba_1(i))
    
RD1__1=pd.merge(u_u[0], u_u[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1__1.rename(columns = {'1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD1__1.rename(columns = {'1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA1__1= RD1__1.drop(['variable_x','variable_y'] , axis=1)
RDA1__1['date']=20110709

In [65]:
def cba_2(a):
    k = SYB1__2.iloc[0+637*a:637+637*a,:]
    return k

u_u2 = []
for i in range(2):
    u_u2.append(cba_2(i))
    
RD1__2=pd.merge(u_u2[0], u_u2[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1__2.rename(columns = {'1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD1__2.rename(columns = {'1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA1__2= RD1__2.drop(['variable_x','variable_y'] , axis=1)
RDA1__2['date']=20110808

In [66]:
def cba_3(a):
    k = SYB1__3.iloc[0+637*a:637+637*a,:]
    return k

u_u3 = []
for i in range(2):
    u_u3.append(cba_3(i))
    
RD1__3=pd.merge(u_u3[0], u_u3[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1__3.rename(columns = {'1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD1__3.rename(columns = {'1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA1__3= RD1__3.drop(['variable_x','variable_y'] , axis=1)
RDA1__3['date']=20120917

In [67]:
def cba_4(a):
    k = SYB1__4.iloc[0+637*a:637+637*a,:]
    return k

u_u4 = []
for i in range(2):
    u_u4.append(cba_4(i))
    
RD1__4=pd.merge(u_u4[0], u_u4[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1__4.rename(columns = {'1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD1__4.rename(columns = {'1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA1__4= RD1__4.drop(['variable_x','variable_y'] , axis=1)
RDA1__4['date']=20140825

In [68]:
def cba_5(a):
    k = SYB1__5.iloc[0+637*a:637+637*a,:]
    return k

u_u5 = []
for i in range(2):
    u_u5.append(cba_5(i))
    
RD1__5=pd.merge(u_u5[0], u_u5[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1__5.rename(columns = {'1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD1__5.rename(columns = {'1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA1__5= RD1__5.drop(['variable_x','variable_y'] , axis=1)
RDA1__5['date']=20161005

In [69]:
def cba_6(a):
    k = SYB1__6.iloc[0+637*a:637+637*a,:]
    return k

u_u6 = []
for i in range(2):
    u_u6.append(cba_6(i))
    
RD1__6=pd.merge(u_u6[0], u_u6[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1__6.rename(columns = {'1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD1__6.rename(columns = {'1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA1__6= RD1__6.drop(['variable_x','variable_y'] , axis=1)
RDA1__6['date']=20180703

In [70]:
def cba_7(a):
    k = SYB1__7.iloc[0+637*a:637+637*a,:]
    return k

u_u7 = []
for i in range(2):
    u_u7.append(cba_7(i))
    
RD1__7=pd.merge(u_u7[0], u_u7[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1__7.rename(columns = {'1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD1__7.rename(columns = {'1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA1__7= RD1__7.drop(['variable_x','variable_y'] , axis=1)
RDA1__7['date']=20180826

In [71]:
def cba_8(a):
    k = SYB1__8.iloc[0+637*a:637+637*a,:]
    return k

u_u8 = []
for i in range(2):
    u_u8.append(cba_8(i))
    
RD1__8=pd.merge(u_u8[0], u_u8[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1__8.rename(columns = {'1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD1__8.rename(columns = {'1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA1__8= RD1__8.drop(['variable_x','variable_y'] , axis=1)
RDA1__8['date']=20181006

In [72]:
def cba_9(a):
    k = SYB1__9.iloc[0+637*a:637+637*a,:]
    return k

u_u9 = []
for i in range(2):
    u_u9.append(cba_9(i))
    
RD1__9=pd.merge(u_u9[0], u_u9[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1__9.rename(columns = {'1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD1__9.rename(columns = {'1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA1__9= RD1__9.drop(['variable_x','variable_y'] , axis=1)
RDA1__9['date']=20190720

In [73]:
def cba_10(a):
    k = SYB1__10.iloc[0+637*a:637+637*a,:]
    return k

u_u10 = []
for i in range(2):
    u_u10.append(cba_10(i))
    
RD1__10=pd.merge(u_u10[0], u_u10[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1__10.rename(columns = {'1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD1__10.rename(columns = {'1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA1__10= RD1__10.drop(['variable_x','variable_y'] , axis=1)
RDA1__10['date']=20191002

In [74]:
def cba_11(a):
    k = SYB1__11.iloc[0+637*a:637+637*a,:]
    return k

u_u11 = []
for i in range(2):
    u_u11.append(cba_11(i))
    
RD1__11=pd.merge(u_u11[0], u_u11[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD1__11.rename(columns = {'1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD1__11.rename(columns = {'1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA1__11= RD1__11.drop(['variable_x','variable_y'] , axis=1)
RDA1__11['date']=20191003

In [75]:
RRDDAA_1=pd.concat([RDA1__11,RDA1__10,RDA1__9,RDA1__8,RDA1__7,RDA1__6,RDA1__5,RDA1__4,RDA1__3,RDA1__2,RDA1__1])

In [76]:
weather_1=pd.merge(RRDDAA, RRDDAA_1, on=['sd', 'sgg', 'umd', 'x', 'y', 'date'], how='inner')

In [77]:
weather_1

,sd,sgg,umd,x,y,1day_mean_T3H,1day_min_T3H,1day_max_T3H,day_mean_T3H,day_min_T3H,...,1day_min_WAV,1day_max_WAV,day_mean_WAV,day_min_WAV,day_max_WAV,date,1day_mode_PTY,day_mode_PTY,1day_mode_SKY,day_mode_SKY
0,경상북도,포항시남구,구룡포읍,105,94,22.833333,22.0,25.0,23.875,19.0,...,0.5,1.5,1.75,1.0,2.5,20191003,1.0,1.0,4.0,4.0
1,경상북도,포항시남구,연일읍,102,94,23.166667,22.0,25.0,24.375,20.0,...,0.0,0.0,0.0,0.0,0.0,20191003,1.0,1.0,4.0,4.0
2,경상북도,포항시남구,오천읍,103,93,23.0,22.0,25.0,25.0,22.0,...,0.0,0.0,0.0,0.0,0.0,20191003,1.0,1.0,4.0,4.0
3,경상북도,포항시남구,대송면,102,93,23.0,22.0,25.0,24.375,20.0,...,0.0,0.0,0.0,0.0,0.0,20191003,1.0,1.0,4.0,4.0
4,경상북도,포항시남구,동해면2,104,94,23.333333,22.0,25.0,24.875,21.0,...,0.5,1.0,0.875,0.5,1.5,20191003,1.0,1.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7002,경상남도,합천군,쌍백면,81,81,26.6,24.9,28.0,25.15,23.8,...,0.0,0.0,0.0,0.0,0.0,20110709,0.0,1.0,4.0,4.0
7003,경상남도,합천군,삼가면,81,80,26.666667,25.0,28.0,25.25,24.0,...,0.0,0.0,0.0,0.0,0.0,20110709,0.0,1.0,4.0,4.0
7004,경상남도,합천군,가회면,79,81,26.216667,24.8,27.5,24.8,23.5,...,0.0,0.0,0.0,0.0,0.0,20110709,0.0,1.0,4.0,4.0
7005,경상남도,합천군,대병면,79,83,25.55,24.1,27.0,24.05,22.8,...,0.0,0.0,0.0,0.0,0.0,20110709,0.0,1.0,4.0,4.0
7006,경상남도,합천군,용주면,81,83,26.9,25.2,28.3,25.425,24.1,...,0.0,0.0,0.0,0.0,0.0,20110709,0.0,1.0,4.0,4.0

## 강수량  이충렬

In [78]:
z__1 = [8] # 8:강수량 # 6,7 -> PTY, SKY # 10: 최고기온 11: 최저기온 12:SKY2  13:적설량
t__1 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__1.append(abc(i, j, n))

u__1 = []
for i in t__1:
    u__1.append(ac1_1(i))
    
u__1=np.reshape(u__1, (637,19))

col1_name1 = yb1_1.columns

ybs1_1 = pd.DataFrame(u__1, columns=col1_name1)

p__1=[]
for i in range(1):
    a = ybs1_1.iloc[0+637*i:637+637*i,:]
    p__1.append(a)
    
pp__1=[]
for i in range(1):
    a=p__1[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__1.append(df)

YB1___1=pd.concat(pp__1)
YB1___1.rename(columns = {'2011070805' : 'variable'}, inplace = True)

In [79]:
t__2 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__2.append(abc(i, j, n))

u__2 = []
for i in t__2:
    u__2.append(ac1_2(i))
    
u__2=np.reshape(u__2, (637,19))

col1_name2 = yb1_2.columns

ybs1_2 = pd.DataFrame(u__2, columns=col1_name2)

p__2=[]
for i in range(1):
    a = ybs1_2.iloc[0+637*i:637+637*i,:]
    p__2.append(a)
    
pp__2=[]
for i in range(1):
    a=p__2[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__2.append(df)

YB1___2=pd.concat(pp__1)
YB1___2.rename(columns = {'2011080705' : 'variable'}, inplace = True)

In [80]:
t__3 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__3.append(abc(i, j, n))

u__3 = []
for i in t__3:
    u__3.append(ac1_3(i))
    
u__3=np.reshape(u__3, (637,19))

col1_name3 = yb1_3.columns

ybs1_3 = pd.DataFrame(u__3, columns=col1_name3)

p__3=[]
for i in range(1):
    a = ybs1_3.iloc[0+637*i:637+637*i,:]
    p__3.append(a)
    
pp__3=[]
for i in range(1):
    a=p__3[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__3.append(df)

YB1___3=pd.concat(pp__3)
YB1___3.rename(columns = {'2012091605' : 'variable'}, inplace = True)

In [81]:
t__4 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__4.append(abc(i, j, n))

u__4 = []
for i in t__4:
    u__4.append(ac1_4(i))
    
u__4=np.reshape(u__4, (637,23))

col1_name4 = yb1_4.columns

ybs1_4 = pd.DataFrame(u__4, columns=col1_name4)

p__4=[]
for i in range(1):
    a = ybs1_4.iloc[0+637*i:637+637*i,:]
    p__4.append(a)
    
pp__4=[]
for i in range(1):
    a=p__4[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__4.append(df)

YB1___4=pd.concat(pp__4)
YB1___4.rename(columns = {'2014082405' : 'variable'}, inplace = True)

In [82]:
t__5 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__5.append(abc(i, j, n))

u__5 = []
for i in t__5:
    u__5.append(ac1_5(i))
    
u__5=np.reshape(u__5, (637,23))

col1_name5 = yb1_5.columns

ybs1_5 = pd.DataFrame(u__5, columns=col1_name5)

p__5=[]
for i in range(1):
    a = ybs1_5.iloc[0+637*i:637+637*i,:]
    p__5.append(a)
    
pp__5=[]
for i in range(1):
    a=p__5[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__5.append(df)

YB1___5=pd.concat(pp__5)
YB1___5.rename(columns = {'2016100405' : 'variable'}, inplace = True)

In [83]:
t__6 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__6.append(abc(i, j, n))

u__6 = []
for i in t__6:
    u__6.append(ac1_6(i))
    
u__6=np.reshape(u__6, (637,23))

col1_name6 = yb1_6.columns

ybs1_6 = pd.DataFrame(u__6, columns=col1_name6)

p__6=[]
for i in range(1):
    a = ybs1_6.iloc[0+637*i:637+637*i,:]
    p__6.append(a)
    
pp__6=[]
for i in range(1):
    a=p__6[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__6.append(df)

YB1___6=pd.concat(pp__6)
YB1___6.rename(columns = {'2018070205' : 'variable'}, inplace = True)

In [84]:
t__7 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__7.append(abc(i, j, n))

u__7 = []
for i in t__7:
    u__7.append(ac1_7(i))
    
u__7=np.reshape(u__7, (637,23))

col1_name7 = yb1_7.columns

ybs1_7 = pd.DataFrame(u__7, columns=col1_name7)

p__7=[]
for i in range(1):
    a = ybs1_7.iloc[0+637*i:637+637*i,:]
    p__7.append(a)
    
pp__7=[]
for i in range(1):
    a=p__7[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__7.append(df)

YB1___7=pd.concat(pp__7)
YB1___7.rename(columns = {'2018082505' : 'variable'}, inplace = True)

In [85]:
t__8 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__8.append(abc(i, j, n))

u__8 = []
for i in t__8:
    u__8.append(ac1_8(i))
    
u__8=np.reshape(u__8, (637,23))

col1_name8 = yb1_8.columns

ybs1_8 = pd.DataFrame(u__8, columns=col1_name8)

p__8=[]
for i in range(1):
    a = ybs1_8.iloc[0+637*i:637+637*i,:]
    p__8.append(a)
    
pp__8=[]
for i in range(1):
    a=p__8[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__8.append(df)

YB1___8=pd.concat(pp__8)
YB1___8.rename(columns = {'2018100505' : 'variable'}, inplace = True)

In [86]:
t__9 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__9.append(abc(i, j, n))

u__9 = []
for i in t__9:
    u__9.append(ac1_9(i))
    
u__9=np.reshape(u__9, (637,23))

col1_name9 = yb1_9.columns

ybs1_9 = pd.DataFrame(u__9, columns=col1_name9)

p__9=[]
for i in range(1):
    a = ybs1_9.iloc[0+637*i:637+637*i,:]
    p__9.append(a)
    
pp__9=[]
for i in range(1):
    a=p__9[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__9.append(df)

YB1___9=pd.concat(pp__9)
YB1___9.rename(columns = {'2019071905' : 'variable'}, inplace = True)

In [87]:
t__10 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__10.append(abc(i, j, n))

u__10 = []
for i in t__10:
    u__10.append(ac1_10(i))
    
u__10=np.reshape(u__10, (637,23))

col1_name10 = yb1_10.columns

ybs1_10 = pd.DataFrame(u__10, columns=col1_name10)

p__10=[]
for i in range(1):
    a = ybs1_10.iloc[0+637*i:637+637*i,:]
    p__10.append(a)
    
pp__10=[]
for i in range(1):
    a=p__10[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__10.append(df)

YB1___10=pd.concat(pp__10)
YB1___10.rename(columns = {'2019100105' : 'variable'}, inplace = True)

In [88]:
t__11 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__11.append(abc(i, j, n))

u__11 = []
for i in t__11:
    u__11.append(ac1_11(i))
    
u__11=np.reshape(u__11, (637,23))

col1_name11 = yb1_11.columns

ybs1_11 = pd.DataFrame(u__11, columns=col1_name11)

p__11=[]
for i in range(1):
    a = ybs1_11.iloc[0+637*i:637+637*i,:]
    p__11.append(a)
    
pp__11=[]
for i in range(1):
    a=p__11[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__11.append(df)

YB1___11=pd.concat(pp__11)
YB1___11.rename(columns = {'20191002505' : 'variable'}, inplace = True)

In [89]:
YB1___1['1day_sum_rain'] = (YB1___1['4hr']  +YB1___1['7hr']+ YB1___1['10hr']  + YB1___1['13hr'] ) 
YB1___1['1day_max_rain'] = YB1___1.iloc[:, 6:10].max(axis=1)
YB1___1['day_sum_rain'] = (YB1___1['16hr']  + YB1___1['19hr']+YB1___1['22hr']  + YB1___1['25hr']) 
YB1___1['day_max_rain'] = YB1___1.iloc[:, 10:14].max(axis=1)
YB1___1['date']= 20110709

In [90]:
YB1___2['1day_sum_rain'] = (YB1___2['4hr']  +YB1___2['7hr']+ YB1___2['10hr']  + YB1___2['13hr'] ) 
YB1___2['1day_max_rain'] = YB1___2.iloc[:, 6:10].max(axis=1)
YB1___2['day_sum_rain'] = (YB1___2['16hr']  + YB1___2['19hr']+YB1___2['22hr']  + YB1___2['25hr']) 
YB1___2['day_max_rain'] = YB1___2.iloc[:, 10:14].max(axis=1)
YB1___2['date']= 20110808

In [91]:
YB1___3['1day_sum_rain'] = (YB1___3['4hr']  +YB1___3['7hr']+ YB1___3['10hr']  + YB1___3['13hr'] ) 
YB1___3['1day_max_rain'] = YB1___3.iloc[:, 6:10].max(axis=1)
YB1___3['day_sum_rain'] = (YB1___3['16hr']  + YB1___3['19hr']+YB1___3['22hr']  + YB1___3['25hr']) 
YB1___3['day_max_rain'] = YB1___3.iloc[:, 10:14].max(axis=1)
YB1___3['date']= 20120917

In [92]:
YB1___4['1day_sum_rain'] = (YB1___4['4hr']  +YB1___4['7hr']+ YB1___4['10hr']  + YB1___4['13hr'] ) 
YB1___4['1day_max_rain'] = YB1___4.iloc[:, 6:10].max(axis=1)
YB1___4['day_sum_rain'] = (YB1___4['16hr']  + YB1___4['19hr']+YB1___4['22hr']  + YB1___4['25hr']) 
YB1___4['day_max_rain'] = YB1___4.iloc[:, 10:14].max(axis=1)
YB1___4['date']= 20140825

In [93]:
YB1___5['1day_sum_rain'] = (YB1___5['4hr']  +YB1___5['7hr']+ YB1___5['10hr']  + YB1___5['13hr'] ) 
YB1___5['1day_max_rain'] = YB1___5.iloc[:, 6:10].max(axis=1)
YB1___5['day_sum_rain'] = (YB1___5['16hr']  + YB1___5['19hr']+YB1___5['22hr']  + YB1___5['25hr']) 
YB1___5['day_max_rain'] = YB1___5.iloc[:, 10:14].max(axis=1)
YB1___5['date']= 20161005

In [94]:
YB1___6['1day_sum_rain'] = (YB1___6['4hr']  +YB1___6['7hr']+ YB1___6['10hr']  + YB1___6['13hr'] ) 
YB1___6['1day_max_rain'] = YB1___6.iloc[:, 6:10].max(axis=1)
YB1___6['day_sum_rain'] = (YB1___6['16hr']  + YB1___6['19hr']+YB1___6['22hr']  + YB1___6['25hr']) 
YB1___6['day_max_rain'] = YB1___6.iloc[:, 10:14].max(axis=1)
YB1___6['date']= 20180703

In [95]:
YB1___7['1day_sum_rain'] = (YB1___7['4hr']  +YB1___7['7hr']+ YB1___7['10hr']  + YB1___7['13hr'] ) 
YB1___7['1day_max_rain'] = YB1___7.iloc[:, 6:10].max(axis=1)
YB1___7['day_sum_rain'] = (YB1___7['16hr']  + YB1___7['19hr']+YB1___7['22hr']  + YB1___7['25hr']) 
YB1___7['day_max_rain'] = YB1___7.iloc[:, 10:14].max(axis=1)
YB1___7['date']= 20180826

In [96]:
YB1___8['1day_sum_rain'] = (YB1___8['4hr']  +YB1___8['7hr']+ YB1___8['10hr']  + YB1___8['13hr'] ) 
YB1___8['1day_max_rain'] = YB1___8.iloc[:, 6:10].max(axis=1)
YB1___8['day_sum_rain'] = (YB1___8['16hr']  + YB1___8['19hr']+YB1___8['22hr']  + YB1___8['25hr']) 
YB1___8['day_max_rain'] = YB1___8.iloc[:, 10:14].max(axis=1)
YB1___8['date']= 20181006

In [97]:
YB1___9['1day_sum_rain'] = (YB1___9['4hr']  +YB1___9['7hr']+ YB1___9['10hr']  + YB1___9['13hr'] ) 
YB1___9['1day_max_rain'] = YB1___9.iloc[:, 6:10].max(axis=1)
YB1___9['day_sum_rain'] = (YB1___9['16hr']  + YB1___9['19hr']+YB1___9['22hr']  + YB1___9['25hr']) 
YB1___9['day_max_rain'] = YB1___9.iloc[:, 10:14].max(axis=1)
YB1___9['date']= 20190720

In [98]:
YB1___10['1day_sum_rain'] = (YB1___10['4hr']  +YB1___10['7hr']+ YB1___10['10hr']  + YB1___10['13hr'] ) 
YB1___10['1day_max_rain'] = YB1___10.iloc[:, 6:10].max(axis=1)
YB1___10['day_sum_rain'] = (YB1___10['16hr']  + YB1___10['19hr']+YB1___10['22hr']  + YB1___10['25hr']) 
YB1___10['day_max_rain'] = YB1___10.iloc[:, 10:14].max(axis=1)
YB1___10['date']= 20191002

In [99]:
YB1___11['1day_sum_rain'] = (YB1___11['4hr']  +YB1___11['7hr']+ YB1___11['10hr']  + YB1___11['13hr'] ) 
YB1___11['1day_max_rain'] = YB1___11.iloc[:, 6:10].max(axis=1)
YB1___11['day_sum_rain'] = (YB1___11['16hr']  + YB1___11['19hr']+YB1___11['22hr']  + YB1___11['25hr']) 
YB1___11['day_max_rain'] = YB1___11.iloc[:, 10:14].max(axis=1)
YB1___11['date']= 20191003

In [100]:
SYB1___11=YB1___11.drop(['variable','4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1___10=YB1___10.drop(['variable','4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1___9=YB1___9.drop(['variable','4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1___8=YB1___8.drop(['variable','4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1___7=YB1___7.drop(['variable','4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1___6=YB1___6.drop(['variable','4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1___5=YB1___5.drop(['variable','4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1___4=YB1___4.drop(['variable','4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB1___3=YB1___3.drop(['variable','4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr'],axis=1)
SYB1___2=YB1___2.drop(['variable','4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr'],axis=1)
SYB1___1=YB1___1.drop(['variable','4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr'],axis=1)

In [101]:
RAIN=pd.concat([SYB1___11,SYB1___10,SYB1___9,SYB1___8,SYB1___7,SYB1___6,SYB1___5,SYB1___4,SYB1___3,SYB1___2,SYB1___1])

In [102]:
RAIN

,sd,sgg,umd,x,y,1day_sum_rain,1day_max_rain,day_sum_rain,day_max_rain,date
0,경상북도,포항시남구,구룡포읍,105,94,220.0,70.0,160.0,70.0,20191003
1,경상북도,포항시남구,연일읍,102,94,220.0,70.0,160.0,70.0,20191003
2,경상북도,포항시남구,오천읍,103,93,220.0,70.0,160.0,70.0,20191003
3,경상북도,포항시남구,대송면,102,93,220.0,70.0,160.0,70.0,20191003
4,경상북도,포항시남구,동해면2,104,94,220.0,70.0,160.0,70.0,20191003
...,...,...,...,...,...,...,...,...,...,...
632,경상남도,합천군,쌍백면,81,81,NaN,NaN,NaN,NaN,20110709
633,경상남도,합천군,삼가면,81,80,NaN,NaN,NaN,NaN,20110709
634,경상남도,합천군,가회면,79,81,NaN,NaN,NaN,NaN,20110709
635,경상남도,합천군,대병면,79,83,NaN,NaN,NaN,NaN,20110709
636,경상남도,합천군,용주면,81,83,NaN,NaN,NaN,NaN,20110709

In [103]:
RAIN.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7007 entries, 0 to 636
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sd             7007 non-null   object
 1   sgg            7007 non-null   object
 2   umd            7007 non-null   object
 3   x              7007 non-null   int64
 4   y              7007 non-null   int64
 5   1day_sum_rain  4459 non-null   object
 6   1day_max_rain  4459 non-null   float64
 7   day_sum_rain   4459 non-null   object
 8   day_max_rain   4459 non-null   float64
 9   date           7007 non-null   int64
dtypes: float64(2), int64(3), object(5)
memory usage: 602.2+ KB

In [104]:
weather__1=pd.merge(weather_1, RAIN, on=['sd', 'sgg', 'umd', 'x', 'y', 'date'], how= 'inner')

In [105]:
weather__1

,sd,sgg,umd,x,y,1day_mean_T3H,1day_min_T3H,1day_max_T3H,day_mean_T3H,day_min_T3H,...,day_max_WAV,date,1day_mode_PTY,day_mode_PTY,1day_mode_SKY,day_mode_SKY,1day_sum_rain,1day_max_rain,day_sum_rain,day_max_rain
0,경상북도,포항시남구,구룡포읍,105,94,22.833333,22.0,25.0,23.875,19.0,...,2.5,20191003,1.0,1.0,4.0,4.0,220.0,70.0,160.0,70.0
1,경상북도,포항시남구,연일읍,102,94,23.166667,22.0,25.0,24.375,20.0,...,0.0,20191003,1.0,1.0,4.0,4.0,220.0,70.0,160.0,70.0
2,경상북도,포항시남구,오천읍,103,93,23.0,22.0,25.0,25.0,22.0,...,0.0,20191003,1.0,1.0,4.0,4.0,220.0,70.0,160.0,70.0
3,경상북도,포항시남구,대송면,102,93,23.0,22.0,25.0,24.375,20.0,...,0.0,20191003,1.0,1.0,4.0,4.0,220.0,70.0,160.0,70.0
4,경상북도,포항시남구,동해면2,104,94,23.333333,22.0,25.0,24.875,21.0,...,1.5,20191003,1.0,1.0,4.0,4.0,220.0,70.0,160.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7002,경상남도,합천군,쌍백면,81,81,26.6,24.9,28.0,25.15,23.8,...,0.0,20110709,0.0,1.0,4.0,4.0,NaN,NaN,NaN,NaN
7003,경상남도,합천군,삼가면,81,80,26.666667,25.0,28.0,25.25,24.0,...,0.0,20110709,0.0,1.0,4.0,4.0,NaN,NaN,NaN,NaN
7004,경상남도,합천군,가회면,79,81,26.216667,24.8,27.5,24.8,23.5,...,0.0,20110709,0.0,1.0,4.0,4.0,NaN,NaN,NaN,NaN
7005,경상남도,합천군,대병면,79,83,25.55,24.1,27.0,24.05,22.8,...,0.0,20110709,0.0,1.0,4.0,4.0,NaN,NaN,NaN,NaN
7006,경상남도,합천군,용주면,81,83,26.9,25.2,28.3,25.425,24.1,...,0.0,20110709,0.0,1.0,4.0,4.0,NaN,NaN,NaN,NaN

In [106]:
gc2_1=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20110707.csv')
gc2_1.rename(columns = {'20110707' : 'variable'}, inplace = True)


#좌표 변환 함수#
def abc(a, b, c):
    k= (int(a) +149*(int(b)-1)-1 ) + (37697*c)
    return k


def ac2_1(a):
    k = gc2_1.iloc[a:a+1,:]
    return k



z__1 = [8] # 8:강수량 # 6,7 -> PTY, SKY # 10: 최고기온 11: 최저기온 12:SKY2  13:적설량
t__1 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__1.append(abc(i, j, n))

u__1 = []
for i in t__1:
    u__1.append(ac2_1(i))
    
u__1=np.reshape(u__1, (637,25))

col2_name1 = gc2_1.columns

gcs2_1 = pd.DataFrame(u__1, columns=col2_name1)

p__1=[]
for i in range(1):
    a = gcs2_1.iloc[0+637*i:637+637*i,:]
    p__1.append(a)
    
pp__1=[]
for i in range(1):
    a=p__1[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__1.append(df)

gc2__1=pd.concat(pp__1)
gc2__1.rename(columns = {'20110707' : 'variable'}, inplace = True)

In [107]:
gc2_2=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20110708.csv')
gc2_2.rename(columns = {'20110708' : 'variable'}, inplace = True)

def ac2_2(a):
    k = gc2_2.iloc[a:a+1,:]
    return k




t__2 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__2.append(abc(i, j, n))

u__2 = []
for i in t__2:
    u__2.append(ac2_2(i))
    
u__2=np.reshape(u__2, (637,25))

col2_name2 = gc2_2.columns

gcs2_2 = pd.DataFrame(u__2, columns=col2_name2)

p__2=[]
for i in range(1):
    a = gcs2_2.iloc[0+637*i:637+637*i,:]
    p__2.append(a)
    
pp__2=[]
for i in range(1):
    a=p__2[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__2.append(df)

gc2__2=pd.concat(pp__2)
gc2__2.rename(columns = {'20110708' : 'variable'}, inplace = True)

In [108]:
gc2_3=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20110709.csv')
gc2_3.rename(columns = {'20110709' : 'variable'}, inplace = True)



def ac2_3(a):
    k = gc2_3.iloc[a:a+1,:]
    return k





t__3 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__3.append(abc(i, j, n))

u__3 = []
for i in t__3:
    u__3.append(ac2_3(i))
    
u__3=np.reshape(u__3, (637,25))

col2_name3 = gc2_3.columns

gcs2_3 = pd.DataFrame(u__3, columns=col2_name3)

p__3=[]
for i in range(1):
    a = gcs2_3.iloc[0+637*i:637+637*i,:]
    p__3.append(a)
    
pp__3=[]
for i in range(1):
    a=p__3[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__3.append(df)

gc2__3=pd.concat(pp__3)
gc2__3.rename(columns = {'20110709' : 'variable'}, inplace = True)

In [109]:
gc2_4=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20110806.csv')
gc2_4.rename(columns = {'20110806' : 'variable'}, inplace = True)




def ac2_4(a):
    k = gc2_4.iloc[a:a+1,:]
    return k



t__4 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__4.append(abc(i, j, n))

u__4 = []
for i in t__4:
    u__4.append(ac2_4(i))
    
u__4=np.reshape(u__4, (637,25))

col2_name4 = gc2_4.columns

gcs2_4 = pd.DataFrame(u__4, columns=col2_name4)

p__4=[]
for i in range(1):
    a = gcs2_4.iloc[0+637*i:637+637*i,:]
    p__4.append(a)
    
pp__4=[]
for i in range(1):
    a=p__4[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__4.append(df)

gc2__4=pd.concat(pp__4)
gc2__4.rename(columns = {'20110806' : 'variable'}, inplace = True)

In [110]:
gc2_5=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20110807.csv')
gc2_5.rename(columns = {'20110807' : 'variable'}, inplace = True)

def ac2_5(a):
    k = gc2_5.iloc[a:a+1,:]
    return k



t__5 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__5.append(abc(i, j, n))

u__5 = []
for i in t__5:
    u__5.append(ac2_5(i))
    
u__5=np.reshape(u__5, (637,25))

col2_name5 = gc2_5.columns

gcs2_5 = pd.DataFrame(u__5, columns=col2_name5)

p__5=[]
for i in range(1):
    a = gcs2_5.iloc[0+637*i:637+637*i,:]
    p__5.append(a)
    
pp__5=[]
for i in range(1):
    a=p__5[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__5.append(df)

gc2__5=pd.concat(pp__5)
gc2__5.rename(columns = {'20110807' : 'variable'}, inplace = True)

In [111]:
gc2_6=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20110808.csv')
gc2_6.rename(columns = {'20110808' : 'variable'}, inplace = True)



def ac2_6(a):
    k = gc2_6.iloc[a:a+1,:]
    return k



t__6 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__6.append(abc(i, j, n))

u__6 = []
for i in t__6:
    u__6.append(ac2_6(i))
    
u__6=np.reshape(u__6, (637,25))

col2_name6 = gc2_6.columns

gcs2_6 = pd.DataFrame(u__6, columns=col2_name6)

p__6=[]
for i in range(1):
    a = gcs2_6.iloc[0+637*i:637+637*i,:]
    p__6.append(a)
    
pp__6=[]
for i in range(1):
    a=p__6[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__6.append(df)

gc2__6=pd.concat(pp__6)
gc2__6.rename(columns = {'20110808' : 'variable'}, inplace = True)

In [112]:
gc2_7=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20120915.csv')
gc2_7.rename(columns = {'20120915' : 'variable'}, inplace = True)



def ac2_7(a):
    k = gc2_7.iloc[a:a+1,:]
    return k



t__7 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__7.append(abc(i, j, n))

u__7 = []
for i in t__7:
    u__7.append(ac2_7(i))
    
u__7=np.reshape(u__7, (637,25))

col2_name7 = gc2_7.columns

gcs2_7 = pd.DataFrame(u__7, columns=col2_name7)

p__7=[]
for i in range(1):
    a = gcs2_7.iloc[0+637*i:637+637*i,:]
    p__7.append(a)
    
pp__7=[]
for i in range(1):
    a=p__7[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__7.append(df)

gc2__7=pd.concat(pp__7)
gc2__7.rename(columns = {'20120915' : 'variable'}, inplace = True)

In [113]:
gc2_8=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20120916.csv')
gc2_8.rename(columns = {'20120916' : 'variable'}, inplace = True)



def ac2_8(a):
    k = gc2_8.iloc[a:a+1,:]
    return k



t__8 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__8.append(abc(i, j, n))

u__8 = []
for i in t__8:
    u__8.append(ac2_8(i))
    
u__8=np.reshape(u__8, (637,25))

col2_name8 = gc2_8.columns

gcs2_8 = pd.DataFrame(u__8, columns=col2_name8)

p__8=[]
for i in range(1):
    a = gcs2_8.iloc[0+637*i:637+637*i,:]
    p__8.append(a)
    
pp__8=[]
for i in range(1):
    a=p__8[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__8.append(df)

gc2__8=pd.concat(pp__8)
gc2__8.rename(columns = {'20120916' : 'variable'}, inplace = True)

In [114]:
gc2_9=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20120917.csv')
gc2_9.rename(columns = {'20120917' : 'variable'}, inplace = True)



def ac2_9(a):
    k = gc2_9.iloc[a:a+1,:]
    return k



t__9 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__9.append(abc(i, j, n))

u__9 = []
for i in t__9:
    u__9.append(ac2_9(i))
    
u__9=np.reshape(u__9, (637,25))

col2_name9 = gc2_9.columns

gcs2_9 = pd.DataFrame(u__9, columns=col2_name9)

p__9=[]
for i in range(1):
    a = gcs2_9.iloc[0+637*i:637+637*i,:]
    p__9.append(a)
    
pp__9=[]
for i in range(1):
    a=p__9[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__9.append(df)

gc2__9=pd.concat(pp__9)
gc2__9.rename(columns = {'20120917' : 'variable'}, inplace = True)

In [115]:
gc2_10=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20140823.csv')
gc2_10.rename(columns = {'20140823' : 'variable'}, inplace = True)


def ac2_10(a):
    k = gc2_10.iloc[a:a+1,:]
    return k



t__10 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__10.append(abc(i, j, n))

u__10 = []
for i in t__10:
    u__10.append(ac2_10(i))
    
u__10=np.reshape(u__10, (637,25))

col2_name10 = gc2_10.columns

gcs2_10 = pd.DataFrame(u__10, columns=col2_name10)

p__10=[]
for i in range(1):
    a = gcs2_10.iloc[0+637*i:637+637*i,:]
    p__10.append(a)
    
pp__10=[]
for i in range(1):
    a=p__10[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__10.append(df)

gc2__10=pd.concat(pp__10)
gc2__10.rename(columns = {'20140823' : 'variable'}, inplace = True)

In [116]:
gc2_11=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20140824.csv')
gc2_11.rename(columns = {'20140824' : 'variable'}, inplace = True)


def ac2_11(a):
    k = gc2_11.iloc[a:a+1,:]
    return k



t__11 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__11.append(abc(i, j, n))

u__11 = []
for i in t__11:
    u__11.append(ac2_11(i))
    
u__11=np.reshape(u__11, (637,25))

col2_name11 = gc2_11.columns

gcs2_11 = pd.DataFrame(u__11, columns=col2_name11)

p__11=[]
for i in range(1):
    a = gcs2_11.iloc[0+637*i:637+637*i,:]
    p__11.append(a)
    
pp__11=[]
for i in range(1):
    a=p__11[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__11.append(df)

gc2__11=pd.concat(pp__11)
gc2__11.rename(columns = {'20140824' : 'variable'}, inplace = True)

In [117]:
gc2_12=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20140825.csv')
gc2_12.rename(columns = {'20140825' : 'variable'}, inplace = True)


def ac2_12(a):
    k = gc2_12.iloc[a:a+1,:]
    return k



t__12 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__12.append(abc(i, j, n))

u__12 = []
for i in t__12:
    u__12.append(ac2_12(i))
    
u__12=np.reshape(u__12, (637,25))

col2_name12 = gc2_12.columns

gcs2_12 = pd.DataFrame(u__12, columns=col2_name12)

p__12=[]
for i in range(1):
    a = gcs2_12.iloc[0+637*i:637+637*i,:]
    p__12.append(a)
    
pp__12=[]
for i in range(1):
    a=p__12[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__12.append(df)

gc2__12=pd.concat(pp__12)
gc2__12.rename(columns = {'20140825' : 'variable'}, inplace = True)

In [118]:
gc2__2['4hr']=gc2__2['0h'] + gc2__2['1h']+gc2__2['2h']+ gc2__2['3h']+ gc2__2['4h']+gc2__2['5h']
gc2__2['7hr']=gc2__2['6h'] + gc2__2['7h'] + gc2__2['8h'] + gc2__2['9h'] + gc2__2['10h'] + gc2__2['11h']
gc2__2['10hr']=gc2__2['12h'] + gc2__2['13h'] + gc2__2['14h'] + gc2__2['15h'] + gc2__2['16h'] + gc2__2['17h']
gc2__2['13hr']=gc2__2['18h'] + gc2__2['19h'] + gc2__2['20h'] + gc2__2['21h'] + gc2__2['22h'] + gc2__2['23h']

gc2__2['1day_sum'] = gc2__2['4hr'] + gc2__2['7hr'] + gc2__2['10hr'] + gc2__2['13hr']
gc2__2['1day_max'] = gc2__2.iloc[:, 30:33].max(axis=1)
gc2__2['date']= 20110709

In [119]:
gc2__3['16hr']=gc2__3['0h'] + gc2__3['1h']+gc2__3['2h']+ gc2__3['3h']+ gc2__3['4h']+gc2__3['5h']
gc2__3['19hr']=gc2__3['6h'] + gc2__3['7h'] + gc2__3['8h'] + gc2__3['9h'] + gc2__3['10h'] + gc2__3['11h']
gc2__3['22hr']=gc2__3['12h'] + gc2__3['13h'] + gc2__3['14h'] + gc2__3['15h'] + gc2__3['16h'] + gc2__3['17h']
gc2__3['25hr']=gc2__3['18h'] + gc2__3['19h'] + gc2__3['20h'] + gc2__3['21h'] + gc2__3['22h'] + gc2__3['23h']

gc2__3['day_sum'] = gc2__3['16hr'] + gc2__3['19hr'] + gc2__3['22hr'] + gc2__3['25hr']
gc2__3['day_max'] = gc2__3.iloc[:, 30:33].max(axis=1)
gc2__3['date']= 20110709

In [120]:
gc2__5['4hr']=gc2__5['0h'] + gc2__5['1h']+gc2__5['2h']+ gc2__5['3h']+ gc2__5['4h']+gc2__5['5h']
gc2__5['7hr']=gc2__5['6h'] + gc2__5['7h'] + gc2__5['8h'] + gc2__5['9h'] + gc2__5['10h'] + gc2__5['11h']
gc2__5['10hr']=gc2__5['12h'] + gc2__5['13h'] + gc2__5['14h'] + gc2__5['15h'] + gc2__5['16h'] + gc2__5['17h']
gc2__5['13hr']=gc2__5['18h'] + gc2__5['19h'] + gc2__5['20h'] + gc2__5['21h'] + gc2__5['22h'] + gc2__5['23h']

gc2__5['1day_sum'] = gc2__5['4hr'] + gc2__5['7hr'] + gc2__5['10hr'] + gc2__5['13hr']
gc2__5['1day_max'] = gc2__5.iloc[:, 30:33].max(axis=1)
gc2__5['date']= 20110808

In [121]:
gc2__6['16hr']=gc2__6['0h'] + gc2__6['1h']+gc2__6['2h']+ gc2__6['3h']+ gc2__6['4h']+gc2__6['5h']
gc2__6['19hr']=gc2__6['6h'] + gc2__6['7h'] + gc2__6['8h'] + gc2__6['9h'] + gc2__6['10h'] + gc2__6['11h']
gc2__6['22hr']=gc2__6['12h'] + gc2__6['13h'] + gc2__6['14h'] + gc2__6['15h'] + gc2__6['16h'] + gc2__6['17h']
gc2__6['25hr']=gc2__6['18h'] + gc2__6['19h'] + gc2__6['20h'] + gc2__6['21h'] + gc2__6['22h'] + gc2__6['23h']

gc2__6['day_sum'] = gc2__6['16hr'] + gc2__6['19hr'] + gc2__6['22hr'] + gc2__6['25hr']
gc2__6['day_max'] = gc2__6.iloc[:, 30:33].max(axis=1)
gc2__6['date']= 20110808

In [122]:
gc2__8['4hr']=gc2__8['0h'] + gc2__8['1h']+gc2__8['2h']+ gc2__8['3h']+ gc2__8['4h']+gc2__8['5h']
gc2__8['7hr']=gc2__8['6h'] + gc2__8['7h'] + gc2__8['8h'] + gc2__8['9h'] + gc2__8['10h'] + gc2__8['11h']
gc2__8['10hr']=gc2__8['12h'] + gc2__8['13h'] + gc2__8['14h'] + gc2__8['15h'] + gc2__8['16h'] + gc2__8['17h']
gc2__8['13hr']=gc2__8['18h'] + gc2__8['19h'] + gc2__8['20h'] + gc2__8['21h'] + gc2__8['22h'] + gc2__8['23h']
gc2__8['1day_sum'] = gc2__8['4hr'] + gc2__8['7hr'] + gc2__8['10hr'] + gc2__8['13hr']
gc2__8['1day_max'] = gc2__8.iloc[:, 30:33].max(axis=1)
gc2__8['date']= 20120917

In [123]:
gc2__9['16hr']=gc2__9['0h'] + gc2__9['1h']+gc2__9['2h']+ gc2__9['3h']+ gc2__9['4h']+gc2__9['5h']
gc2__9['19hr']=gc2__9['6h'] + gc2__9['7h'] + gc2__9['8h'] + gc2__9['9h'] + gc2__9['10h'] + gc2__9['11h']
gc2__9['22hr']=gc2__9['12h'] + gc2__9['13h'] + gc2__9['14h'] + gc2__9['15h'] + gc2__9['16h'] + gc2__9['17h']
gc2__9['25hr']=gc2__9['18h'] + gc2__9['19h'] + gc2__9['20h'] + gc2__9['21h'] + gc2__9['22h'] + gc2__9['23h']
gc2__9['day_sum'] = gc2__9['16hr'] + gc2__9['19hr'] + gc2__9['22hr'] + gc2__9['25hr']
gc2__9['day_max'] = gc2__9.iloc[:, 30:33].max(axis=1)
gc2__9['date']= 20120917

In [124]:
gc2__11['4hr']=gc2__11['0h'] + gc2__11['1h']+gc2__11['2h']+ gc2__11['3h']+ gc2__11['4h']+gc2__11['5h']
gc2__11['7hr']=gc2__11['6h'] + gc2__11['7h'] + gc2__11['8h'] + gc2__11['9h'] + gc2__11['10h'] + gc2__11['11h']
gc2__11['10hr']=gc2__11['12h'] + gc2__11['13h'] + gc2__11['14h'] + gc2__11['15h'] + gc2__11['16h'] + gc2__11['17h']
gc2__11['13hr']=gc2__11['18h'] + gc2__11['19h'] + gc2__11['20h'] + gc2__11['21h'] + gc2__11['22h'] + gc2__11['23h']
gc2__11['1day_sum'] = gc2__11['4hr'] + gc2__11['7hr'] + gc2__11['10hr'] + gc2__11['13hr']
gc2__11['1day_max'] = gc2__11.iloc[:, 30:33].max(axis=1)
gc2__11['date']= 20140825

In [125]:
gc2__12['16hr']=gc2__12['0h'] + gc2__12['1h']+gc2__12['2h']+ gc2__12['3h']+ gc2__12['4h']+gc2__12['5h']
gc2__12['19hr']=gc2__12['6h'] + gc2__12['7h'] + gc2__12['8h'] + gc2__12['9h'] + gc2__12['10h'] + gc2__12['11h']
gc2__12['22hr']=gc2__12['12h'] + gc2__12['13h'] + gc2__12['14h'] + gc2__12['15h'] + gc2__12['16h'] + gc2__12['17h']
gc2__12['25hr']=gc2__12['18h'] + gc2__12['19h'] + gc2__12['20h'] + gc2__12['21h'] + gc2__12['22h'] + gc2__12['23h']
gc2__12['day_sum'] = gc2__12['16hr'] + gc2__12['19hr'] + gc2__12['22hr'] + gc2__12['25hr']
gc2__12['day_max'] = gc2__12.iloc[:, 30:33].max(axis=1)
gc2__12['date']= 20140825

In [126]:

dgc2__2=gc2__2.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__3=gc2__3.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)

dgc2__5=gc2__5.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__6=gc2__6.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)

dgc2__8=gc2__8.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__9=gc2__9.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)

dgc2__11=gc2__11.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__12=gc2__12.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)

In [127]:
listdata1= ['4hr','7hr','10hr','13hr']
listdata2=['16hr','19hr','22hr','25hr' ]

In [128]:
for _, f in enumerate(listdata1):
    list2 = [(dgc2__2[f]<=0.1), (dgc2__2[f]>0.1)&(dgc2__2[f]<=1), (dgc2__2[f]>1)&(dgc2__2[f]<=5),(dgc2__2[f]>5)&(dgc2__2[f]<=10),(dgc2__2[f]>10)&(dgc2__2[f]<=20),(dgc2__2[f]>20)&(dgc2__2[f]<=40),(dgc2__2[f]>40)&(dgc2__2[f]<=70),(dgc2__2[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__2[f]=np.select(list2, choicelist)

In [129]:
for _, f in enumerate(listdata2):
    list3 = [(dgc2__3[f]<=0.1), (dgc2__3[f]>0.1)&(gc2__3[f]<=1), (dgc2__3[f]>1)&(dgc2__3[f]<=5),(dgc2__3[f]>5)&(dgc2__3[f]<=10),(dgc2__3[f]>10)&(dgc2__3[f]<=20),(dgc2__3[f]>20)&(dgc2__3[f]<=40),(dgc2__3[f]>40)&(dgc2__3[f]<=70),(dgc2__3[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__3[f]=np.select(list3, choicelist)

In [130]:
for _, f in enumerate(listdata1):
    list2 = [(dgc2__5[f]<=0.1), (dgc2__5[f]>0.1)&(dgc2__5[f]<=1), (dgc2__5[f]>1)&(dgc2__5[f]<=5),(dgc2__5[f]>5)&(dgc2__5[f]<=10),(dgc2__5[f]>10)&(dgc2__5[f]<=20),(dgc2__5[f]>20)&(dgc2__5[f]<=40),(dgc2__5[f]>40)&(dgc2__5[f]<=70),(dgc2__5[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__5[f]=np.select(list2, choicelist)

In [131]:
for _, f in enumerate(listdata2):
    list3 = [(dgc2__6[f]<=0.1), (dgc2__6[f]>0.1)&(gc2__6[f]<=1), (dgc2__6[f]>1)&(dgc2__6[f]<=5),(dgc2__6[f]>5)&(dgc2__6[f]<=10),(dgc2__6[f]>10)&(dgc2__6[f]<=20),(dgc2__6[f]>20)&(dgc2__6[f]<=40),(dgc2__6[f]>40)&(dgc2__6[f]<=70),(dgc2__6[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__6[f]=np.select(list3, choicelist)

In [132]:
for _, f in enumerate(listdata1):
    list2 = [(dgc2__8[f]<=0.1), (dgc2__8[f]>0.1)&(dgc2__8[f]<=1), (dgc2__8[f]>1)&(dgc2__8[f]<=5),(dgc2__8[f]>5)&(dgc2__8[f]<=10),(dgc2__8[f]>10)&(dgc2__8[f]<=20),(dgc2__8[f]>20)&(dgc2__8[f]<=40),(dgc2__8[f]>40)&(dgc2__8[f]<=70),(dgc2__8[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__8[f]=np.select(list2, choicelist)

In [133]:
for _, f in enumerate(listdata2):
    list3 = [(dgc2__9[f]<=0.1), (dgc2__9[f]>0.1)&(gc2__9[f]<=1), (dgc2__9[f]>1)&(dgc2__9[f]<=5),(dgc2__9[f]>5)&(dgc2__9[f]<=10),(dgc2__9[f]>10)&(dgc2__9[f]<=20),(dgc2__9[f]>20)&(dgc2__9[f]<=40),(dgc2__9[f]>40)&(dgc2__9[f]<=70),(dgc2__9[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__9[f]=np.select(list3, choicelist)

In [134]:
for _, f in enumerate(listdata1):
    list2 = [(dgc2__11[f]<=0.1), (dgc2__11[f]>0.1)&(dgc2__11[f]<=1), (dgc2__11[f]>1)&(dgc2__11[f]<=5),(dgc2__11[f]>5)&(dgc2__11[f]<=10),(dgc2__11[f]>10)&(dgc2__11[f]<=20),(dgc2__11[f]>20)&(dgc2__11[f]<=40),(dgc2__11[f]>40)&(dgc2__11[f]<=70),(dgc2__11[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__11[f]=np.select(list2, choicelist)

In [135]:
for _, f in enumerate(listdata2):
    list3 = [(dgc2__12[f]<=0.1), (dgc2__12[f]>0.1)&(gc2__12[f]<=1), (dgc2__12[f]>1)&(dgc2__12[f]<=5),(dgc2__12[f]>5)&(dgc2__12[f]<=10),(dgc2__12[f]>10)&(dgc2__12[f]<=20),(dgc2__12[f]>20)&(dgc2__12[f]<=40),(dgc2__12[f]>40)&(dgc2__12[f]<=70),(dgc2__12[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__12[f]=np.select(list3, choicelist)

In [136]:
dgc2__2=dgc2__2.drop(['4hr','7hr','10hr','13hr'],axis=1)
dgc2__3=dgc2__3.drop(['16hr','19hr','22hr','25hr'],axis=1)
dgc2__5=dgc2__5.drop(['4hr','7hr','10hr','13hr'],axis=1)
dgc2__6=dgc2__6.drop(['16hr','19hr','22hr','25hr'],axis=1)
dgc2__8=dgc2__8.drop(['4hr','7hr','10hr','13hr'],axis=1)
dgc2__9=dgc2__9.drop(['16hr','19hr','22hr','25hr'],axis=1)
dgc2__11=dgc2__11.drop(['4hr','7hr','10hr','13hr'],axis=1)
dgc2__12=dgc2__12.drop(['16hr','19hr','22hr','25hr'],axis=1)

In [137]:
a0=pd.merge(dgc2__2, dgc2__3, on=['sd', 'sgg', 'umd', 'x', 'y', 'date','variable'], how= 'inner')

In [138]:
b0=pd.merge(dgc2__5, dgc2__6, on=['sd', 'sgg', 'umd', 'x', 'y', 'date','variable'], how= 'inner')

In [139]:
c0=pd.merge(dgc2__8, dgc2__9, on=['sd', 'sgg', 'umd', 'x', 'y', 'date','variable'], how= 'inner')

In [140]:
d0=pd.merge(dgc2__11, dgc2__12, on=['sd', 'sgg', 'umd', 'x', 'y', 'date','variable'], how= 'inner')

In [141]:
RAIN1=pd.concat([a0,b0,c0,d0])

In [142]:
RAIN1=RAIN1.drop(['variable'],axis=1)

In [143]:
RAIN1.rename(columns = {'1day_sum' : '1day_sum_rain','1day_max' : '1day_max_rain','day_sum' : 'day_sum_rain','day_max' : 'day_max_rain'}, inplace = True)

In [144]:
RAIN1

,sd,sgg,umd,x,y,1day_sum_rain,1day_max_rain,date,day_sum_rain,day_max_rain
0,경상북도,포항시남구,구룡포읍,105,94,0.0,0.0,20110709,141.0,94.0
1,경상북도,포항시남구,연일읍,102,94,0.0,0.0,20110709,123.0,73.0
2,경상북도,포항시남구,오천읍,103,93,0.0,0.0,20110709,132.0,80.0
3,경상북도,포항시남구,대송면,102,93,0.0,0.0,20110709,130.0,76.0
4,경상북도,포항시남구,동해면2,104,94,0.0,0.0,20110709,131.0,84.0
...,...,...,...,...,...,...,...,...,...,...
632,경상남도,합천군,쌍백면,81,81,5.0,0.0,20140825,81.0,46.0
633,경상남도,합천군,삼가면,81,80,5.0,0.0,20140825,91.0,51.0
634,경상남도,합천군,가회면,79,81,4.0,0.0,20140825,78.0,43.0
635,경상남도,합천군,대병면,79,83,3.0,0.0,20140825,60.0,33.0
636,경상남도,합천군,용주면,81,83,2.0,0.0,20140825,68.0,39.0

In [145]:
BBB1=weather__1.iloc[:4459, :]   
BBB2=weather__1.iloc[4459:,:]
BBB2=BBB2.drop(['1day_sum_rain','1day_max_rain','day_sum_rain','day_max_rain'],axis=1)
BBB_2 = pd.merge( BBB2, RAIN1, on=['sd', 'sgg', 'umd', 'x', 'y','date', 'umd'], how='inner')
SRAIN__1=pd.concat([BBB1,BBB_2])

In [146]:
SRAIN__1.to_csv('SRAIN__11.csv', index=False, encoding='CP949')