## 연속형자료

In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt

In [2]:
import pandas as pd

jido=pd.read_csv(r'C:\Users\stat_17\Desktop\지역좌표.csv', encoding='CP949')

In [3]:


x=jido.iloc[:, 3:4]
y=jido.iloc[:, 4:4+1]

import numpy as np
x=x.values.tolist()
y=y.values.tolist()

x=np.reshape(x, (637))
y=np.reshape(y, (637))

In [4]:
yb2_1=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20110707.csv')
yb2_1.rename(columns = {'2011070705' : 'variable'}, inplace = True)

#좌표 변환 함수#
def abc(a, b, c):
    k= (int(a) +149*(int(b)-1)-1 ) + (37697*c)
    return k

#변환한 행,리스트들 수집#
z = [0, 1, 4, 5, 9 , 14] # 8:강수량 # 6,7 -> PTY, SKY # 10: 최고기온 11: 최저기온 12:SKY2  13:적설량
t =[]
for n in z:
    for i, j in zip(x, y):
        t.append(abc(i, j, n))
        
#수집한 행의 리스트 행 추출#
def ac2_1(a):
    k = yb2_1.iloc[a:a+1,:]
    return k

##
u = []
for i in t:
    u.append(ac2_1(i))
    
    
##
u=np.reshape(u, (3822,23))

##
col2_name1 = yb2_1.columns

##
yb2__1 = pd.DataFrame(u, columns=col2_name1)

##
p=[]
for i in range(6):
    a = yb2__1.iloc[0+637*i:637+637*i,:]
    p.append(a)
    
##
pp=[]
for i in range(6):
    a=p[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp.append(df)
    
pp[5]=pp[5].loc[pp[5].variable == 'WAV'].replace(-1.0, 0)


ppp=pd.concat(pp[0:5])
YB2_1=pd.concat([ppp, pp[5]])

In [5]:
yb2_2=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20110806.csv')
yb2_2.rename(columns = {'2011080605' : 'variable'}, inplace = True)
t2 =[]
for n in z:
    for i, j in zip(x, y):
        t2.append(abc(i, j, n))
        
def ac2_2(a):
    k = yb2_2.iloc[a:a+1,:]
    return k

u2 = []
for i in t2:
    u2.append(ac2_2(i))
    
u2=np.reshape(u2, (3822,23))

col2_name2 = yb2_2.columns

yb2__2 = pd.DataFrame(u2, columns=col2_name2)

p2=[]
for i in range(6):
    a2 = yb2__2.iloc[0+637*i:637+637*i,:]
    p2.append(a2)
    
pp2=[]
for i in range(6):
    a2=p2[i].reset_index(drop=True)
    df2= jido.join(a2, how='left')
    pp2.append(df2)
    

pp2[5]=pp2[5].loc[pp2[5].variable == 'WAV'].replace(-1.0, 0)


ppp2=pd.concat(pp2[0:5])
YB2_2=pd.concat([ppp2, pp2[5]])

In [6]:
yb2_3=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20120915.csv')
yb2_3.rename(columns = {'2012091505' : 'variable'}, inplace = True)
t3 =[]
for n in z:
    for i, j in zip(x, y):
        t3.append(abc(i, j, n))
        
def ac2_3(a):
    k = yb2_3.iloc[a:a+1,:]
    return k

u3 = []
for i in t3:
    u3.append(ac2_3(i))
    
u3=np.reshape(u3, (3822,23))

col2_name3 = yb2_3.columns

yb2__3 = pd.DataFrame(u3, columns=col2_name3)

p3=[]
for i in range(6):
    a3 = yb2__3.iloc[0+637*i:637+637*i,:]
    p3.append(a3)
    
pp3=[]
for i in range(6):
    a3=p3[i].reset_index(drop=True)
    df3= jido.join(a3, how='left')
    pp3.append(df3)
    
pp3[5]=pp3[5].loc[pp3[5].variable == 'WAV'].replace(-1.0, 0)


ppp3=pd.concat(pp3[0:5])
YB2_3=pd.concat([ppp3, pp3[5]])

In [7]:
yb2_4=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20140823.csv')
yb2_4.rename(columns = {'2014082305' : 'variable'}, inplace = True)
t4 =[]
for n in z:
    for i, j in zip(x, y):
        t4.append(abc(i, j, n))
        
def ac2_4(a):
    k = yb2_4.iloc[a:a+1,:]
    return k

u4 = []
for i in t4:
    u4.append(ac2_4(i))
    
u4=np.reshape(u4, (3822,23))

col2_name4 = yb2_4.columns

yb2__4 = pd.DataFrame(u4, columns=col2_name4)

p4=[]
for i in range(6):
    a4 = yb2__4.iloc[0+637*i:637+637*i,:]
    p4.append(a4)
    
pp4=[]
for i in range(6):
    a4=p4[i].reset_index(drop=True)
    df4= jido.join(a4, how='left')
    pp4.append(df4)
    
pp4[5]=pp4[5].loc[pp4[5].variable == 'WAV'].replace(-1.0, 0)


ppp4=pd.concat(pp4[0:5])
YB2_4=pd.concat([ppp4, pp4[5]])

In [8]:
yb2_5=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20161003.csv')
yb2_5.rename(columns = {'2016100305' : 'variable'}, inplace = True)
t5 =[]
for n in z:
    for i, j in zip(x, y):
        t5.append(abc(i, j, n))
        
def ac2_5(a):
    k = yb2_5.iloc[a:a+1,:]
    return k

u5 = []
for i in t5:
    u5.append(ac2_5(i))
    
u5=np.reshape(u5, (3822,23))

col2_name5 = yb2_5.columns

yb2__5 = pd.DataFrame(u5, columns=col2_name5)

p5=[]
for i in range(6):
    a5 = yb2__5.iloc[0+637*i:637+637*i,:]
    p5.append(a5)
    
pp5=[]
for i in range(6):
    a5=p5[i].reset_index(drop=True)
    df5= jido.join(a5, how='left')
    pp5.append(df5)
    
pp5[5]=pp5[5].loc[pp5[5].variable == 'WAV'].replace(-1.0, 0)


ppp5=pd.concat(pp5[0:5])
YB2_5=pd.concat([ppp5, pp5[5]])

In [9]:
yb2_6=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20180701.csv')
yb2_6.rename(columns = {'2018070105' : 'variable'}, inplace = True)
t6 =[]
for n in z:
    for i, j in zip(x, y):
        t6.append(abc(i, j, n))
        
def ac2_6(a):
    k = yb2_6.iloc[a:a+1,:]
    return k

u6 = []
for i in t6:
    u6.append(ac2_6(i))
    
u6=np.reshape(u6, (3822,23))

col2_name6 = yb2_6.columns

yb2__6 = pd.DataFrame(u6, columns=col2_name6)

p6=[]
for i in range(6):
    a6 = yb2__6.iloc[0+637*i:637+637*i,:]
    p6.append(a6)
    
pp6=[]
for i in range(6):
    a6=p6[i].reset_index(drop=True)
    df6= jido.join(a6, how='left')
    pp6.append(df6)
    
pp6[5]=pp6[5].loc[pp6[5].variable == 'WAV'].replace(-1.0, 0)


ppp6=pd.concat(pp6[0:5])
YB2_6=pd.concat([ppp6, pp6[5]])

In [10]:
yb2_7=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20180824.csv')
yb2_7.rename(columns = {'2018082405' : 'variable'}, inplace = True)
t7 =[]
for n in z:
    for i, j in zip(x, y):
        t7.append(abc(i, j, n))
        
def ac2_7(a):
    k = yb2_7.iloc[a:a+1,:]
    return k

u7 = []
for i in t7:
    u7.append(ac2_7(i))
    
u7=np.reshape(u7, (3822,23))

col2_name7 = yb2_7.columns

yb2__7 = pd.DataFrame(u7, columns=col2_name7)

p7=[]
for i in range(6):
    a7 = yb2__7.iloc[0+637*i:637+637*i,:]
    p7.append(a7)
    
pp7=[]
for i in range(6):
    a7=p7[i].reset_index(drop=True)
    df7= jido.join(a7, how='left')
    pp7.append(df7)
    
pp7[5]=pp7[5].loc[pp7[5].variable == 'WAV'].replace(-1.0, 0)


ppp7=pd.concat(pp7[0:5])
YB2_7=pd.concat([ppp7, pp7[5]])

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [11]:
yb2_8=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20181004.csv')
yb2_8.rename(columns = {'2018100405' : 'variable'}, inplace = True)
t8 =[]
for n in z:
    for i, j in zip(x, y):
        t8.append(abc(i, j, n))
        
def ac2_8(a):
    k = yb2_8.iloc[a:a+1,:]
    return k

u8 = []
for i in t8:
    u8.append(ac2_8(i))
    
u8=np.reshape(u8, (3822,23))

col2_name8 = yb2_8.columns

yb2__8 = pd.DataFrame(u8, columns=col2_name8)

p8=[]
for i in range(6):
    a8 = yb2__8.iloc[0+637*i:637+637*i,:]
    p8.append(a8)
    
pp8=[]
for i in range(6):
    a8=p8[i].reset_index(drop=True)
    df8= jido.join(a8, how='left')
    pp8.append(df8)
    

pp8[5]=pp8[5].loc[pp8[5].variable == 'WAV'].replace(-1.0, 0)


ppp8=pd.concat(pp8[0:5])
YB2_8=pd.concat([ppp8, pp8[5]])

In [12]:
yb2_9=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20190718.csv')
yb2_9.rename(columns = {'2019071805' : 'variable'}, inplace = True)
t9 =[]
for n in z:
    for i, j in zip(x, y):
        t9.append(abc(i, j, n))
        
def ac2_9(a):
    k = yb2_9.iloc[a:a+1,:]
    return k

u9 = []
for i in t9:
    u9.append(ac2_9(i))
    
u9=np.reshape(u9, (3822,23))

col2_name9 = yb2_9.columns

yb2__9 = pd.DataFrame(u9, columns=col2_name9)

p9=[]
for i in range(6):
    a9 = yb2__9.iloc[0+637*i:637+637*i,:]
    p9.append(a9)
    
pp9=[]
for i in range(6):
    a9=p9[i].reset_index(drop=True)
    df9= jido.join(a9, how='left')
    pp9.append(df9)
    
pp9[5]=pp9[5].loc[pp9[5].variable == 'WAV'].replace(-1.0, 0)


ppp9=pd.concat(pp9[0:5])
YB2_9=pd.concat([ppp9, pp9[5]])

In [13]:
yb2_10=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20190930.csv')
yb2_10.rename(columns = {'2019093005' : 'variable'}, inplace = True)
t10 =[]
for n in z:
    for i, j in zip(x, y):
        t10.append(abc(i, j, n))
        
def ac2_10(a):
    k = yb2_10.iloc[a:a+1,:]
    return k

u10 = []
for i in t10:
    u10.append(ac2_10(i))
    
u10=np.reshape(u10, (3822,23))

col2_name10 = yb2_10.columns

yb2__10 = pd.DataFrame(u10, columns=col2_name10)

p10=[]
for i in range(6):
    a10 = yb2__10.iloc[0+637*i:637+637*i,:]
    p10.append(a10)
    
pp10=[]
for i in range(6):
    a10=p10[i].reset_index(drop=True)
    df10= jido.join(a10, how='left')
    pp10.append(df10)
    
pp10[5]=pp10[5].loc[pp10[5].variable == 'WAV'].replace(-1.0, 0)


ppp10=pd.concat(pp10[0:5])
YB2_10=pd.concat([ppp10, pp10[5]])

In [14]:
yb2_11=pd.read_csv(r'C:\Users\stat_17\Desktop\예보데이터\SHRT_20191001.csv')
yb2_11.rename(columns = {'2019100105' : 'variable'}, inplace = True)
t11 =[]
for n in z:
    for i, j in zip(x, y):
        t11.append(abc(i, j, n))
        
def ac2_11(a):
    k = yb2_11.iloc[a:a+1,:]
    return k

u11 = []
for i in t11:
    u11.append(ac2_11(i))
    
u11=np.reshape(u11, (3822,23))

col2_name11 = yb2_11.columns

yb2__11 = pd.DataFrame(u11, columns=col2_name11)

p11=[]
for i in range(6):
    a11 = yb2__11.iloc[0+637*i:637+637*i,:]
    p11.append(a11)
    
pp11=[]
for i in range(6):
    a11=p11[i].reset_index(drop=True)
    df11= jido.join(a11, how='left')
    pp11.append(df11)
    
pp11[5]=pp11[5].loc[pp11[5].variable == 'WAV'].replace(-1.0, 0)


ppp11=pd.concat(pp11[0:5])
YB2_11=pd.concat([ppp11, pp11[5]])

In [15]:
#YB2_1['date'] = 20110709 
YB2_1['2day_mean'] = (YB2_1['4hr']  +YB2_1['7hr']  + YB2_1['10hr']  + YB2_1['13hr'] +YB2_1['16hr']  + YB2_1['19hr']  ) /6
YB2_1['2day_max'] = YB2_1.iloc[:, 6:12].max(axis=1)
YB2_1['2day_min'] = YB2_1.iloc[:, 6:12].min(axis=1)
YB2_1['1day_mean'] = (  YB2_1['22hr']  + YB2_1['25hr']+ YB2_1['28hr']  + YB2_1['31hr']  + YB2_1['34hr'] + YB2_1['37hr'] +YB2_1['40hr']  + YB2_1['43hr']) /8
YB2_1['1day_max'] = YB2_1.iloc[:, 12:20].max(axis=1)
YB2_1['1day_min'] = YB2_1.iloc[:, 12:20].min(axis=1)
YB2_1['day_mean'] = ( YB2_1['46hr']  + YB2_1['49hr']+ YB2_1['52hr']  + YB2_1['55hr']  + YB2_1['58hr'] + YB2_1['61hr']  + YB2_1['64hr'] + YB2_1['67hr']) /8 
YB2_1['day_max'] = YB2_1.iloc[:, 20:28].max(axis=1)
YB2_1['day_min'] = YB2_1.iloc[:, 20:28].min(axis=1)

In [16]:
#YB2_2['date'] = 20110808
YB2_2['2day_mean'] = (YB2_2['4hr']  +YB2_2['7hr']  + YB2_2['10hr']  + YB2_2['13hr'] +YB2_2['16hr']  + YB2_2['19hr']  ) /6
YB2_2['2day_max'] = YB2_2.iloc[:, 6:12].max(axis=1)
YB2_2['2day_min'] = YB2_2.iloc[:, 6:12].min(axis=1)
YB2_2['1day_mean'] = (  YB2_2['22hr']  + YB2_2['25hr']+ YB2_2['28hr']  + YB2_2['31hr']  + YB2_2['34hr'] + YB2_2['37hr'] +YB2_2['40hr']  + YB2_2['43hr']) /8
YB2_2['1day_max'] = YB2_2.iloc[:, 12:20].max(axis=1)
YB2_2['1day_min'] = YB2_2.iloc[:, 12:20].min(axis=1)
YB2_2['day_mean'] = ( YB2_2['46hr']  + YB2_2['49hr']+ YB2_2['52hr']  + YB2_2['55hr']  + YB2_2['58hr'] + YB2_2['61hr']  + YB2_2['64hr'] + YB2_2['67hr']) /8 
YB2_2['day_max'] = YB2_2.iloc[:, 20:28].max(axis=1)
YB2_2['day_min'] = YB2_2.iloc[:, 20:28].min(axis=1)

In [17]:
#YB2_3['date'] = 20120917
YB2_3['2day_mean'] = (YB2_3['4hr']  +YB2_3['7hr']  + YB2_3['10hr']  + YB2_3['13hr'] +YB2_3['16hr']  + YB2_3['19hr']  ) /6
YB2_3['2day_max'] = YB2_3.iloc[:, 6:12].max(axis=1)
YB2_3['2day_min'] = YB2_3.iloc[:, 6:12].min(axis=1)
YB2_3['1day_mean'] = (  YB2_3['22hr']  + YB2_3['25hr']+ YB2_3['28hr']  + YB2_3['31hr']  + YB2_3['34hr'] + YB2_3['37hr'] +YB2_3['40hr']  + YB2_3['43hr']) /8
YB2_3['1day_max'] = YB2_3.iloc[:, 12:20].max(axis=1)
YB2_3['1day_min'] = YB2_3.iloc[:, 12:20].min(axis=1)
YB2_3['day_mean'] = ( YB2_3['46hr']  + YB2_3['49hr']+ YB2_3['52hr']  + YB2_3['55hr']  + YB2_3['58hr'] + YB2_3['61hr']  + YB2_3['64hr'] + YB2_3['67hr']) /8 
YB2_3['day_max'] = YB2_3.iloc[:, 20:28].max(axis=1)
YB2_3['day_min'] = YB2_3.iloc[:, 20:28].min(axis=1)

In [18]:
#YB2_4['date'] = 20140825
YB2_4['2day_mean'] = (YB2_4['4hr']  +YB2_4['7hr']  + YB2_4['10hr']  + YB2_4['13hr'] +YB2_4['16hr']  + YB2_4['19hr']  ) /6
YB2_4['2day_max'] = YB2_4.iloc[:, 6:12].max(axis=1)
YB2_4['2day_min'] = YB2_4.iloc[:, 6:12].min(axis=1)
YB2_4['1day_mean'] = (  YB2_4['22hr']  + YB2_4['25hr']+ YB2_4['28hr']  + YB2_4['31hr']  + YB2_4['34hr'] + YB2_4['37hr'] +YB2_4['40hr']  + YB2_4['43hr']) /8
YB2_4['1day_max'] = YB2_4.iloc[:, 12:20].max(axis=1)
YB2_4['1day_min'] = YB2_4.iloc[:, 12:20].min(axis=1)
YB2_4['day_mean'] = ( YB2_4['46hr']  + YB2_4['49hr']+ YB2_4['52hr']  + YB2_4['55hr']  + YB2_4['58hr'] + YB2_4['61hr']  + YB2_4['64hr'] + YB2_4['67hr']) /8 
YB2_4['day_max'] = YB2_4.iloc[:, 20:28].max(axis=1)
YB2_4['day_min'] = YB2_4.iloc[:, 20:28].min(axis=1)

In [19]:
#YB2_5['date'] = 20161005
YB2_5['2day_mean'] = (YB2_5['4hr']  +YB2_5['7hr']  + YB2_5['10hr']  + YB2_5['13hr'] +YB2_5['16hr']  + YB2_5['19hr']  ) /6
YB2_5['2day_max'] = YB2_5.iloc[:, 6:12].max(axis=1)
YB2_5['2day_min'] = YB2_5.iloc[:, 6:12].min(axis=1)
YB2_5['1day_mean'] = (  YB2_5['22hr']  + YB2_5['25hr']+ YB2_5['28hr']  + YB2_5['31hr']  + YB2_5['34hr'] + YB2_5['37hr'] +YB2_5['40hr']  + YB2_5['43hr']) /8
YB2_5['1day_max'] = YB2_5.iloc[:, 12:20].max(axis=1)
YB2_5['1day_min'] = YB2_5.iloc[:, 12:20].min(axis=1)
YB2_5['day_mean'] = ( YB2_5['46hr']  + YB2_5['49hr']+ YB2_5['52hr']  + YB2_5['55hr']  + YB2_5['58hr'] + YB2_5['61hr']  + YB2_5['64hr'] + YB2_5['67hr']) /8 
YB2_5['day_max'] = YB2_5.iloc[:, 20:28].max(axis=1)
YB2_5['day_min'] = YB2_5.iloc[:, 20:28].min(axis=1)

In [20]:
#YB2_6['date'] = 20180703
YB2_6['2day_mean'] = (YB2_6['4hr']  +YB2_6['7hr']  + YB2_6['10hr']  + YB2_6['13hr'] +YB2_6['16hr']  + YB2_6['19hr']  ) /6
YB2_6['2day_max'] = YB2_6.iloc[:, 6:12].max(axis=1)
YB2_6['2day_min'] = YB2_6.iloc[:, 6:12].min(axis=1)
YB2_6['1day_mean'] = (  YB2_6['22hr']  + YB2_6['25hr']+ YB2_6['28hr']  + YB2_6['31hr']  + YB2_6['34hr'] + YB2_6['37hr'] +YB2_6['40hr']  + YB2_6['43hr']) /8
YB2_6['1day_max'] = YB2_6.iloc[:, 12:20].max(axis=1)
YB2_6['1day_min'] = YB2_6.iloc[:, 12:20].min(axis=1)
YB2_6['day_mean'] = ( YB2_6['46hr']  + YB2_6['49hr']+ YB2_6['52hr']  + YB2_6['55hr']  + YB2_6['58hr'] + YB2_6['61hr']  + YB2_6['64hr'] + YB2_6['67hr']) /8 
YB2_6['day_max'] = YB2_6.iloc[:, 20:28].max(axis=1)
YB2_6['day_min'] = YB2_6.iloc[:, 20:28].min(axis=1)

In [21]:
#YB2_7['date'] = 20180826
YB2_7['2day_mean'] = (YB2_7['4hr']  +YB2_7['7hr']  + YB2_7['10hr']  + YB2_7['13hr'] +YB2_7['16hr']  + YB2_7['19hr']  ) /6
YB2_7['2day_max'] = YB2_7.iloc[:, 6:12].max(axis=1)
YB2_7['2day_min'] = YB2_7.iloc[:, 6:12].min(axis=1)
YB2_7['1day_mean'] = (  YB2_7['22hr']  + YB2_7['25hr']+ YB2_7['28hr']  + YB2_7['31hr']  + YB2_7['34hr'] + YB2_7['37hr'] +YB2_7['40hr']  + YB2_7['43hr']) /8
YB2_7['1day_max'] = YB2_7.iloc[:, 12:20].max(axis=1)
YB2_7['1day_min'] = YB2_7.iloc[:, 12:20].min(axis=1)
YB2_7['day_mean'] = ( YB2_7['46hr']  + YB2_7['49hr']+ YB2_7['52hr']  + YB2_7['55hr']  + YB2_7['58hr'] + YB2_7['61hr']  + YB2_7['64hr'] + YB2_7['67hr']) /8 
YB2_7['day_max'] = YB2_7.iloc[:, 20:28].max(axis=1)
YB2_7['day_min'] = YB2_7.iloc[:, 20:28].min(axis=1)

In [22]:
#YB2_8['date'] = 20181006
YB2_8['2day_mean'] = (YB2_8['4hr']  +YB2_8['7hr']  + YB2_8['10hr']  + YB2_8['13hr'] +YB2_8['16hr']  + YB2_8['19hr']  ) /6
YB2_8['2day_max'] = YB2_8.iloc[:, 6:12].max(axis=1)
YB2_8['2day_min'] = YB2_8.iloc[:, 6:12].min(axis=1)
YB2_8['1day_mean'] = (  YB2_8['22hr']  + YB2_8['25hr']+ YB2_8['28hr']  + YB2_8['31hr']  + YB2_8['34hr'] + YB2_8['37hr'] +YB2_8['40hr']  + YB2_8['43hr']) /8
YB2_8['1day_max'] = YB2_8.iloc[:, 12:20].max(axis=1)
YB2_8['1day_min'] = YB2_8.iloc[:, 12:20].min(axis=1)
YB2_8['day_mean'] = ( YB2_8['46hr']  + YB2_8['49hr']+ YB2_8['52hr']  + YB2_8['55hr']  + YB2_8['58hr'] + YB2_8['61hr']  + YB2_8['64hr'] + YB2_8['67hr']) /8 
YB2_8['day_max'] = YB2_8.iloc[:, 20:28].max(axis=1)
YB2_8['day_min'] = YB2_8.iloc[:, 20:28].min(axis=1)

In [23]:
#YB2_9['date'] = 20190720
YB2_9['2day_mean'] = (YB2_9['4hr']  +YB2_9['7hr']  + YB2_9['10hr']  + YB2_9['13hr'] +YB2_9['16hr']  + YB2_9['19hr']  ) /6
YB2_9['2day_max'] = YB2_9.iloc[:, 6:12].max(axis=1)
YB2_9['2day_min'] = YB2_9.iloc[:, 6:12].min(axis=1)
YB2_9['1day_mean'] = (  YB2_9['22hr']  + YB2_9['25hr']+ YB2_9['28hr']  + YB2_9['31hr']  + YB2_9['34hr'] + YB2_9['37hr'] +YB2_9['40hr']  + YB2_9['43hr']) /8
YB2_9['1day_max'] = YB2_9.iloc[:, 12:20].max(axis=1)
YB2_9['1day_min'] = YB2_9.iloc[:, 12:20].min(axis=1)
YB2_9['day_mean'] = ( YB2_9['46hr']  + YB2_9['49hr']+ YB2_9['52hr']  + YB2_9['55hr']  + YB2_9['58hr'] + YB2_9['61hr']  + YB2_9['64hr'] + YB2_9['67hr']) /8 
YB2_9['day_max'] = YB2_9.iloc[:, 20:28].max(axis=1)
YB2_9['day_min'] = YB2_9.iloc[:, 20:28].min(axis=1)

In [24]:
#YB2_10['date'] = 20191002
YB2_10['2day_mean'] = (YB2_10['4hr']  +YB2_10['7hr']  + YB2_10['10hr']  + YB2_10['13hr'] +YB2_10['16hr']  + YB2_10['19hr']  ) /6
YB2_10['2day_max'] = YB2_10.iloc[:, 6:12].max(axis=1)
YB2_10['2day_min'] = YB2_10.iloc[:, 6:12].min(axis=1)
YB2_10['1day_mean'] = (  YB2_10['22hr']  + YB2_10['25hr']+ YB2_10['28hr']  + YB2_10['31hr']  + YB2_10['34hr'] + YB2_10['37hr'] +YB2_10['40hr']  + YB2_10['43hr']) /8
YB2_10['1day_max'] = YB2_10.iloc[:, 12:20].max(axis=1)
YB2_10['1day_min'] = YB2_10.iloc[:, 12:20].min(axis=1)
YB2_10['day_mean'] = ( YB2_10['46hr']  + YB2_10['49hr']+ YB2_10['52hr']  + YB2_10['55hr']  + YB2_10['58hr'] + YB2_10['61hr']  + YB2_10['64hr'] + YB2_10['67hr']) /8 
YB2_10['day_max'] = YB2_10.iloc[:, 20:28].max(axis=1)
YB2_10['day_min'] = YB2_10.iloc[:, 20:28].min(axis=1)

In [25]:
#YB2_11['date'] = 20191003
YB2_11['2day_mean'] = (YB2_11['4hr']  +YB2_11['7hr']  + YB2_11['10hr']  + YB2_11['13hr'] +YB2_11['16hr']  + YB2_11['19hr']  ) /6
YB2_11['2day_max'] = YB2_11.iloc[:, 6:12].max(axis=1)
YB2_11['2day_min'] = YB2_11.iloc[:, 6:12].min(axis=1)
YB2_11['1day_mean'] = (  YB2_11['22hr']  + YB2_11['25hr']+ YB2_11['28hr']  + YB2_11['31hr']  + YB2_11['34hr'] + YB2_11['37hr'] +YB2_11['40hr']  + YB2_11['43hr']) /8
YB2_11['1day_max'] = YB2_11.iloc[:, 12:20].max(axis=1)
YB2_11['1day_min'] = YB2_11.iloc[:, 12:20].min(axis=1)
YB2_11['day_mean'] = ( YB2_11['46hr']  + YB2_11['49hr']+ YB2_11['52hr']  + YB2_11['55hr']  + YB2_11['58hr'] + YB2_11['61hr']  + YB2_11['64hr'] + YB2_11['67hr']) /8 
YB2_11['day_max'] = YB2_11.iloc[:, 20:28].max(axis=1)
YB2_11['day_min'] = YB2_11.iloc[:, 20:28].min(axis=1)

In [26]:
SYB2_11=YB2_11.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2_10=YB2_10.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2_9=YB2_9.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2_8=YB2_8.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2_7=YB2_7.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2_6=YB2_6.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2_5=YB2_5.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2_4=YB2_4.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2_3=YB2_3.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2_2=YB2_2.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2_1=YB2_1.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)

In [27]:
def cba1(a):
    k = SYB2_1.iloc[0+637*a:637+637*a,:]
    return k

uu = []
for i in range(6):
    uu.append(cba1(i))

In [28]:
RD2_1=pd.merge(uu[0], uu[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_1.rename(columns = {'2day_mean_x' : '2day_mean_T3H','2day_min_x' : '2day_min_T3H', '2day_max_x' : '2day_max_T3H', '1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD2_1.rename(columns = {'2day_mean_y' : '2day_mean_REH','2day_min_y' : '2day_min_REH', '2day_max_y' : '2day_max_REH', '1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD2_1=pd.merge(RD2_1, uu[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_1=pd.merge(RD2_1, uu[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_1.rename(columns = {'2day_mean_x' : '2day_mean_WSD','2day_min_x' : '2day_min_WSD', '2day_max_x' : '2day_max_WSD', '1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD2_1.rename(columns = {'2day_mean_y' : '2day_mean_VEC','2day_min_y' : '2day_min_VEC', '2day_max_y' : '2day_max_VEC', '1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD2_1=pd.merge(RD2_1, uu[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_1=pd.merge(RD2_1, uu[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_1.rename(columns = {'2day_mean_x' : '2day_mean_POP','2day_min_x' : '2day_min_POP', '2day_max_x' : '2day_max_POP', '1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD2_1.rename(columns = {'2day_mean_y' : '2day_mean_WAV','2day_min_y' : '2day_min_WAV', '2day_max_y' : '2day_max_WAV', '1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA2_1= RD2_1.drop(['variable_x','variable_y'] , axis=1)
RDA2_1['date']=20110709

<ipython-input-28-bcd74d98485d>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA2_1['date']=20110709

In [29]:
def cba2(a):
    k = SYB2_2.iloc[0+637*a:637+637*a,:]
    return k

uu2 = []
for i in range(6):
    uu2.append(cba2(i))





RD2_2=pd.merge(uu2[0], uu2[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_2.rename(columns = {'2day_mean_x' : '2day_mean_T3H','2day_min_x' : '2day_min_T3H', '2day_max_x' : '2day_max_T3H', '1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD2_2.rename(columns = {'2day_mean_y' : '2day_mean_REH','2day_min_y' : '2day_min_REH', '2day_max_y' : '2day_max_REH', '1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD2_2=pd.merge(RD2_2, uu2[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_2=pd.merge(RD2_2, uu2[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_2.rename(columns = {'2day_mean_x' : '2day_mean_WSD','2day_min_x' : '2day_min_WSD', '2day_max_x' : '2day_max_WSD', '1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD2_2.rename(columns = {'2day_mean_y' : '2day_mean_VEC','2day_min_y' : '2day_min_VEC', '2day_max_y' : '2day_max_VEC', '1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD2_2=pd.merge(RD2_2, uu2[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_2=pd.merge(RD2_2, uu2[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_2.rename(columns = {'2day_mean_x' : '2day_mean_POP','2day_min_x' : '2day_min_POP', '2day_max_x' : '2day_max_POP', '1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD2_2.rename(columns = {'2day_mean_y' : '2day_mean_WAV','2day_min_y' : '2day_min_WAV', '2day_max_y' : '2day_max_WAV', '1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA2_2= RD2_2.drop(['variable_x','variable_y'] , axis=1)
RDA2_2['date']=20110808

<ipython-input-29-aeb18e0da929>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA2_2['date']=20110808

In [30]:
def cba3(a):
    k = SYB2_3.iloc[0+637*a:637+637*a,:]
    return k

uu3 = []
for i in range(6):
    uu3.append(cba3(i))





RD2_3=pd.merge(uu3[0], uu3[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_3.rename(columns = {'2day_mean_x' : '2day_mean_T3H','2day_min_x' : '2day_min_T3H', '2day_max_x' : '2day_max_T3H', '1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD2_3.rename(columns = {'2day_mean_y' : '2day_mean_REH','2day_min_y' : '2day_min_REH', '2day_max_y' : '2day_max_REH', '1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD2_3=pd.merge(RD2_3, uu3[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_3=pd.merge(RD2_3, uu3[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_3.rename(columns = {'2day_mean_x' : '2day_mean_WSD','2day_min_x' : '2day_min_WSD', '2day_max_x' : '2day_max_WSD', '1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD2_3.rename(columns = {'2day_mean_y' : '2day_mean_VEC','2day_min_y' : '2day_min_VEC', '2day_max_y' : '2day_max_VEC', '1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD2_3=pd.merge(RD2_3, uu3[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_3=pd.merge(RD2_3, uu3[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_3.rename(columns = {'2day_mean_x' : '2day_mean_POP','2day_min_x' : '2day_min_POP', '2day_max_x' : '2day_max_POP', '1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD2_3.rename(columns = {'2day_mean_y' : '2day_mean_WAV','2day_min_y' : '2day_min_WAV', '2day_max_y' : '2day_max_WAV', '1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA2_3= RD2_3.drop(['variable_x','variable_y'] , axis=1)
RDA2_3['date']=20120917

<ipython-input-30-f1457ea9c078>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA2_3['date']=20120917

In [31]:
def cba4(a):
    k = SYB2_4.iloc[0+637*a:637+637*a,:]
    return k

uu4 = []
for i in range(6):
    uu4.append(cba4(i))





RD2_4=pd.merge(uu4[0], uu4[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_4.rename(columns = {'2day_mean_x' : '2day_mean_T3H','2day_min_x' : '2day_min_T3H', '2day_max_x' : '2day_max_T3H', '1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD2_4.rename(columns = {'2day_mean_y' : '2day_mean_REH','2day_min_y' : '2day_min_REH', '2day_max_y' : '2day_max_REH', '1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD2_4=pd.merge(RD2_4, uu4[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_4=pd.merge(RD2_4, uu4[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_4.rename(columns = {'2day_mean_x' : '2day_mean_WSD','2day_min_x' : '2day_min_WSD', '2day_max_x' : '2day_max_WSD', '1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD2_4.rename(columns = {'2day_mean_y' : '2day_mean_VEC','2day_min_y' : '2day_min_VEC', '2day_max_y' : '2day_max_VEC', '1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD2_4=pd.merge(RD2_4, uu4[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_4=pd.merge(RD2_4, uu4[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_4.rename(columns = {'2day_mean_x' : '2day_mean_POP','2day_min_x' : '2day_min_POP', '2day_max_x' : '2day_max_POP', '1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD2_4.rename(columns = {'2day_mean_y' : '2day_mean_WAV','2day_min_y' : '2day_min_WAV', '2day_max_y' : '2day_max_WAV', '1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA2_4= RD2_4.drop(['variable_x','variable_y'] , axis=1)
RDA2_4['date']=20140825

<ipython-input-31-7ba3fe105834>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA2_4['date']=20140825

In [32]:
def cba5(a):
    k = SYB2_5.iloc[0+637*a:637+637*a,:]
    return k

uu5 = []
for i in range(6):
    uu5.append(cba5(i))





RD2_5=pd.merge(uu5[0], uu5[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_5.rename(columns = {'2day_mean_x' : '2day_mean_T3H','2day_min_x' : '2day_min_T3H', '2day_max_x' : '2day_max_T3H', '1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD2_5.rename(columns = {'2day_mean_y' : '2day_mean_REH','2day_min_y' : '2day_min_REH', '2day_max_y' : '2day_max_REH', '1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD2_5=pd.merge(RD2_5, uu5[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_5=pd.merge(RD2_5, uu5[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_5.rename(columns = {'2day_mean_x' : '2day_mean_WSD','2day_min_x' : '2day_min_WSD', '2day_max_x' : '2day_max_WSD', '1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD2_5.rename(columns = {'2day_mean_y' : '2day_mean_VEC','2day_min_y' : '2day_min_VEC', '2day_max_y' : '2day_max_VEC', '1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD2_5=pd.merge(RD2_5, uu5[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_5=pd.merge(RD2_5, uu5[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_5.rename(columns = {'2day_mean_x' : '2day_mean_POP','2day_min_x' : '2day_min_POP', '2day_max_x' : '2day_max_POP', '1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD2_5.rename(columns = {'2day_mean_y' : '2day_mean_WAV','2day_min_y' : '2day_min_WAV', '2day_max_y' : '2day_max_WAV', '1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA2_5= RD2_5.drop(['variable_x','variable_y'] , axis=1)
RDA2_5['date']=20161005

<ipython-input-32-f767138b6d17>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA2_5['date']=20161005

In [33]:
def cba6(a):
    k = SYB2_6.iloc[0+637*a:637+637*a,:]
    return k

uu6 = []
for i in range(6):
    uu6.append(cba6(i))





RD2_6=pd.merge(uu6[0], uu6[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_6.rename(columns = {'2day_mean_x' : '2day_mean_T3H','2day_min_x' : '2day_min_T3H', '2day_max_x' : '2day_max_T3H', '1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD2_6.rename(columns = {'2day_mean_y' : '2day_mean_REH','2day_min_y' : '2day_min_REH', '2day_max_y' : '2day_max_REH', '1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD2_6=pd.merge(RD2_6, uu6[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_6=pd.merge(RD2_6, uu6[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_6.rename(columns = {'2day_mean_x' : '2day_mean_WSD','2day_min_x' : '2day_min_WSD', '2day_max_x' : '2day_max_WSD', '1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD2_6.rename(columns = {'2day_mean_y' : '2day_mean_VEC','2day_min_y' : '2day_min_VEC', '2day_max_y' : '2day_max_VEC', '1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD2_6=pd.merge(RD2_6, uu6[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_6=pd.merge(RD2_6, uu6[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_6.rename(columns = {'2day_mean_x' : '2day_mean_POP','2day_min_x' : '2day_min_POP', '2day_max_x' : '2day_max_POP', '1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD2_6.rename(columns = {'2day_mean_y' : '2day_mean_WAV','2day_min_y' : '2day_min_WAV', '2day_max_y' : '2day_max_WAV', '1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA2_6= RD2_6.drop(['variable_x','variable_y'] , axis=1)
RDA2_6['date']=20180703

<ipython-input-33-fd28dd38e72e>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA2_6['date']=20180703

In [34]:
def cba7(a):
    k = SYB2_7.iloc[0+637*a:637+637*a,:]
    return k

uu7 = []
for i in range(6):
    uu7.append(cba7(i))


RD2_7=pd.merge(uu7[0], uu7[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_7.rename(columns = {'2day_mean_x' : '2day_mean_T3H','2day_min_x' : '2day_min_T3H', '2day_max_x' : '2day_max_T3H', '1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD2_7.rename(columns = {'2day_mean_y' : '2day_mean_REH','2day_min_y' : '2day_min_REH', '2day_max_y' : '2day_max_REH', '1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD2_7=pd.merge(RD2_7, uu7[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_7=pd.merge(RD2_7, uu7[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_7.rename(columns = {'2day_mean_x' : '2day_mean_WSD','2day_min_x' : '2day_min_WSD', '2day_max_x' : '2day_max_WSD', '1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD2_7.rename(columns = {'2day_mean_y' : '2day_mean_VEC','2day_min_y' : '2day_min_VEC', '2day_max_y' : '2day_max_VEC', '1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD2_7=pd.merge(RD2_7, uu7[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_7=pd.merge(RD2_7, uu7[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_7.rename(columns = {'2day_mean_x' : '2day_mean_POP','2day_min_x' : '2day_min_POP', '2day_max_x' : '2day_max_POP', '1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD2_7.rename(columns = {'2day_mean_y' : '2day_mean_WAV','2day_min_y' : '2day_min_WAV', '2day_max_y' : '2day_max_WAV', '1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA2_7= RD2_7.drop(['variable_x','variable_y'] , axis=1)
RDA2_7['date']=20180826

<ipython-input-34-34d58f8b3ead>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA2_7['date']=20180826

In [35]:
def cba8(a):
    k = SYB2_8.iloc[0+637*a:637+637*a,:]
    return k

uu8 = []
for i in range(6):
    uu8.append(cba8(i))


RD2_8=pd.merge(uu8[0], uu8[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_8.rename(columns = {'2day_mean_x' : '2day_mean_T3H','2day_min_x' : '2day_min_T3H', '2day_max_x' : '2day_max_T3H', '1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD2_8.rename(columns = {'2day_mean_y' : '2day_mean_REH','2day_min_y' : '2day_min_REH', '2day_max_y' : '2day_max_REH', '1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD2_8=pd.merge(RD2_8, uu8[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_8=pd.merge(RD2_8, uu8[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_8.rename(columns = {'2day_mean_x' : '2day_mean_WSD','2day_min_x' : '2day_min_WSD', '2day_max_x' : '2day_max_WSD', '1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD2_8.rename(columns = {'2day_mean_y' : '2day_mean_VEC','2day_min_y' : '2day_min_VEC', '2day_max_y' : '2day_max_VEC', '1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD2_8=pd.merge(RD2_8, uu8[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_8=pd.merge(RD2_8, uu8[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_8.rename(columns = {'2day_mean_x' : '2day_mean_POP','2day_min_x' : '2day_min_POP', '2day_max_x' : '2day_max_POP', '1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD2_8.rename(columns = {'2day_mean_y' : '2day_mean_WAV','2day_min_y' : '2day_min_WAV', '2day_max_y' : '2day_max_WAV', '1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA2_8= RD2_8.drop(['variable_x','variable_y'] , axis=1)
RDA2_8['date']=20181006

<ipython-input-35-e3467e8d3dc8>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA2_8['date']=20181006

In [36]:
def cba9(a):
    k = SYB2_9.iloc[0+637*a:637+637*a,:]
    return k

uu9 = []
for i in range(6):
    uu9.append(cba9(i))


RD2_9=pd.merge(uu9[0], uu9[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_9.rename(columns = {'2day_mean_x' : '2day_mean_T3H','2day_min_x' : '2day_min_T3H', '2day_max_x' : '2day_max_T3H', '1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD2_9.rename(columns = {'2day_mean_y' : '2day_mean_REH','2day_min_y' : '2day_min_REH', '2day_max_y' : '2day_max_REH', '1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD2_9=pd.merge(RD2_9, uu9[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_9=pd.merge(RD2_9, uu9[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_9.rename(columns = {'2day_mean_x' : '2day_mean_WSD','2day_min_x' : '2day_min_WSD', '2day_max_x' : '2day_max_WSD', '1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD2_9.rename(columns = {'2day_mean_y' : '2day_mean_VEC','2day_min_y' : '2day_min_VEC', '2day_max_y' : '2day_max_VEC', '1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD2_9=pd.merge(RD2_9, uu9[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_9=pd.merge(RD2_9, uu9[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_9.rename(columns = {'2day_mean_x' : '2day_mean_POP','2day_min_x' : '2day_min_POP', '2day_max_x' : '2day_max_POP', '1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD2_9.rename(columns = {'2day_mean_y' : '2day_mean_WAV','2day_min_y' : '2day_min_WAV', '2day_max_y' : '2day_max_WAV', '1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA2_9= RD2_9.drop(['variable_x','variable_y'] , axis=1)
RDA2_9['date']=20190720

<ipython-input-36-f45ca5942bdc>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA2_9['date']=20190720

In [37]:
def cba10(a):
    k = SYB2_10.iloc[0+637*a:637+637*a,:]
    return k

uu10 = []
for i in range(6):
    uu10.append(cba10(i))


RD2_10=pd.merge(uu10[0], uu10[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_10.rename(columns = {'2day_mean_x' : '2day_mean_T3H','2day_min_x' : '2day_min_T3H', '2day_max_x' : '2day_max_T3H', '1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD2_10.rename(columns = {'2day_mean_y' : '2day_mean_REH','2day_min_y' : '2day_min_REH', '2day_max_y' : '2day_max_REH', '1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD2_10=pd.merge(RD2_10, uu10[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_10=pd.merge(RD2_10, uu10[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_10.rename(columns = {'2day_mean_x' : '2day_mean_WSD','2day_min_x' : '2day_min_WSD', '2day_max_x' : '2day_max_WSD', '1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD2_10.rename(columns = {'2day_mean_y' : '2day_mean_VEC','2day_min_y' : '2day_min_VEC', '2day_max_y' : '2day_max_VEC', '1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD2_10=pd.merge(RD2_10, uu10[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_10=pd.merge(RD2_10, uu10[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_10.rename(columns = {'2day_mean_x' : '2day_mean_POP','2day_min_x' : '2day_min_POP', '2day_max_x' : '2day_max_POP', '1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD2_10.rename(columns = {'2day_mean_y' : '2day_mean_WAV','2day_min_y' : '2day_min_WAV', '2day_max_y' : '2day_max_WAV', '1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA2_10= RD2_10.drop(['variable_x','variable_y'] , axis=1)
RDA2_10['date']=20191002

<ipython-input-37-40b2cd59df06>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA2_10['date']=20191002

In [38]:
def cba11(a):
    k = SYB2_11.iloc[0+637*a:637+637*a,:]
    return k

uu11 = []
for i in range(6):
    uu11.append(cba11(i))


RD2_11=pd.merge(uu11[0], uu11[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_11.rename(columns = {'2day_mean_x' : '2day_mean_T3H','2day_min_x' : '2day_min_T3H', '2day_max_x' : '2day_max_T3H', '1day_mean_x':'1day_mean_T3H', '1day_min_x':'1day_min_T3H', '1day_max_x':'1day_max_T3H', 'day_mean_x':'day_mean_T3H', 'day_max_x':'day_max_T3H', 'day_min_x':'day_min_T3H'}, inplace = True)
RD2_11.rename(columns = {'2day_mean_y' : '2day_mean_REH','2day_min_y' : '2day_min_REH', '2day_max_y' : '2day_max_REH', '1day_mean_y':'1day_mean_REH', '1day_min_y':'1day_min_REH', '1day_max_y':'1day_max_REH', 'day_mean_y':'day_mean_REH', 'day_max_y':'day_max_REH', 'day_min_y':'day_min_REH'}, inplace = True)

RD2_11=pd.merge(RD2_11, uu11[2], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_11=pd.merge(RD2_11, uu11[3], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_11.rename(columns = {'2day_mean_x' : '2day_mean_WSD','2day_min_x' : '2day_min_WSD', '2day_max_x' : '2day_max_WSD', '1day_mean_x':'1day_mean_WSD', '1day_min_x':'1day_min_WSD', '1day_max_x':'1day_max_WSD', 'day_mean_x':'day_mean_WSD', 'day_max_x':'day_max_WSD', 'day_min_x':'day_min_WSD'}, inplace = True)
RD2_11.rename(columns = {'2day_mean_y' : '2day_mean_VEC','2day_min_y' : '2day_min_VEC', '2day_max_y' : '2day_max_VEC', '1day_mean_y':'1day_mean_VEC', '1day_min_y':'1day_min_VEC', '1day_max_y':'1day_max_VEC', 'day_mean_y':'day_mean_VEC', 'day_max_y':'day_max_VEC', 'day_min_y':'day_min_VEC'}, inplace = True)

RD2_11=pd.merge(RD2_11, uu11[4], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_11=pd.merge(RD2_11, uu11[5], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2_11.rename(columns = {'2day_mean_x' : '2day_mean_POP','2day_min_x' : '2day_min_POP', '2day_max_x' : '2day_max_POP', '1day_mean_x':'1day_mean_POP', '1day_min_x':'1day_min_POP', '1day_max_x':'1day_max_POP', 'day_mean_x':'day_mean_POP', 'day_max_x':'day_max_POP', 'day_min_x':'day_min_POP'}, inplace = True)
RD2_11.rename(columns = {'2day_mean_y' : '2day_mean_WAV','2day_min_y' : '2day_min_WAV', '2day_max_y' : '2day_max_WAV', '1day_mean_y':'1day_mean_WAV', '1day_min_y':'1day_min_WAV', '1day_max_y':'1day_max_WAV', 'day_mean_y':'day_mean_WAV', 'day_max_y':'day_max_WAV', 'day_min_y':'day_min_WAV'}, inplace = True)

RDA2_11= RD2_11.drop(['variable_x','variable_y'] , axis=1)
RDA2_11['date']=20191003

<ipython-input-38-af9c85ca007f>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RDA2_11['date']=20191003

In [39]:
RRDDAA=pd.concat([RDA2_11,RDA2_10,RDA2_9,RDA2_8,RDA2_7,RDA2_6,RDA2_5,RDA2_4,RDA2_3,RDA2_2,RDA2_1])

In [40]:
RRDDAA

,sd,sgg,umd,x,y,2day_mean_T3H,2day_max_T3H,2day_min_T3H,1day_mean_T3H,1day_max_T3H,...,2day_mean_WAV,2day_max_WAV,2day_min_WAV,1day_mean_WAV,1day_max_WAV,1day_min_WAV,day_mean_WAV,day_max_WAV,day_min_WAV,date
0,경상북도,포항시남구,구룡포읍,105,94,22.5,24.0,21.0,22.0,24.0,...,0.5,0.5,0.5,1.6875,3.5,0.5,1.4375,2.0,1.0,20191003
1,경상북도,포항시남구,연일읍,102,94,23.666667,25.0,22.0,22.5,24.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20191003
2,경상북도,포항시남구,오천읍,103,93,23.666667,25.0,22.0,22.625,24.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20191003
3,경상북도,포항시남구,대송면,102,93,23.5,25.0,22.0,22.375,24.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20191003
4,경상북도,포항시남구,동해면2,104,94,23.5,25.0,22.0,22.5,24.0,...,0.5,0.5,0.5,1.0,2.0,0.5,0.8125,1.0,0.5,20191003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,경상남도,합천군,쌍백면,81,81,25.75,27.9,22.9,25.9375,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20110709
633,경상남도,합천군,삼가면,81,80,25.833333,28.0,23.0,26.0,28.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20110709
634,경상남도,합천군,가회면,79,81,25.5,27.5,22.5,25.6875,28.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20110709
635,경상남도,합천군,대병면,79,83,25.066667,27.1,22.0,25.15,28.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20110709
636,경상남도,합천군,용주면,81,83,26.2,28.3,23.2,26.4375,29.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20110709

## 범주형자료

In [41]:
z_1 = [6,7] # 8:강수량 # 6,7 -> PTY, SKY # 10: 최고기온 11: 최저기온 12:SKY2  13:적설량
t_1 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_1.append(abc(i, j, n))

u_1 = []
for i in t_1:
    u_1.append(ac2_1(i))
    
u_1=np.reshape(u_1, (1274,23))

col2_name1 = yb2_1.columns

ybs2_1 = pd.DataFrame(u_1, columns=col2_name1)

p_1=[]
for i in range(2):
    a = ybs2_1.iloc[0+637*i:637+637*i,:]
    p_1.append(a)
    
pp_1=[]
for i in range(2):
    a=p_1[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_1.append(df)

YB2__1=pd.concat(pp_1)
YB2__1.rename(columns = {'2011070705' : 'variable'}, inplace = True)

In [42]:
t_2 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_2.append(abc(i, j, n))

u_2 = []
for i in t_2:
    u_2.append(ac2_2(i))

u_2=np.reshape(u_2, (1274,23))

col2_name2 = yb2_2.columns

ybs2_2 = pd.DataFrame(u_2, columns=col2_name2)

p_2=[]
for i in range(2):
    a = ybs2_2.iloc[0+637*i:637+637*i,:]
    p_2.append(a)
    
pp_2=[]
for i in range(2):
    a=p_2[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_2.append(df)

YB2__2=pd.concat(pp_2)
YB2__2.rename(columns = {'2011080605' : 'variable'}, inplace = True)

In [43]:
t_3 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_3.append(abc(i, j, n))

u_3 = []
for i in t_3:
    u_3.append(ac2_3(i))

u_3=np.reshape(u_3, (1274,23))

col2_name3 = yb2_3.columns

ybs2_3 = pd.DataFrame(u_3, columns=col2_name3)

p_3=[]
for i in range(2):
    a = ybs2_3.iloc[0+637*i:637+637*i,:]
    p_3.append(a)
    
pp_3=[]
for i in range(2):
    a=p_3[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_3.append(df)

YB2__3=pd.concat(pp_3)
YB2__3.rename(columns = {'2012091505' : 'variable'}, inplace = True)

In [44]:
t_4 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_4.append(abc(i, j, n))

u_4 = []
for i in t_4:
    u_4.append(ac2_4(i))

u_4=np.reshape(u_4, (1274,23))

col2_name4 = yb2_4.columns

ybs2_4 = pd.DataFrame(u_4, columns=col2_name4)

p_4=[]
for i in range(2):
    a = ybs2_4.iloc[0+637*i:637+637*i,:]
    p_4.append(a)
    
pp_4=[]
for i in range(2):
    a=p_4[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_4.append(df)

YB2__4=pd.concat(pp_4)
YB2__4.rename(columns = {'2014082305' : 'variable'}, inplace = True)

In [45]:
t_5 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_5.append(abc(i, j, n))

u_5 = []
for i in t_5:
    u_5.append(ac2_5(i))

u_5=np.reshape(u_5, (1274,23))

col2_name5 = yb2_5.columns

ybs2_5 = pd.DataFrame(u_5, columns=col2_name5)

p_5=[]
for i in range(2):
    a = ybs2_5.iloc[0+637*i:637+637*i,:]
    p_5.append(a)
    
pp_5=[]
for i in range(2):
    a=p_5[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_5.append(df)

YB2__5=pd.concat(pp_5)
YB2__5.rename(columns = {'2016100305' : 'variable'}, inplace = True)

In [46]:
t_6 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_6.append(abc(i, j, n))

u_6 = []
for i in t_6:
    u_6.append(ac2_6(i))

u_6=np.reshape(u_6, (1274,23))

col2_name6 = yb2_6.columns

ybs2_6 = pd.DataFrame(u_6, columns=col2_name6)

p_6=[]
for i in range(2):
    a = ybs2_6.iloc[0+637*i:637+637*i,:]
    p_6.append(a)
    
pp_6=[]
for i in range(2):
    a=p_6[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_6.append(df)

YB2__6=pd.concat(pp_6)
YB2__6.rename(columns = {'2018070105' : 'variable'}, inplace = True)

In [47]:
t_7 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_7.append(abc(i, j, n))

u_7 = []
for i in t_7:
    u_7.append(ac2_7(i))

u_7=np.reshape(u_7, (1274,23))

col2_name7 = yb2_7.columns

ybs2_7 = pd.DataFrame(u_7, columns=col2_name7)

p_7=[]
for i in range(2):
    a = ybs2_7.iloc[0+637*i:637+637*i,:]
    p_7.append(a)
    
pp_7=[]
for i in range(2):
    a=p_7[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_7.append(df)

YB2__7=pd.concat(pp_7)
YB2__7.rename(columns = {'2018082405' : 'variable'}, inplace = True)

In [48]:
t_8 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_8.append(abc(i, j, n))

u_8 = []
for i in t_8:
    u_8.append(ac2_8(i))

u_8=np.reshape(u_8, (1274,23))

col2_name8 = yb2_8.columns

ybs2_8 = pd.DataFrame(u_8, columns=col2_name8)

p_8=[]
for i in range(2):
    a = ybs2_8.iloc[0+637*i:637+637*i,:]
    p_8.append(a)
    
pp_8=[]
for i in range(2):
    a=p_8[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_8.append(df)

YB2__8=pd.concat(pp_8)
YB2__8.rename(columns = {'2018100405' : 'variable'}, inplace = True)

In [49]:
t_9 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_9.append(abc(i, j, n))

u_9 = []
for i in t_9:
    u_9.append(ac2_9(i))

u_9=np.reshape(u_9, (1274,23))

col2_name9 = yb2_9.columns

ybs2_9 = pd.DataFrame(u_9, columns=col2_name9)

p_9=[]
for i in range(2):
    a = ybs2_9.iloc[0+637*i:637+637*i,:]
    p_9.append(a)
    
pp_9=[]
for i in range(2):
    a=p_9[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_9.append(df)

YB2__9=pd.concat(pp_9)
YB2__9.rename(columns = {'2019071805' : 'variable'}, inplace = True)

In [50]:
t_10 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_10.append(abc(i, j, n))

u_10 = []
for i in t_10:
    u_10.append(ac2_10(i))

u_10=np.reshape(u_10, (1274,23))

col2_name10 = yb2_10.columns

ybs2_10 = pd.DataFrame(u_10, columns=col2_name10)

p_10=[]
for i in range(2):
    a = ybs2_10.iloc[0+637*i:637+637*i,:]
    p_10.append(a)
    
pp_10=[]
for i in range(2):
    a=p_10[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_10.append(df)

YB2__10=pd.concat(pp_10)
YB2__10.rename(columns = {'2019093005' : 'variable'}, inplace = True)

In [51]:
t_11 =[]
for n in z_1:
    for i, j in zip(x, y):
        t_11.append(abc(i, j, n))

u_11 = []
for i in t_11:
    u_11.append(ac2_11(i))

u_11=np.reshape(u_11, (1274,23))

col2_name11 = yb2_11.columns

ybs2_11 = pd.DataFrame(u_11, columns=col2_name11)

p_11=[]
for i in range(2):
    a = ybs2_11.iloc[0+637*i:637+637*i,:]
    p_11.append(a)
    
pp_11=[]
for i in range(2):
    a=p_11[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp_11.append(df)

YB2__11=pd.concat(pp_11)
YB2__11.rename(columns = {'2019100105' : 'variable'}, inplace = True)

In [52]:
from scipy.stats import mode
YB2__1['2day_mode'] = YB2__1.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB2__1['1day_mode'] = YB2__1.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

YB2__1['day_mode'] = YB2__1.iloc[:, 20:28].mode(axis=1).dropna(axis=1)

In [53]:
YB2__2['2day_mode'] = YB2__2.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB2__2['1day_mode'] = YB2__2.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

YB2__2['day_mode'] = YB2__2.iloc[:, 20:28].mode(axis=1).dropna(axis=1)

In [54]:
YB2__3['2day_mode'] = YB2__3.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB2__3['1day_mode'] = YB2__3.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

YB2__3['day_mode'] = YB2__3.iloc[:, 20:28].mode(axis=1).dropna(axis=1)

In [55]:
YB2__4['2day_mode'] = YB2__4.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB2__4['1day_mode'] = YB2__4.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

YB2__4['day_mode'] = YB2__4.iloc[:, 20:28].mode(axis=1).dropna(axis=1)

In [56]:
YB2__5['2day_mode'] = YB2__5.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB2__5['1day_mode'] = YB2__5.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

YB2__5['day_mode'] = YB2__5.iloc[:, 20:28].mode(axis=1).dropna(axis=1)

In [57]:
YB2__6['2day_mode'] = YB2__6.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB2__6['1day_mode'] = YB2__6.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

YB2__6['day_mode'] = YB2__6.iloc[:, 20:28].mode(axis=1).dropna(axis=1)

In [58]:
YB2__7['2day_mode'] = YB2__7.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB2__7['1day_mode'] = YB2__7.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

YB2__7['day_mode'] = YB2__7.iloc[:, 20:28].mode(axis=1).dropna(axis=1)

In [59]:
YB2__8['2day_mode'] = YB2__8.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB2__8['1day_mode'] = YB2__8.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

YB2__8['day_mode'] = YB2__8.iloc[:,20:28].mode(axis=1).dropna(axis=1)

In [60]:
YB2__9['2day_mode'] = YB2__9.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB2__9['1day_mode'] = YB2__9.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

YB2__9['day_mode'] = YB2__9.iloc[:, 20:28].mode(axis=1).dropna(axis=1)

In [61]:
YB2__10['2day_mode'] = YB2__10.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB2__10['1day_mode'] = YB2__10.iloc[:, 12:20].mode(axis=1).dropna(axis=1)

YB2__10['day_mode'] = YB2__10.iloc[:, 20:28].mode(axis=1).dropna(axis=1)

In [62]:
YB2__11['2day_mode'] = YB2__11.iloc[:, 6:12].mode(axis=1).dropna(axis=1)

YB2__11['1day_mode'] = YB2__11.iloc[:,12:20].mode(axis=1).dropna(axis=1)

YB2__11['day_mode'] = YB2__11.iloc[:, 20:28].mode(axis=1).dropna(axis=1)

In [63]:
SYB2__11=YB2__11.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2__10=YB2__10.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2__9=YB2__9.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2__8=YB2__8.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2__7=YB2__7.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2__6=YB2__6.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2__5=YB2__5.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2__4=YB2__4.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2__3=YB2__3.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2__2=YB2__2.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2__1=YB2__1.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)

In [64]:
def cba_1(a):
    k = SYB2__1.iloc[0+637*a:637+637*a,:]
    return k

u_u = []
for i in range(2):
    u_u.append(cba_1(i))
    
RD2__1=pd.merge(u_u[0], u_u[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2__1.rename(columns = {'2day_mode_x' : '2day_mode_PTY', '1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD2__1.rename(columns = {'2day_mode_y' : '2day_mode_SKY', '1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA2__1= RD2__1.drop(['variable_x','variable_y'] , axis=1)
RDA2__1['date']=20110709

In [65]:
def cba_2(a):
    k = SYB2__2.iloc[0+637*a:637+637*a,:]
    return k

u_u2 = []
for i in range(2):
    u_u2.append(cba_2(i))
    
RD2__2=pd.merge(u_u2[0], u_u2[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2__2.rename(columns = {'2day_mode_x' : '2day_mode_PTY', '1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD2__2.rename(columns = {'2day_mode_y' : '2day_mode_SKY', '1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA2__2= RD2__2.drop(['variable_x','variable_y'] , axis=1)
RDA2__2['date']=20110808

In [66]:
def cba_3(a):
    k = SYB2__3.iloc[0+637*a:637+637*a,:]
    return k

u_u3 = []
for i in range(2):
    u_u3.append(cba_3(i))
    
RD2__3=pd.merge(u_u3[0], u_u3[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2__3.rename(columns = {'2day_mode_x' : '2day_mode_PTY', '1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD2__3.rename(columns = {'2day_mode_y' : '2day_mode_SKY', '1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA2__3= RD2__3.drop(['variable_x','variable_y'] , axis=1)
RDA2__3['date']=20120917

In [67]:
def cba_4(a):
    k = SYB2__4.iloc[0+637*a:637+637*a,:]
    return k

u_u4 = []
for i in range(2):
    u_u4.append(cba_4(i))
    
RD2__4=pd.merge(u_u4[0], u_u4[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2__4.rename(columns = {'2day_mode_x' : '2day_mode_PTY', '1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD2__4.rename(columns = {'2day_mode_y' : '2day_mode_SKY', '1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA2__4= RD2__4.drop(['variable_x','variable_y'] , axis=1)
RDA2__4['date']=20140825

In [68]:
def cba_5(a):
    k = SYB2__5.iloc[0+637*a:637+637*a,:]
    return k

u_u5 = []
for i in range(2):
    u_u5.append(cba_5(i))
    
RD2__5=pd.merge(u_u5[0], u_u5[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2__5.rename(columns = {'2day_mode_x' : '2day_mode_PTY', '1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD2__5.rename(columns = {'2day_mode_y' : '2day_mode_SKY', '1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA2__5= RD2__5.drop(['variable_x','variable_y'] , axis=1)
RDA2__5['date']=20161005

In [69]:
def cba_6(a):
    k = SYB2__6.iloc[0+637*a:637+637*a,:]
    return k

u_u6 = []
for i in range(2):
    u_u6.append(cba_6(i))
    
RD2__6=pd.merge(u_u6[0], u_u6[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2__6.rename(columns = {'2day_mode_x' : '2day_mode_PTY', '1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD2__6.rename(columns = {'2day_mode_y' : '2day_mode_SKY', '1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA2__6= RD2__6.drop(['variable_x','variable_y'] , axis=1)
RDA2__6['date']=20180703

In [70]:
def cba_7(a):
    k = SYB2__7.iloc[0+637*a:637+637*a,:]
    return k

u_u7 = []
for i in range(2):
    u_u7.append(cba_7(i))
    
RD2__7=pd.merge(u_u7[0], u_u7[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2__7.rename(columns = {'2day_mode_x' : '2day_mode_PTY', '1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD2__7.rename(columns = {'2day_mode_y' : '2day_mode_SKY', '1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA2__7= RD2__7.drop(['variable_x','variable_y'] , axis=1)
RDA2__7['date']=20180826

In [71]:
def cba_8(a):
    k = SYB2__8.iloc[0+637*a:637+637*a,:]
    return k

u_u8 = []
for i in range(2):
    u_u8.append(cba_8(i))
    
RD2__8=pd.merge(u_u8[0], u_u8[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2__8.rename(columns = {'2day_mode_x' : '2day_mode_PTY', '1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD2__8.rename(columns = {'2day_mode_y' : '2day_mode_SKY', '1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA2__8= RD2__8.drop(['variable_x','variable_y'] , axis=1)
RDA2__8['date']=20181006

In [72]:
def cba_9(a):
    k = SYB2__9.iloc[0+637*a:637+637*a,:]
    return k

u_u9 = []
for i in range(2):
    u_u9.append(cba_9(i))
    
RD2__9=pd.merge(u_u9[0], u_u9[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2__9.rename(columns = {'2day_mode_x' : '2day_mode_PTY', '1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD2__9.rename(columns = {'2day_mode_y' : '2day_mode_SKY', '1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA2__9= RD2__9.drop(['variable_x','variable_y'] , axis=1)
RDA2__9['date']=20190720

In [73]:
def cba_10(a):
    k = SYB2__10.iloc[0+637*a:637+637*a,:]
    return k

u_u10 = []
for i in range(2):
    u_u10.append(cba_10(i))
    
RD2__10=pd.merge(u_u10[0], u_u10[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2__10.rename(columns = {'2day_mode_x' : '2day_mode_PTY', '1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD2__10.rename(columns = {'2day_mode_y' : '2day_mode_SKY', '1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA2__10= RD2__10.drop(['variable_x','variable_y'] , axis=1)
RDA2__10['date']=20191002

In [74]:
def cba_11(a):
    k = SYB2__11.iloc[0+637*a:637+637*a,:]
    return k

u_u11 = []
for i in range(2):
    u_u11.append(cba_11(i))
    
RD2__11=pd.merge(u_u11[0], u_u11[1], on = ['sd', 'sgg', 'umd', 'x', 'y'], how='left')
RD2__11.rename(columns = {'2day_mode_x' : '2day_mode_PTY', '1day_mode_x':'1day_mode_PTY',  'day_mode_x':'day_mode_PTY'}, inplace = True)
RD2__11.rename(columns = {'2day_mode_y' : '2day_mode_SKY', '1day_mode_y':'1day_mode_SKY',  'day_mode_y':'day_mode_SKY'}, inplace = True)

RDA2__11= RD2__11.drop(['variable_x','variable_y'] , axis=1)
RDA2__11['date']=20191003

In [75]:
RDA2__1

,sd,sgg,umd,x,y,2day_mode_PTY,1day_mode_PTY,day_mode_PTY,2day_mode_SKY,1day_mode_SKY,day_mode_SKY,date
0,경상북도,포항시남구,구룡포읍,105,94,0.0,0.0,0.0,4.0,4.0,4.0,20110709
1,경상북도,포항시남구,연일읍,102,94,0.0,0.0,0.0,4.0,4.0,4.0,20110709
2,경상북도,포항시남구,오천읍,103,93,0.0,0.0,0.0,4.0,4.0,4.0,20110709
3,경상북도,포항시남구,대송면,102,93,0.0,0.0,0.0,4.0,4.0,4.0,20110709
4,경상북도,포항시남구,동해면2,104,94,0.0,0.0,0.0,4.0,4.0,4.0,20110709
...,...,...,...,...,...,...,...,...,...,...,...,...
632,경상남도,합천군,쌍백면,81,81,0.0,0.0,1.0,4.0,4.0,4.0,20110709
633,경상남도,합천군,삼가면,81,80,0.0,0.0,1.0,4.0,4.0,4.0,20110709
634,경상남도,합천군,가회면,79,81,0.0,0.0,1.0,4.0,4.0,4.0,20110709
635,경상남도,합천군,대병면,79,83,0.0,0.0,1.0,4.0,4.0,4.0,20110709
636,경상남도,합천군,용주면,81,83,0.0,0.0,1.0,4.0,4.0,4.0,20110709

In [76]:
RRDDAA_1=pd.concat([RDA2__11,RDA2__10,RDA2__9,RDA2__8,RDA2__7,RDA2__6,RDA2__5,RDA2__4,RDA2__3,RDA2__2,RDA2__1])

In [77]:
weather_1=pd.merge(RRDDAA, RRDDAA_1, on=['sd', 'sgg', 'umd', 'x', 'y', 'date'], how='inner')

In [78]:
weather_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7007 entries, 0 to 7006
Data columns (total 66 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   sd             7007 non-null   object
 1   sgg            7007 non-null   object
 2   umd            7007 non-null   object
 3   x              7007 non-null   int64
 4   y              7007 non-null   int64
 5   2day_mean_T3H  7007 non-null   object
 6   2day_max_T3H   7007 non-null   float64
 7   2day_min_T3H   7007 non-null   float64
 8   1day_mean_T3H  7007 non-null   object
 9   1day_max_T3H   7007 non-null   float64
 10  1day_min_T3H   7007 non-null   float64
 11  day_mean_T3H   7007 non-null   object
 12  day_max_T3H    7007 non-null   float64
 13  day_min_T3H    7007 non-null   float64
 14  2day_mean_REH  7007 non-null   object
 15  2day_max_REH   7007 non-null   float64
 16  2day_min_REH   7007 non-null   float64
 17  1day_mean_REH  7007 non-null   object
 18  1day_max_REH   7007 non-null   float64
 19  1day_min_REH   7007 non-null   float64
 20  day_mean_REH   7007 non-null   object
 21  day_max_REH    7007 non-null   float64
 22  day_min_REH    7007 non-null   float64
 23  2day_mean_WSD  7007 non-null   object
 24  2day_max_WSD   7007 non-null   float64
 25  2day_min_WSD   7007 non-null   float64
 26  1day_mean_WSD  7007 non-null   object
 27  1day_max_WSD   7007 non-null   float64
 28  1day_min_WSD   7007 non-null   float64
 29  day_mean_WSD   7007 non-null   object
 30  day_max_WSD    7007 non-null   float64
 31  day_min_WSD    7007 non-null   float64
 32  2day_mean_VEC  7007 non-null   object
 33  2day_max_VEC   7007 non-null   float64
 34  2day_min_VEC   7007 non-null   float64
 35  1day_mean_VEC  7007 non-null   object
 36  1day_max_VEC   7007 non-null   float64
 37  1day_min_VEC   7007 non-null   float64
 38  day_mean_VEC   7007 non-null   object
 39  day_max_VEC    7007 non-null   float64
 40  day_min_VEC    7007 non-null   float64
 41  2day_mean_POP  7007 non-null   object
 42  2day_max_POP   7007 non-null   float64
 43  2day_min_POP   7007 non-null   float64
 44  1day_mean_POP  7007 non-null   object
 45  1day_max_POP   7007 non-null   float64
 46  1day_min_POP   7007 non-null   float64
 47  day_mean_POP   7007 non-null   object
 48  day_max_POP    7007 non-null   float64
 49  day_min_POP    7007 non-null   float64
 50  2day_mean_WAV  7007 non-null   object
 51  2day_max_WAV   7007 non-null   float64
 52  2day_min_WAV   7007 non-null   float64
 53  1day_mean_WAV  7007 non-null   object
 54  1day_max_WAV   7007 non-null   float64
 55  1day_min_WAV   7007 non-null   float64
 56  day_mean_WAV   7007 non-null   object
 57  day_max_WAV    7007 non-null   float64
 58  day_min_WAV    7007 non-null   float64
 59  date           7007 non-null   int64
 60  2day_mode_PTY  7007 non-null   float64
 61  1day_mode_PTY  7007 non-null   float64
 62  day_mode_PTY   7007 non-null   float64
 63  2day_mode_SKY  7007 non-null   float64
 64  1day_mode_SKY  7007 non-null   float64
 65  day_mode_SKY   7007 non-null   float64
dtypes: float64(42), int64(3), object(21)
memory usage: 3.6+ MB

## 강수량 뽑기

In [79]:
z__1 = [8] # 8:강수량 # 6,7 -> PTY, SKY # 10: 최고기온 11: 최저기온 12:SKY2  13:적설량
t__1 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__1.append(abc(i, j, n))

u__1 = []
for i in t__1:
    u__1.append(ac2_1(i))
    
u__1=np.reshape(u__1, (637,23))

col2_name1 = yb2_1.columns

ybs2_1 = pd.DataFrame(u__1, columns=col2_name1)

p__1=[]
for i in range(1):
    a = ybs2_1.iloc[0+637*i:637+637*i,:]
    p__1.append(a)
    
pp__1=[]
for i in range(1):
    a=p__1[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__1.append(df)

YB2___1=pd.concat(pp__1)
YB2___1.rename(columns = {'2011070705' : 'variable'}, inplace = True)

In [80]:
t__2 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__2.append(abc(i, j, n))

u__2 = []
for i in t__2:
    u__2.append(ac2_2(i))
    
u__2=np.reshape(u__2, (637,23))

col2_name2 = yb2_2.columns

ybs2_2 = pd.DataFrame(u__2, columns=col2_name2)

p__2=[]
for i in range(1):
    a = ybs2_2.iloc[0+637*i:637+637*i,:]
    p__2.append(a)
    
pp__2=[]
for i in range(1):
    a=p__2[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__2.append(df)

YB2___2=pd.concat(pp__2)
YB2___2.rename(columns = {'2011080605' : 'variable'}, inplace = True)

In [81]:
t__3 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__3.append(abc(i, j, n))

u__3 = []
for i in t__3:
    u__3.append(ac2_3(i))
    
u__3=np.reshape(u__3, (637,23))

col2_name3 = yb2_3.columns

ybs2_3 = pd.DataFrame(u__3, columns=col2_name3)

p__3=[]
for i in range(1):
    a = ybs2_3.iloc[0+637*i:637+637*i,:]
    p__3.append(a)
    
pp__3=[]
for i in range(1):
    a=p__3[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__3.append(df)

YB2___3=pd.concat(pp__3)
YB2___3.rename(columns = {'2012091505' : 'variable'}, inplace = True)

In [82]:
t__4 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__4.append(abc(i, j, n))

u__4 = []
for i in t__4:
    u__4.append(ac2_4(i))
    
u__4=np.reshape(u__4, (637,23))

col2_name4 = yb2_4.columns

ybs2_4 = pd.DataFrame(u__4, columns=col2_name4)

p__4=[]
for i in range(1):
    a = ybs2_4.iloc[0+637*i:637+637*i,:]
    p__4.append(a)
    
pp__4=[]
for i in range(1):
    a=p__4[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__4.append(df)

YB2___4=pd.concat(pp__4)
YB2___4.rename(columns = {'2014082305' : 'variable'}, inplace = True)

In [83]:
t__5 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__5.append(abc(i, j, n))

u__5 = []
for i in t__5:
    u__5.append(ac2_5(i))
    
u__5=np.reshape(u__5, (637,23))

col2_name5 = yb2_5.columns

ybs2_5 = pd.DataFrame(u__5, columns=col2_name5)

p__5=[]
for i in range(1):
    a = ybs2_5.iloc[0+637*i:637+637*i,:]
    p__5.append(a)
    
pp__5=[]
for i in range(1):
    a=p__5[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__5.append(df)

YB2___5=pd.concat(pp__5)
YB2___5.rename(columns = {'2016100305' : 'variable'}, inplace = True)

In [84]:
t__6 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__6.append(abc(i, j, n))

u__6 = []
for i in t__6:
    u__6.append(ac2_6(i))
    
u__6=np.reshape(u__6, (637,23))

col2_name6 = yb2_6.columns

ybs2_6 = pd.DataFrame(u__6, columns=col2_name6)

p__6=[]
for i in range(1):
    a = ybs2_6.iloc[0+637*i:637+637*i,:]
    p__6.append(a)
    
pp__6=[]
for i in range(1):
    a=p__6[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__6.append(df)

YB2___6=pd.concat(pp__6)
YB2___6.rename(columns = {'2018070105' : 'variable'}, inplace = True)

In [85]:
t__7 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__7.append(abc(i, j, n))

u__7 = []
for i in t__7:
    u__7.append(ac2_7(i))
    
u__7=np.reshape(u__7, (637,23))

col2_name7 = yb2_7.columns

ybs2_7 = pd.DataFrame(u__7, columns=col2_name7)

p__7=[]
for i in range(1):
    a = ybs2_7.iloc[0+637*i:637+637*i,:]
    p__7.append(a)
    
pp__7=[]
for i in range(1):
    a=p__7[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__7.append(df)

YB2___7=pd.concat(pp__7)
YB2___7.rename(columns = {'2018082405' : 'variable'}, inplace = True)

In [86]:
t__8 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__8.append(abc(i, j, n))

u__8 = []
for i in t__8:
    u__8.append(ac2_8(i))
    
u__8=np.reshape(u__8, (637,23))

col2_name8 = yb2_8.columns

ybs2_8 = pd.DataFrame(u__8, columns=col2_name8)

p__8=[]
for i in range(1):
    a = ybs2_8.iloc[0+637*i:637+637*i,:]
    p__8.append(a)
    
pp__8=[]
for i in range(1):
    a=p__8[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__8.append(df)

YB2___8=pd.concat(pp__8)
YB2___8.rename(columns = {'2018100405' : 'variable'}, inplace = True)

In [87]:
t__9 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__9.append(abc(i, j, n))

u__9 = []
for i in t__9:
    u__9.append(ac2_9(i))
    
u__9=np.reshape(u__9, (637,23))

col2_name9 = yb2_9.columns

ybs2_9 = pd.DataFrame(u__9, columns=col2_name9)

p__9=[]
for i in range(1):
    a = ybs2_9.iloc[0+637*i:637+637*i,:]
    p__9.append(a)
    
pp__9=[]
for i in range(1):
    a=p__9[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__9.append(df)

YB2___9=pd.concat(pp__9)
YB2___9.rename(columns = {'2019071805' : 'variable'}, inplace = True)

In [88]:
t__10 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__10.append(abc(i, j, n))

u__10 = []
for i in t__10:
    u__10.append(ac2_10(i))
    
u__10=np.reshape(u__10, (637,23))

col2_name10 = yb2_10.columns

ybs2_10 = pd.DataFrame(u__10, columns=col2_name10)

p__10=[]
for i in range(1):
    a = ybs2_10.iloc[0+637*i:637+637*i,:]
    p__10.append(a)
    
pp__10=[]
for i in range(1):
    a=p__10[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__10.append(df)

YB2___10=pd.concat(pp__10)
YB2___10.rename(columns = {'2019093005' : 'variable'}, inplace = True)

In [89]:
t__11 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__11.append(abc(i, j, n))

u__11 = []
for i in t__11:
    u__11.append(ac2_11(i))
    
u__11=np.reshape(u__11, (637,23))

col2_name11 = yb2_11.columns

ybs2_11 = pd.DataFrame(u__11, columns=col2_name11)

p__11=[]
for i in range(1):
    a = ybs2_11.iloc[0+637*i:637+637*i,:]
    p__11.append(a)
    
pp__11=[]
for i in range(1):
    a=p__11[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__11.append(df)

YB2___11=pd.concat(pp__11)
YB2___11.rename(columns = {'2019100105' : 'variable'}, inplace = True)

In [90]:
YB2___1['2day_sum'] = (YB2___1['4hr']  +YB2___1['7hr']  + YB2___1['10hr']  + YB2___1['13hr'] ) 
YB2___1['2day_max'] = YB2___1.iloc[:, 6:10].max(axis=1)
YB2___1['1day_sum'] = (YB2___1['16hr']  + YB2___1['19hr']  + YB2___1['22hr']  + YB2___1['25hr'] ) 
YB2___1['1day_max'] = YB2___1.iloc[:, 10:14].max(axis=1)
YB2___1['day_sum'] = (YB2___1['28hr']  + YB2___1['31hr']  + YB2___1['34hr'] ) 
YB2___1['day_max'] = YB2___1.iloc[:, 14:17].max(axis=1)
YB2___1['date']= 20110709

In [91]:
YB2___2['2day_sum'] = (YB2___2['4hr']  +YB2___2['7hr']  + YB2___2['10hr']  + YB2___2['13hr'] ) 
YB2___2['2day_max'] = YB2___2.iloc[:, 6:10].max(axis=1)
YB2___2['1day_sum'] = (YB2___2['16hr']  + YB2___2['19hr']  + YB2___2['22hr']  + YB2___2['25hr'] ) 
YB2___2['1day_max'] = YB2___2.iloc[:, 10:14].max(axis=1)
YB2___2['day_sum'] = (YB2___2['28hr']  + YB2___2['31hr']  + YB2___2['34hr'] ) 
YB2___2['day_max'] = YB2___2.iloc[:, 14:17].max(axis=1)
YB2___2['date']=20110808

In [92]:
YB2___3['2day_sum'] = (YB2___3['4hr']  +YB2___3['7hr']  + YB2___3['10hr']  + YB2___3['13hr'] ) 
YB2___3['2day_max'] = YB2___3.iloc[:, 6:10].max(axis=1)
YB2___3['1day_sum'] = (YB2___3['16hr']  + YB2___3['19hr']  + YB2___3['22hr']  + YB2___3['25hr'] ) 
YB2___3['1day_max'] = YB2___3.iloc[:, 10:14].max(axis=1)
YB2___3['day_sum'] = (YB2___3['28hr']  + YB2___3['31hr']  + YB2___3['34hr'] ) 
YB2___3['day_max'] = YB2___3.iloc[:, 14:17].max(axis=1)
YB2___3['date']=20120917

In [93]:
YB2___4['2day_sum'] = (YB2___4['4hr']  +YB2___4['7hr']  + YB2___4['10hr']  + YB2___4['13hr'] ) 
YB2___4['2day_max'] = YB2___4.iloc[:, 6:10].max(axis=1)
YB2___4['1day_sum'] = (YB2___4['16hr']  + YB2___4['19hr']  + YB2___4['22hr']  + YB2___4['25hr'] ) 
YB2___4['1day_max'] = YB2___4.iloc[:, 10:14].max(axis=1)
YB2___4['day_sum'] = (YB2___4['28hr']  + YB2___4['31hr']  + YB2___4['34hr'] ) 
YB2___4['day_max'] = YB2___4.iloc[:, 14:17].max(axis=1)
YB2___4['date']=20140825

In [94]:
YB2___5['2day_sum'] = (YB2___5['4hr']  +YB2___5['7hr']  + YB2___5['10hr']  + YB2___5['13hr'] ) 
YB2___5['2day_max'] = YB2___5.iloc[:, 6:10].max(axis=1)
YB2___5['1day_sum'] = (YB2___5['16hr']  + YB2___5['19hr']  + YB2___5['22hr']  + YB2___5['25hr'] ) 
YB2___5['1day_max'] = YB2___5.iloc[:, 10:14].max(axis=1)
YB2___5['day_sum'] = (YB2___5['28hr']  + YB2___5['31hr']  + YB2___5['34hr'] ) 
YB2___5['day_max'] = YB2___5.iloc[:, 14:17].max(axis=1)
YB2___5['date']=20161005

In [95]:
YB2___6['2day_sum'] = (YB2___6['4hr']  +YB2___6['7hr']  + YB2___6['10hr']  + YB2___6['13hr'] ) 
YB2___6['2day_max'] = YB2___6.iloc[:, 6:10].max(axis=1)
YB2___6['1day_sum'] = (YB2___6['16hr']  + YB2___6['19hr']  + YB2___6['22hr']  + YB2___6['25hr'] ) 
YB2___6['1day_max'] = YB2___6.iloc[:, 10:14].max(axis=1)
YB2___6['day_sum'] = (YB2___6['28hr']  + YB2___6['31hr']  + YB2___6['34hr'] ) 
YB2___6['day_max'] = YB2___6.iloc[:, 14:17].max(axis=1)
YB2___6['date']=20180703

In [96]:
YB2___7['2day_sum'] = (YB2___7['4hr']  +YB2___7['7hr']  + YB2___7['10hr']  + YB2___7['13hr'] ) 
YB2___7['2day_max'] = YB2___7.iloc[:, 6:10].max(axis=1)
YB2___7['1day_sum'] = (YB2___7['16hr']  + YB2___7['19hr']  + YB2___7['22hr']  + YB2___7['25hr'] ) 
YB2___7['1day_max'] = YB2___7.iloc[:, 10:14].max(axis=1)
YB2___7['day_sum'] = (YB2___7['28hr']  + YB2___7['31hr']  + YB2___7['34hr'] ) 
YB2___7['day_max'] = YB2___7.iloc[:, 14:17].max(axis=1)
YB2___7['date']=20180826

In [97]:
YB2___8['2day_sum'] = (YB2___8['4hr']  +YB2___8['7hr']  + YB2___8['10hr']  + YB2___8['13hr'] ) 
YB2___8['2day_max'] = YB2___8.iloc[:, 6:10].max(axis=1)
YB2___8['1day_sum'] = (YB2___8['16hr']  + YB2___8['19hr']  + YB2___8['22hr']  + YB2___8['25hr'] ) 
YB2___8['1day_max'] = YB2___8.iloc[:, 10:14].max(axis=1)
YB2___8['day_sum'] = (YB2___8['28hr']  + YB2___8['31hr']  + YB2___8['34hr'] ) 
YB2___8['day_max'] = YB2___8.iloc[:, 14:17].max(axis=1)
YB2___8['date']=20181006

In [98]:
YB2___9['2day_sum'] = (YB2___9['4hr']  +YB2___9['7hr']  + YB2___9['10hr']  + YB2___9['13hr'] ) 
YB2___9['2day_max'] = YB2___9.iloc[:, 6:10].max(axis=1)
YB2___9['1day_sum'] = (YB2___9['16hr']  + YB2___9['19hr']  + YB2___9['22hr']  + YB2___9['25hr'] ) 
YB2___9['1day_max'] = YB2___9.iloc[:, 10:14].max(axis=1)
YB2___9['day_sum'] = (YB2___9['28hr']  + YB2___9['31hr']  + YB2___9['34hr'] ) 
YB2___9['day_max'] = YB2___9.iloc[:, 14:17].max(axis=1)
YB2___9['date']=20190720

In [99]:
YB2___10['2day_sum'] = (YB2___10['4hr']  +YB2___10['7hr']  + YB2___10['10hr']  + YB2___10['13hr'] ) 
YB2___10['2day_max'] = YB2___10.iloc[:, 6:10].max(axis=1)
YB2___10['1day_sum'] = (YB2___10['16hr']  + YB2___10['19hr']  + YB2___10['22hr']  + YB2___10['25hr'] ) 
YB2___10['1day_max'] = YB2___10.iloc[:, 10:14].max(axis=1)
YB2___10['day_sum'] = (YB2___10['28hr']  + YB2___10['31hr']  + YB2___10['34hr'] ) 
YB2___10['day_max'] = YB2___10.iloc[:, 14:17].max(axis=1)
YB2___10['date']=20191002

In [100]:
YB2___11['2day_sum'] = (YB2___11['4hr']  +YB2___11['7hr']  + YB2___11['10hr']  + YB2___11['13hr'] ) 
YB2___11['2day_max'] = YB2___11.iloc[:, 6:10].max(axis=1)
YB2___11['1day_sum'] = (YB2___11['16hr']  + YB2___11['19hr']  + YB2___11['22hr']  + YB2___11['25hr'] ) 
YB2___11['1day_max'] = YB2___11.iloc[:, 10:14].max(axis=1)
YB2___11['day_sum'] = (YB2___11['28hr']  + YB2___11['31hr']  + YB2___11['34hr'] ) 
YB2___11['day_max'] = YB2___11.iloc[:, 14:17].max(axis=1)
YB2___11['date']=20191003

In [101]:
SYB2___11=YB2___11.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2___10=YB2___10.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2___9=YB2___9.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2___8=YB2___8.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2___7=YB2___7.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2___6=YB2___6.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2___5=YB2___5.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2___4=YB2___4.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2___3=YB2___3.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2___2=YB2___2.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)
SYB2___1=YB2___1.drop(['4hr','7hr','10hr','13hr','16hr','19hr','22hr','25hr','28hr','31hr','34hr','37hr','40hr','43hr','46hr','49hr','52hr','55hr','58hr','61hr','64hr','67hr'],axis=1)

In [102]:
RAIN=pd.concat([SYB2___11,SYB2___10,SYB2___9,SYB2___8,SYB2___7,SYB2___6,SYB2___5,SYB2___4,SYB2___3,SYB2___2,SYB2___1])

In [103]:
RAIN.rename(columns = {'2day_sum' : '2day_sum_rain', '1day_sum':'1day_sum_rain',  'day_sum':'day_sum_rain', '2day_max' : '2day_max_rain', '1day_max':'1day_max_rain',  'day_max':'day_max_rain',}, inplace = True)

In [104]:
weather__2=pd.merge(weather_1, RAIN, on=['sd', 'sgg', 'umd', 'x', 'y', 'date'], how= 'inner')

In [105]:
weather__2

,sd,sgg,umd,x,y,2day_mean_T3H,2day_max_T3H,2day_min_T3H,1day_mean_T3H,1day_max_T3H,...,2day_mode_SKY,1day_mode_SKY,day_mode_SKY,variable,2day_sum_rain,2day_max_rain,1day_sum_rain,1day_max_rain,day_sum_rain,day_max_rain
0,경상북도,포항시남구,구룡포읍,105,94,22.5,24.0,21.0,22.0,24.0,...,4.0,4.0,4.0,R06,20.0,10.0,220.0,70.0,160.0,70.0
1,경상북도,포항시남구,연일읍,102,94,23.666667,25.0,22.0,22.5,24.0,...,4.0,4.0,4.0,R06,20.0,10.0,220.0,70.0,160.0,70.0
2,경상북도,포항시남구,오천읍,103,93,23.666667,25.0,22.0,22.625,24.0,...,4.0,4.0,4.0,R06,20.0,10.0,220.0,70.0,160.0,70.0
3,경상북도,포항시남구,대송면,102,93,23.5,25.0,22.0,22.375,24.0,...,4.0,4.0,4.0,R06,20.0,10.0,220.0,70.0,160.0,70.0
4,경상북도,포항시남구,동해면2,104,94,23.5,25.0,22.0,22.5,24.0,...,4.0,4.0,4.0,R06,20.0,10.0,220.0,70.0,160.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7002,경상남도,합천군,쌍백면,81,81,25.75,27.9,22.9,25.9375,28.0,...,4.0,4.0,4.0,R06,NaN,NaN,NaN,NaN,NaN,NaN
7003,경상남도,합천군,삼가면,81,80,25.833333,28.0,23.0,26.0,28.0,...,4.0,4.0,4.0,R06,NaN,NaN,NaN,NaN,NaN,NaN
7004,경상남도,합천군,가회면,79,81,25.5,27.5,22.5,25.6875,28.1,...,4.0,4.0,4.0,R06,NaN,NaN,NaN,NaN,NaN,NaN
7005,경상남도,합천군,대병면,79,83,25.066667,27.1,22.0,25.15,28.1,...,4.0,4.0,4.0,R06,NaN,NaN,NaN,NaN,NaN,NaN
7006,경상남도,합천군,용주면,81,83,26.2,28.3,23.2,26.4375,29.1,...,4.0,4.0,4.0,R06,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
gc2_1=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20110707.csv')
gc2_1.rename(columns = {'20110707' : 'variable'}, inplace = True)


#좌표 변환 함수#
def abc(a, b, c):
    k= (int(a) +149*(int(b)-1)-1 ) + (37697*c)
    return k


def ac2_1(a):
    k = gc2_1.iloc[a:a+1,:]
    return k



z__1 = [8] # 8:강수량 # 6,7 -> PTY, SKY # 10: 최고기온 11: 최저기온 12:SKY2  13:적설량
t__1 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__1.append(abc(i, j, n))

u__1 = []
for i in t__1:
    u__1.append(ac2_1(i))
    
u__1=np.reshape(u__1, (637,25))

col2_name1 = gc2_1.columns

gcs2_1 = pd.DataFrame(u__1, columns=col2_name1)

p__1=[]
for i in range(1):
    a = gcs2_1.iloc[0+637*i:637+637*i,:]
    p__1.append(a)
    
pp__1=[]
for i in range(1):
    a=p__1[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__1.append(df)

gc2__1=pd.concat(pp__1)
gc2__1.rename(columns = {'20110707' : 'variable'}, inplace = True)

In [108]:
gc2_2=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20110708.csv')
gc2_2.rename(columns = {'20110708' : 'variable'}, inplace = True)

def ac2_2(a):
    k = gc2_2.iloc[a:a+1,:]
    return k




t__2 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__2.append(abc(i, j, n))

u__2 = []
for i in t__2:
    u__2.append(ac2_2(i))
    
u__2=np.reshape(u__2, (637,25))

col2_name2 = gc2_2.columns

gcs2_2 = pd.DataFrame(u__2, columns=col2_name2)

p__2=[]
for i in range(1):
    a = gcs2_2.iloc[0+637*i:637+637*i,:]
    p__2.append(a)
    
pp__2=[]
for i in range(1):
    a=p__2[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__2.append(df)

gc2__2=pd.concat(pp__2)
gc2__2.rename(columns = {'20110708' : 'variable'}, inplace = True)

In [109]:
gc2_3=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20110709.csv')
gc2_3.rename(columns = {'20110709' : 'variable'}, inplace = True)



def ac2_3(a):
    k = gc2_3.iloc[a:a+1,:]
    return k





t__3 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__3.append(abc(i, j, n))

u__3 = []
for i in t__3:
    u__3.append(ac2_3(i))
    
u__3=np.reshape(u__3, (637,25))

col2_name3 = gc2_3.columns

gcs2_3 = pd.DataFrame(u__3, columns=col2_name3)

p__3=[]
for i in range(1):
    a = gcs2_3.iloc[0+637*i:637+637*i,:]
    p__3.append(a)
    
pp__3=[]
for i in range(1):
    a=p__3[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__3.append(df)

gc2__3=pd.concat(pp__3)
gc2__3.rename(columns = {'20110709' : 'variable'}, inplace = True)

In [110]:
gc2_4=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20110806.csv')
gc2_4.rename(columns = {'20110806' : 'variable'}, inplace = True)




def ac2_4(a):
    k = gc2_4.iloc[a:a+1,:]
    return k



t__4 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__4.append(abc(i, j, n))

u__4 = []
for i in t__4:
    u__4.append(ac2_4(i))
    
u__4=np.reshape(u__4, (637,25))

col2_name4 = gc2_4.columns

gcs2_4 = pd.DataFrame(u__4, columns=col2_name4)

p__4=[]
for i in range(1):
    a = gcs2_4.iloc[0+637*i:637+637*i,:]
    p__4.append(a)
    
pp__4=[]
for i in range(1):
    a=p__4[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__4.append(df)

gc2__4=pd.concat(pp__4)
gc2__4.rename(columns = {'20110806' : 'variable'}, inplace = True)

In [111]:
gc2_5=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20110807.csv')
gc2_5.rename(columns = {'20110807' : 'variable'}, inplace = True)

def ac2_5(a):
    k = gc2_5.iloc[a:a+1,:]
    return k



t__5 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__5.append(abc(i, j, n))

u__5 = []
for i in t__5:
    u__5.append(ac2_5(i))
    
u__5=np.reshape(u__5, (637,25))

col2_name5 = gc2_5.columns

gcs2_5 = pd.DataFrame(u__5, columns=col2_name5)

p__5=[]
for i in range(1):
    a = gcs2_5.iloc[0+637*i:637+637*i,:]
    p__5.append(a)
    
pp__5=[]
for i in range(1):
    a=p__5[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__5.append(df)

gc2__5=pd.concat(pp__5)
gc2__5.rename(columns = {'20110807' : 'variable'}, inplace = True)

In [112]:
gc2_6=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20110808.csv')
gc2_6.rename(columns = {'20110808' : 'variable'}, inplace = True)



def ac2_6(a):
    k = gc2_6.iloc[a:a+1,:]
    return k



t__6 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__6.append(abc(i, j, n))

u__6 = []
for i in t__6:
    u__6.append(ac2_6(i))
    
u__6=np.reshape(u__6, (637,25))

col2_name6 = gc2_6.columns

gcs2_6 = pd.DataFrame(u__6, columns=col2_name6)

p__6=[]
for i in range(1):
    a = gcs2_6.iloc[0+637*i:637+637*i,:]
    p__6.append(a)
    
pp__6=[]
for i in range(1):
    a=p__6[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__6.append(df)

gc2__6=pd.concat(pp__6)
gc2__6.rename(columns = {'20110808' : 'variable'}, inplace = True)

In [113]:
gc2_7=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20120915.csv')
gc2_7.rename(columns = {'20120915' : 'variable'}, inplace = True)



def ac2_7(a):
    k = gc2_7.iloc[a:a+1,:]
    return k



t__7 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__7.append(abc(i, j, n))

u__7 = []
for i in t__7:
    u__7.append(ac2_7(i))
    
u__7=np.reshape(u__7, (637,25))

col2_name7 = gc2_7.columns

gcs2_7 = pd.DataFrame(u__7, columns=col2_name7)

p__7=[]
for i in range(1):
    a = gcs2_7.iloc[0+637*i:637+637*i,:]
    p__7.append(a)
    
pp__7=[]
for i in range(1):
    a=p__7[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__7.append(df)

gc2__7=pd.concat(pp__7)
gc2__7.rename(columns = {'20120915' : 'variable'}, inplace = True)

In [114]:
gc2_8=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20120916.csv')
gc2_8.rename(columns = {'20120916' : 'variable'}, inplace = True)



def ac2_8(a):
    k = gc2_8.iloc[a:a+1,:]
    return k



t__8 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__8.append(abc(i, j, n))

u__8 = []
for i in t__8:
    u__8.append(ac2_8(i))
    
u__8=np.reshape(u__8, (637,25))

col2_name8 = gc2_8.columns

gcs2_8 = pd.DataFrame(u__8, columns=col2_name8)

p__8=[]
for i in range(1):
    a = gcs2_8.iloc[0+637*i:637+637*i,:]
    p__8.append(a)
    
pp__8=[]
for i in range(1):
    a=p__8[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__8.append(df)

gc2__8=pd.concat(pp__8)
gc2__8.rename(columns = {'20120916' : 'variable'}, inplace = True)

In [115]:
gc2_9=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20120917.csv')
gc2_9.rename(columns = {'20120917' : 'variable'}, inplace = True)



def ac2_9(a):
    k = gc2_9.iloc[a:a+1,:]
    return k



t__9 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__9.append(abc(i, j, n))

u__9 = []
for i in t__9:
    u__9.append(ac2_9(i))
    
u__9=np.reshape(u__9, (637,25))

col2_name9 = gc2_9.columns

gcs2_9 = pd.DataFrame(u__9, columns=col2_name9)

p__9=[]
for i in range(1):
    a = gcs2_9.iloc[0+637*i:637+637*i,:]
    p__9.append(a)
    
pp__9=[]
for i in range(1):
    a=p__9[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__9.append(df)

gc2__9=pd.concat(pp__9)
gc2__9.rename(columns = {'20120917' : 'variable'}, inplace = True)

In [116]:
gc2_10=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20140823.csv')
gc2_10.rename(columns = {'20140823' : 'variable'}, inplace = True)


def ac2_10(a):
    k = gc2_10.iloc[a:a+1,:]
    return k



t__10 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__10.append(abc(i, j, n))

u__10 = []
for i in t__10:
    u__10.append(ac2_10(i))
    
u__10=np.reshape(u__10, (637,25))

col2_name10 = gc2_10.columns

gcs2_10 = pd.DataFrame(u__10, columns=col2_name10)

p__10=[]
for i in range(1):
    a = gcs2_10.iloc[0+637*i:637+637*i,:]
    p__10.append(a)
    
pp__10=[]
for i in range(1):
    a=p__10[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__10.append(df)

gc2__10=pd.concat(pp__10)
gc2__10.rename(columns = {'20140823' : 'variable'}, inplace = True)

In [117]:
gc2_11=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20140824.csv')
gc2_11.rename(columns = {'20140824' : 'variable'}, inplace = True)


def ac2_11(a):
    k = gc2_11.iloc[a:a+1,:]
    return k



t__11 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__11.append(abc(i, j, n))

u__11 = []
for i in t__11:
    u__11.append(ac2_11(i))
    
u__11=np.reshape(u__11, (637,25))

col2_name11 = gc2_11.columns

gcs2_11 = pd.DataFrame(u__11, columns=col2_name11)

p__11=[]
for i in range(1):
    a = gcs2_11.iloc[0+637*i:637+637*i,:]
    p__11.append(a)
    
pp__11=[]
for i in range(1):
    a=p__11[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__11.append(df)

gc2__11=pd.concat(pp__11)
gc2__11.rename(columns = {'20140824' : 'variable'}, inplace = True)

In [118]:
gc2_12=pd.read_csv(r'C:\Users\stat_17\Desktop\실황\ODAM_20140825.csv')
gc2_12.rename(columns = {'20140825' : 'variable'}, inplace = True)


def ac2_12(a):
    k = gc2_12.iloc[a:a+1,:]
    return k



t__12 =[]
for n in z__1:
    for i, j in zip(x, y):
        t__12.append(abc(i, j, n))

u__12 = []
for i in t__12:
    u__12.append(ac2_12(i))
    
u__12=np.reshape(u__12, (637,25))

col2_name12 = gc2_12.columns

gcs2_12 = pd.DataFrame(u__12, columns=col2_name12)

p__12=[]
for i in range(1):
    a = gcs2_12.iloc[0+637*i:637+637*i,:]
    p__12.append(a)
    
pp__12=[]
for i in range(1):
    a=p__12[i].reset_index(drop=True)
    df= jido.join(a, how='left')
    pp__12.append(df)

gc2__12=pd.concat(pp__12)
gc2__12.rename(columns = {'20140825' : 'variable'}, inplace = True)

In [119]:
gc2__1['4hr']=gc2__1['0h'] + gc2__1['1h']+gc2__1['2h']+ gc2__1['3h']+ gc2__1['4h']+gc2__1['5h']
gc2__1['7hr']=gc2__1['6h'] + gc2__1['7h'] + gc2__1['8h'] + gc2__1['9h'] + gc2__1['10h'] + gc2__1['11h']
gc2__1['10hr']=gc2__1['12h'] + gc2__1['13h'] + gc2__1['14h'] + gc2__1['15h'] + gc2__1['16h'] + gc2__1['17h']
gc2__1['13hr']=gc2__1['18h'] + gc2__1['19h'] + gc2__1['20h'] + gc2__1['21h'] + gc2__1['22h'] + gc2__1['23h']
gc2__1['2day_sum'] = gc2__1['4hr'] + gc2__1['7hr'] + gc2__1['10hr'] + gc2__1['13hr']
gc2__1['2day_max'] = gc2__1.iloc[:, 30:33].max(axis=1)
gc2__1['date']= 20110709

In [120]:
gc2__2['16hr']=gc2__2['0h'] + gc2__2['1h']+gc2__2['2h']+ gc2__2['3h']+ gc2__2['4h']+gc2__2['5h']
gc2__2['19hr']=gc2__2['6h'] + gc2__2['7h'] + gc2__2['8h'] + gc2__2['9h'] + gc2__2['10h'] + gc2__2['11h']
gc2__2['22hr']=gc2__2['12h'] + gc2__2['13h'] + gc2__2['14h'] + gc2__2['15h'] + gc2__2['16h'] + gc2__2['17h']
gc2__2['25hr']=gc2__2['18h'] + gc2__2['19h'] + gc2__2['20h'] + gc2__2['21h'] + gc2__2['22h'] + gc2__2['23h']
gc2__2['1day_sum'] = gc2__2['16hr'] + gc2__2['19hr'] + gc2__2['22hr'] + gc2__2['25hr']
gc2__2['1day_max'] = gc2__2.iloc[:, 30:33].max(axis=1)
gc2__2['date']= 20110709

In [121]:
gc2__3['28hr']=gc2__3['0h'] + gc2__3['1h']+gc2__3['2h']+ gc2__3['3h']+ gc2__3['4h']+gc2__3['5h']
gc2__3['31hr']=gc2__3['6h'] + gc2__3['7h'] + gc2__3['8h'] + gc2__3['9h'] + gc2__3['10h'] + gc2__3['11h']
gc2__3['34hr']=gc2__3['12h'] + gc2__3['13h'] + gc2__3['14h'] + gc2__3['15h'] + gc2__3['16h'] + gc2__3['17h']
gc2__3['day_sum'] = gc2__3['28hr'] + gc2__3['31hr'] + gc2__3['34hr'] 
gc2__3['day_max'] = gc2__3.iloc[:, 30:33].max(axis=1)
gc2__3['date']= 20110709

In [122]:
gc2__4['4hr']=gc2__4['0h'] + gc2__4['1h']+gc2__4['2h']+ gc2__4['3h']+ gc2__4['4h']+gc2__4['5h']
gc2__4['7hr']=gc2__4['6h'] + gc2__4['7h'] + gc2__4['8h'] + gc2__4['9h'] + gc2__4['10h'] + gc2__4['11h']
gc2__4['10hr']=gc2__4['12h'] + gc2__4['13h'] + gc2__4['14h'] + gc2__4['15h'] + gc2__4['16h'] + gc2__4['17h']
gc2__4['13hr']=gc2__4['18h'] + gc2__4['19h'] + gc2__4['20h'] + gc2__4['21h'] + gc2__4['22h'] + gc2__4['23h']
gc2__4['2day_sum'] = gc2__4['4hr'] + gc2__4['7hr'] + gc2__4['10hr'] + gc2__4['13hr']
gc2__4['2day_max'] = gc2__4.iloc[:, 30:33].max(axis=1)
gc2__4['date']= 20110808

In [123]:
gc2__5['16hr']=gc2__5['0h'] + gc2__5['1h']+gc2__5['2h']+ gc2__5['3h']+ gc2__5['4h']+gc2__5['5h']
gc2__5['19hr']=gc2__5['6h'] + gc2__5['7h'] + gc2__5['8h'] + gc2__5['9h'] + gc2__5['10h'] + gc2__5['11h']
gc2__5['22hr']=gc2__5['12h'] + gc2__5['13h'] + gc2__5['14h'] + gc2__5['15h'] + gc2__5['16h'] + gc2__5['17h']
gc2__5['25hr']=gc2__5['18h'] + gc2__5['19h'] + gc2__5['20h'] + gc2__5['21h'] + gc2__5['22h'] + gc2__5['23h']
gc2__5['1day_sum'] = gc2__5['16hr'] + gc2__5['19hr'] + gc2__5['22hr'] + gc2__5['25hr']
gc2__5['1day_max'] = gc2__5.iloc[:, 30:33].max(axis=1)
gc2__5['date']= 20110808

In [124]:
gc2__6['28hr']=gc2__6['0h'] + gc2__6['1h']+gc2__6['2h']+ gc2__6['3h']+ gc2__6['4h']+gc2__6['5h']
gc2__6['31hr']=gc2__6['6h'] + gc2__6['7h'] + gc2__6['8h'] + gc2__6['9h'] + gc2__6['10h'] + gc2__6['11h']
gc2__6['34hr']=gc2__6['12h'] + gc2__6['13h'] + gc2__6['14h'] + gc2__6['15h'] + gc2__6['16h'] + gc2__6['17h']
gc2__6['day_sum'] = gc2__6['28hr'] + gc2__6['31hr'] + gc2__6['34hr'] 
gc2__6['day_max'] = gc2__6.iloc[:, 30:33].max(axis=1)
gc2__6['date']= 20110808

In [125]:
gc2__7['4hr']=gc2__7['0h'] + gc2__7['1h']+gc2__7['2h']+ gc2__7['3h']+ gc2__7['4h']+gc2__7['5h']
gc2__7['7hr']=gc2__7['6h'] + gc2__7['7h'] + gc2__7['8h'] + gc2__7['9h'] + gc2__7['10h'] + gc2__7['11h']
gc2__7['10hr']=gc2__7['12h'] + gc2__7['13h'] + gc2__7['14h'] + gc2__7['15h'] + gc2__7['16h'] + gc2__7['17h']
gc2__7['13hr']=gc2__7['18h'] + gc2__7['19h'] + gc2__7['20h'] + gc2__7['21h'] + gc2__7['22h'] + gc2__7['23h']
gc2__7['2day_sum'] = gc2__7['4hr'] + gc2__7['7hr'] + gc2__7['10hr'] + gc2__7['13hr']
gc2__7['2day_max'] = gc2__7.iloc[:, 30:33].max(axis=1)
gc2__7['date']= 20120917

In [126]:
gc2__8['16hr']=gc2__8['0h'] + gc2__8['1h']+gc2__8['2h']+ gc2__8['3h']+ gc2__8['4h']+gc2__8['5h']
gc2__8['19hr']=gc2__8['6h'] + gc2__8['7h'] + gc2__8['8h'] + gc2__8['9h'] + gc2__8['10h'] + gc2__8['11h']
gc2__8['22hr']=gc2__8['12h'] + gc2__8['13h'] + gc2__8['14h'] + gc2__8['15h'] + gc2__8['16h'] + gc2__8['17h']
gc2__8['25hr']=gc2__8['18h'] + gc2__8['19h'] + gc2__8['20h'] + gc2__8['21h'] + gc2__8['22h'] + gc2__8['23h']
gc2__8['1day_sum'] = gc2__8['16hr'] + gc2__8['19hr'] + gc2__8['22hr'] + gc2__8['25hr']
gc2__8['1day_max'] = gc2__8.iloc[:, 30:33].max(axis=1)
gc2__8['date']= 20120917

In [127]:
gc2__9['28hr']=gc2__9['0h'] + gc2__9['1h']+gc2__9['2h']+ gc2__9['3h']+ gc2__9['4h']+gc2__9['5h']
gc2__9['31hr']=gc2__9['6h'] + gc2__9['7h'] + gc2__9['8h'] + gc2__9['9h'] + gc2__9['10h'] + gc2__9['11h']
gc2__9['34hr']=gc2__9['12h'] + gc2__9['13h'] + gc2__9['14h'] + gc2__9['15h'] + gc2__9['16h'] + gc2__9['17h']
gc2__9['day_sum'] = gc2__9['28hr'] + gc2__9['31hr'] + gc2__9['34hr'] 
gc2__9['day_max'] = gc2__9.iloc[:, 30:33].max(axis=1)
gc2__9['date']= 20120917

In [128]:
gc2__10['4hr']=gc2__10['0h'] + gc2__10['1h']+gc2__10['2h']+ gc2__10['3h']+ gc2__10['4h']+gc2__10['5h']
gc2__10['7hr']=gc2__10['6h'] + gc2__10['7h'] + gc2__10['8h'] + gc2__10['9h'] + gc2__10['10h'] + gc2__10['11h']
gc2__10['10hr']=gc2__10['12h'] + gc2__10['13h'] + gc2__10['14h'] + gc2__10['15h'] + gc2__10['16h'] + gc2__10['17h']
gc2__10['13hr']=gc2__10['18h'] + gc2__10['19h'] + gc2__10['20h'] + gc2__10['21h'] + gc2__10['22h'] + gc2__10['23h']
gc2__10['2day_sum'] = gc2__10['4hr'] + gc2__10['7hr'] + gc2__10['10hr'] + gc2__10['13hr']
gc2__10['2day_max'] = gc2__10.iloc[:, 30:33].max(axis=1)
gc2__10['date']= 20140825

In [129]:
gc2__11['16hr']=gc2__11['0h'] + gc2__11['1h']+gc2__11['2h']+ gc2__11['3h']+ gc2__11['4h']+gc2__11['5h']
gc2__11['19hr']=gc2__11['6h'] + gc2__11['7h'] + gc2__11['8h'] + gc2__11['9h'] + gc2__11['10h'] + gc2__11['11h']
gc2__11['22hr']=gc2__11['12h'] + gc2__11['13h'] + gc2__11['14h'] + gc2__11['15h'] + gc2__11['16h'] + gc2__11['17h']
gc2__11['25hr']=gc2__11['18h'] + gc2__11['19h'] + gc2__11['20h'] + gc2__11['21h'] + gc2__11['22h'] + gc2__11['23h']
gc2__11['1day_sum'] = gc2__11['16hr'] + gc2__11['19hr'] + gc2__11['22hr'] + gc2__11['25hr']
gc2__11['1day_max'] = gc2__11.iloc[:, 30:33].max(axis=1)
gc2__11['date']= 20140825

In [130]:
gc2__12['28hr']=gc2__12['0h'] + gc2__12['1h']+gc2__12['2h']+ gc2__12['3h']+ gc2__12['4h']+gc2__12['5h']
gc2__12['31hr']=gc2__12['6h'] + gc2__12['7h'] + gc2__12['8h'] + gc2__12['9h'] + gc2__12['10h'] + gc2__12['11h']
gc2__12['34hr']=gc2__12['12h'] + gc2__12['13h'] + gc2__12['14h'] + gc2__12['15h'] + gc2__12['16h'] + gc2__12['17h']
gc2__12['day_sum'] = gc2__12['28hr'] + gc2__12['31hr'] + gc2__12['34hr'] 
gc2__12['day_max'] = gc2__12.iloc[:, 30:33].max(axis=1)
gc2__12['date']= 20140825

In [131]:
dgc2__1=gc2__1.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__2=gc2__2.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__3=gc2__3.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__4=gc2__4.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__5=gc2__5.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__6=gc2__6.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__7=gc2__7.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__8=gc2__8.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__9=gc2__9.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__10=gc2__10.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__11=gc2__11.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)
dgc2__12=gc2__12.drop(['0h','1h','2h','3h','4h','5h','6h','7h','8h','9h','10h','11h','12h','13h','14h','15h','16h','17h','18h','19h','20h','21h','22h','23h'],axis=1)

In [132]:
listdata1= ['4hr','7hr','10hr','13hr']
listdata2=['16hr','19hr','22hr','25hr']
listdata3=['28hr','31hr','34hr']

In [133]:
for _, f in enumerate(listdata1):
    list = [(dgc2__1[f]<=0.1), (dgc2__1[f]>0.1)&(dgc2__1[f]<=1), (dgc2__1[f]>1)&(dgc2__1[f]<=5),(dgc2__1[f]>5)&(dgc2__1[f]<=10),(dgc2__1[f]>10)&(dgc2__1[f]<=20),(dgc2__1[f]>20)&(dgc2__1[f]<=40),(dgc2__1[f]>40)&(dgc2__1[f]<=70),(dgc2__1[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__1[f]=np.select(list, choicelist)

In [134]:
for _, f in enumerate(listdata2):
    list2 = [(dgc2__2[f]<=0.1), (dgc2__2[f]>0.1)&(dgc2__2[f]<=1), (dgc2__2[f]>1)&(dgc2__2[f]<=5),(dgc2__2[f]>5)&(dgc2__2[f]<=10),(dgc2__2[f]>10)&(dgc2__2[f]<=20),(dgc2__2[f]>20)&(dgc2__2[f]<=40),(dgc2__2[f]>40)&(dgc2__2[f]<=70),(dgc2__2[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__2[f]=np.select(list2, choicelist)

In [135]:
for _, f in enumerate(listdata3):
    list3 = [(dgc2__3[f]<=0.1), (dgc2__3[f]>0.1)&(dgc2__3[f]<=1), (dgc2__3[f]>1)&(dgc2__3[f]<=5),(dgc2__3[f]>5)&(dgc2__3[f]<=10),(dgc2__3[f]>10)&(dgc2__3[f]<=20),(dgc2__3[f]>20)&(dgc2__3[f]<=40),(dgc2__3[f]>40)&(dgc2__3[f]<=70),(dgc2__3[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__3[f]=np.select(list3, choicelist)

In [136]:
for _, f in enumerate(listdata1):
    list4 = [(dgc2__4[f]<=0.1), (dgc2__4[f]>0.1)&(dgc2__4[f]<=1), (dgc2__4[f]>1)&(dgc2__4[f]<=5),(dgc2__4[f]>5)&(dgc2__4[f]<=10),(dgc2__4[f]>10)&(dgc2__4[f]<=20),(dgc2__4[f]>20)&(dgc2__4[f]<=40),(dgc2__4[f]>40)&(dgc2__4[f]<=70),(dgc2__4[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__4[f]=np.select(list4, choicelist)

In [137]:
for _, f in enumerate(listdata2):
    list5 = [(dgc2__5[f]<=0.1), (dgc2__5[f]>0.1)&(dgc2__5[f]<=1), (dgc2__5[f]>1)&(dgc2__5[f]<=5),(dgc2__5[f]>5)&(dgc2__5[f]<=10),(dgc2__5[f]>10)&(dgc2__5[f]<=20),(dgc2__5[f]>20)&(dgc2__5[f]<=40),(dgc2__5[f]>40)&(dgc2__5[f]<=70),(dgc2__5[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__5[f]=np.select(list5, choicelist)

In [138]:
for _, f in enumerate(listdata3):
    list6 = [(dgc2__6[f]<=0.1), (dgc2__6[f]>0.1)&(dgc2__6[f]<=1), (dgc2__6[f]>1)&(dgc2__6[f]<=5),(dgc2__6[f]>5)&(dgc2__6[f]<=10),(dgc2__6[f]>10)&(dgc2__6[f]<=20),(dgc2__6[f]>20)&(dgc2__6[f]<=40),(dgc2__6[f]>40)&(dgc2__6[f]<=70),(dgc2__6[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__6[f]=np.select(list6, choicelist)

In [139]:
for _, f in enumerate(listdata1):
    list7 = [(dgc2__7[f]<=0.1), (dgc2__7[f]>0.1)&(dgc2__7[f]<=1), (dgc2__7[f]>1)&(dgc2__7[f]<=5),(dgc2__7[f]>5)&(dgc2__7[f]<=10),(dgc2__7[f]>10)&(dgc2__7[f]<=20),(dgc2__7[f]>20)&(dgc2__7[f]<=40),(dgc2__7[f]>40)&(dgc2__7[f]<=70),(dgc2__7[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__7[f]=np.select(list7, choicelist)

In [140]:
for _, f in enumerate(listdata2):
    list8 = [(dgc2__8[f]<=0.1), (dgc2__8[f]>0.1)&(dgc2__8[f]<=1), (dgc2__8[f]>1)&(dgc2__8[f]<=5),(dgc2__8[f]>5)&(dgc2__8[f]<=10),(dgc2__8[f]>10)&(dgc2__8[f]<=20),(dgc2__8[f]>20)&(dgc2__8[f]<=40),(dgc2__8[f]>40)&(dgc2__8[f]<=70),(dgc2__8[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__8[f]=np.select(list8, choicelist)

In [141]:
for _, f in enumerate(listdata3):
    list9 = [(dgc2__9[f]<=0.1), (dgc2__9[f]>0.1)&(dgc2__9[f]<=1), (dgc2__9[f]>1)&(dgc2__9[f]<=5),(dgc2__9[f]>5)&(dgc2__9[f]<=10),(dgc2__9[f]>10)&(dgc2__9[f]<=20),(dgc2__9[f]>20)&(dgc2__9[f]<=40),(dgc2__9[f]>40)&(dgc2__9[f]<=70),(dgc2__9[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__9[f]=np.select(list9, choicelist)

In [142]:
for _, f in enumerate(listdata1):
    list10 = [(dgc2__10[f]<=0.1), (dgc2__10[f]>0.1)&(dgc2__10[f]<=1), (dgc2__10[f]>1)&(dgc2__10[f]<=5),(dgc2__10[f]>5)&(dgc2__10[f]<=10),(dgc2__10[f]>10)&(dgc2__10[f]<=20),(dgc2__10[f]>20)&(dgc2__10[f]<=40),(dgc2__10[f]>40)&(dgc2__10[f]<=70),(dgc2__10[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__10[f]=np.select(list10, choicelist)

In [143]:
for _, f in enumerate(listdata2):
    list11 = [(dgc2__11[f]<=0.1), (dgc2__11[f]>0.1)&(dgc2__11[f]<=1), (dgc2__11[f]>1)&(dgc2__11[f]<=5),(dgc2__11[f]>5)&(dgc2__11[f]<=10),(dgc2__11[f]>10)&(dgc2__11[f]<=20),(dgc2__11[f]>20)&(dgc2__11[f]<=40),(dgc2__11[f]>40)&(dgc2__11[f]<=70),(dgc2__11[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__11[f]=np.select(list11, choicelist)

In [144]:
for _, f in enumerate(listdata3):
    list12 = [(dgc2__12[f]<=0.1), (dgc2__12[f]>0.1)&(dgc2__12[f]<=1), (dgc2__12[f]>1)&(dgc2__12[f]<=5),(dgc2__12[f]>5)&(dgc2__12[f]<=10),(dgc2__12[f]>10)&(dgc2__12[f]<=20),(dgc2__12[f]>20)&(dgc2__12[f]<=40),(dgc2__12[f]>40)&(dgc2__12[f]<=70),(dgc2__12[f]>70)]
    choicelist = [0,1,5,10,20,40,70,100]
    dgc2__12[f]=np.select(list12, choicelist)

In [145]:
dgc2__1=dgc2__1.drop(['4hr','7hr','10hr','13hr'],axis=1)
dgc2__2=dgc2__2.drop(['16hr','19hr','22hr','25hr'],axis=1)
dgc2__3=dgc2__3.drop(['28hr','31hr','34hr'],axis=1)
dgc2__4=dgc2__4.drop(['4hr','7hr','10hr','13hr'],axis=1)
dgc2__5=dgc2__5.drop(['16hr','19hr','22hr','25hr'],axis=1)
dgc2__6=dgc2__6.drop(['28hr','31hr','34hr'],axis=1)
dgc2__7=dgc2__7.drop(['4hr','7hr','10hr','13hr'],axis=1)
dgc2__8=dgc2__8.drop(['16hr','19hr','22hr','25hr'],axis=1)
dgc2__9=dgc2__9.drop(['28hr','31hr','34hr'],axis=1)
dgc2__10=dgc2__10.drop(['4hr','7hr','10hr','13hr'],axis=1)
dgc2__11=dgc2__11.drop(['16hr','19hr','22hr','25hr'],axis=1)
dgc2__12=dgc2__12.drop(['28hr','31hr','34hr'],axis=1)

In [146]:
a0=pd.merge(dgc2__1, dgc2__2, on=['sd', 'sgg', 'umd', 'x', 'y', 'date','variable'], how= 'inner')

In [147]:
a1=pd.merge(a0, dgc2__3, on=['sd', 'sgg', 'umd', 'x', 'y', 'date','variable'], how= 'inner')

In [148]:
b0=pd.merge(dgc2__4, dgc2__5, on=['sd', 'sgg', 'umd', 'x', 'y', 'date','variable'], how= 'inner')

In [149]:
b1=pd.merge(b0, dgc2__6, on=['sd', 'sgg', 'umd', 'x', 'y', 'date','variable'], how= 'inner')

In [150]:
c0=pd.merge(dgc2__7, dgc2__8, on=['sd', 'sgg', 'umd', 'x', 'y', 'date','variable'], how= 'inner')

In [151]:
c1=pd.merge(c0, dgc2__9, on=['sd', 'sgg', 'umd', 'x', 'y', 'date','variable'], how= 'inner')

In [152]:
d0=pd.merge(dgc2__10, dgc2__11, on=['sd', 'sgg', 'umd', 'x', 'y', 'date','variable'], how= 'inner')

In [153]:
d1=pd.merge(d0, dgc2__12, on=['sd', 'sgg', 'umd', 'x', 'y', 'date','variable'], how= 'inner')

In [154]:
RAIN2=pd.concat([a1,b1,c1,d1])

In [155]:
RAIN2=RAIN2.drop(['variable'],axis=1)

In [156]:
RAIN2

,sd,sgg,umd,x,y,2day_sum,2day_max,date,1day_sum,1day_max,day_sum,day_max
0,경상북도,포항시남구,구룡포읍,105,94,1.0,1.0,20110709,0.0,0.0,124.0,94.0
1,경상북도,포항시남구,연일읍,102,94,2.0,1.0,20110709,0.0,0.0,103.0,73.0
2,경상북도,포항시남구,오천읍,103,93,0.0,0.0,20110709,0.0,0.0,109.0,80.0
3,경상북도,포항시남구,대송면,102,93,2.0,1.0,20110709,0.0,0.0,108.0,76.0
4,경상북도,포항시남구,동해면2,104,94,0.0,0.0,20110709,0.0,0.0,112.0,84.0
...,...,...,...,...,...,...,...,...,...,...,...,...
632,경상남도,합천군,쌍백면,81,81,0.0,0.0,20140825,5.0,0.0,79.0,46.0
633,경상남도,합천군,삼가면,81,80,0.0,0.0,20140825,5.0,0.0,89.0,51.0
634,경상남도,합천군,가회면,79,81,0.0,0.0,20140825,4.0,0.0,76.0,43.0
635,경상남도,합천군,대병면,79,83,0.0,0.0,20140825,3.0,0.0,57.0,33.0
636,경상남도,합천군,용주면,81,83,0.0,0.0,20140825,2.0,0.0,66.0,39.0

In [157]:
RAIN2.rename(columns = {'2day_sum' : '2day_sum_rain','2day_max' : '2day_max_rain','1day_sum' : '1day_sum_rain','1day_max' : '1day_max_rain','day_sum' : 'day_sum_rain','day_max' : 'day_max_rain'}, inplace = True)

In [158]:
AAA1=weather__2.iloc[:4459, :] 
AA2=weather__2.iloc[4459:,:]
AAA2=AA2.drop(['2day_sum_rain','2day_max_rain','1day_sum_rain','1day_max_rain','day_sum_rain','day_max_rain'],axis=1)
AAA_2 = pd.merge( AAA2, RAIN2, on=['sd', 'sgg', 'umd', 'x', 'y','date', 'umd'], how='inner')
SRAIN__2=pd.concat([AAA1,AAA_2])

In [159]:
SRAIN__2.to_csv('SRAIN__22.csv', index=False, encoding='CP949')